'use strict';
// Gate A canonical review-records doc: committed bytes must equal the
// deterministic generator output (no drift, no hand edits).
const test=require('node:test'),assert=require('node:assert');
const {execFileSync}=require('node:child_process');
test('canonical review-records doc matches generated bytes (deterministic)',()=>{
 const out=execFileSync(process.execPath,['scripts/track-b/gate-a-canonical-records.js','--check'],{encoding:'utf8'});
 assert.match(out,/CHECK OK/);
});
