'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{digest}=require('../../src/clean-runtime/contracts/canonical'),C=require('../../src/clean-runtime/school/display-optics-evidence/candidate'),{buildExtendedWorldReplayCandidate}=require('../../src/clean-runtime/school/scene-extension-replay/candidate'),packet=require('../../evidence/track-b/scene-camera-candidate/packet-v1_5.json'),capture=require('../../evidence/track-b/scene-camera-candidate/v1_5-capture/r3-sweep-full.json'),manifest=require('../../evidence/track-b/scene-camera-candidate/v1_5-capture/source-artifact-manifest.json'),fs=require('node:fs'),crypto=require('node:crypto');
function args(){const w=buildExtendedWorldReplayCandidate({packet});return {packet,genesis:w.genesis,committedWorld:w.after,optics:C.sourceOptics,projectionMatrixElements:C.sourceProjection,measuredCanvasRect:capture.shots[0].canvasRect}}
test('pinned capture host and Three reproduce exact optics; every measured canvas fits authored near body, read-only',async()=>{
 for(const path of ['tests/track-b/admission-evidence-host/host.html','tests/track-b/admission-evidence-host/vendor/three.module.js'])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),manifest.sources.find(s=>s.path===path).sha256);
 const host=fs.readFileSync('tests/track-b/admission-evidence-host/host.html','utf8');assert.ok(host.includes('new THREE.PerspectiveCamera(55,1200/700,.1,40)'));assert.ok(host.includes('renderer.setSize(1200,700)'));
 const T=await import('./admission-evidence-host/vendor/three.module.js'),camera=new T.PerspectiveCamera(55,1200/700,.1,40);assert.deepEqual(camera.projectionMatrix.elements,C.sourceProjection);
 assert.equal(capture.shots.length,17);for(const shot of capture.shots){const a={...args(),measuredCanvasRect:shot.canvasRect},before=digest(a),r=C.inspectDisplayOpticsCandidate(a);assert.equal(r.status,'OPTICS_EVIDENCE_CONTAINED_NOT_OPERATIONALLY_ADMITTED');assert.deepEqual(r.nearFrustumContainingHalfExtentsMicrounits,{halfWidth:89242,halfHeight:52058});assert.equal(digest(a),before);assert.deepEqual(r,C.inspectDisplayOpticsCandidate(a))}
});
test('changed projection/fov/zoom/aspect/near/far/view-offset/canvas/world/genesis cannot reuse capture evidence',()=>{
 for(const kind of ['projection','fov','zoom','aspect','near','far','view','canvas','world','genesis']){const a=structuredClone(args());if(kind==='projection')a.projectionMatrixElements[0]*=.1;if(kind==='fov')a.optics.verticalFovDegrees=170;if(kind==='zoom')a.optics.zoom=.1;if(kind==='aspect')a.optics.aspect=4;if(kind==='near')a.optics.nearPlaneMicrounits++;if(kind==='far')a.optics.farPlaneMicrounits++;if(kind==='view')a.optics.viewOffset={offsetX:1};if(kind==='canvas')a.measuredCanvasRect.width++;if(kind==='world')a.committedWorld.stateDigest='changed';if(kind==='genesis')a.genesis.stateDigest='changed';assert.equal(C.inspectDisplayOpticsCandidate(a).status,'UNKNOWN',kind)}
});
