'use strict';const test=require('node:test'),assert=require('node:assert/strict'),A=require('../../src/clean-runtime/authoring'),{digest}=require('../../src/clean-runtime/contracts/canonical'),P=require('../../src/clean-runtime/school/scene-extension-admission/pins'),E=require('../../src/clean-runtime/school/scene-extension-admission/executor'),S=require('../../src/clean-runtime/school/scene-extension-admission/sweep-verifier'),R=require('../../src/clean-runtime/school/scene-extension-admission/review-verifier'),G=require('../../src/clean-runtime/school/scene-camera-geometry'),packet=require('../../evidence/track-b/scene-camera-candidate/packet-v1_5.json');
// Synthetic reviewed strings exercise validators only; NOT owner evidence.
function fixture(){const d=E.definition(packet),r={scope:R.SCOPE,effectScope:d.effectScope,packetDigest:d.packetDigest,worldDigest:d.worldDigest,reviewDecision:'APPROVED_FOR_SLICE',ownerDecision:'ADMIT',reviewId:'test-only-review-not-owner',reviewEvidenceRefs:['test-only'],ownerMessageRef:'test-only:reply',ownerQuestionRef:'test-only:question',questionPacketDigest:d.packetDigest,questionEffectScope:d.effectScope};r.reviewRecordDigest=digest(r);const ref=A.refFor(E.TYPE,d),draft=A.createDraft({envelopeId:'test-only-envelope',definitionRef:ref}),validated=A.transitionEnvelope(draft,'VALIDATED',{validationEvidenceRefs:['test-only-validator']}),patch={reviewId:r.reviewId,reviewScope:r.scope,reviewDecision:r.reviewDecision,reviewedDefinitionDigest:ref.definitionDigest,reviewedDefinitionRevision:ref.revision,reviewEvidenceRefs:['review-record-sha256:'+r.reviewRecordDigest],ownerDecisionMessageRef:r.ownerMessageRef,ownerDecisionQuestionRef:r.ownerQuestionRef},reviewed=A.transitionEnvelope(validated,'REVIEWED',patch),envelope=A.transitionEnvelope(reviewed,'VERIFIED_FOR_SLICE',patch);return {packet,definition:d,envelope,reviewRecord:r}}
test('typed landed sweep independently verifies actual pixels and source hashes',()=>{assert.equal(S.verifySweepEvidence({packet,initialWorld:G.validatePacket(packet),sweepEvidence:S.wrapper(packet)}),true)});
test('candidate preparation uses imported verifiers and never executes admission',()=>{const r=E.inspectCandidate(fixture());assert.equal(r.status,'PREPARED_NOT_ADMITTED');assert.equal(packet.extension.status,'AUTHORED_CANDIDATE_NOT_ADMITTED');assert.equal(E.createRegistry().snapshot().length,0)});
test('forged caller verifier rejected before any verification',()=>{const f=fixture();assert.equal(E.inspectCandidate({...f,verifySweepEvidence:()=>true}).reason,'CALLER_VERIFIER_OR_EXTRA_INPUT_FORBIDDEN');assert.equal(E.inspectCandidate({...f,verifyReviewRecord:()=>true}).reason,'CALLER_VERIFIER_OR_EXTRA_INPUT_FORBIDDEN')});
test('wrong scope and missing original question evidence fail closed',()=>{for(const field of ['ownerQuestionRef','ownerMessageRef']){const f=fixture();f.reviewRecord[field]='';assert.equal(E.inspectCandidate(f).status,'UNKNOWN')}const f=fixture();f.envelope=A.transitionEnvelope(A.createDraft({envelopeId:'wrong-scope',definitionRef:A.refFor(E.TYPE,f.definition)}),'VALIDATED',{validationEvidenceRefs:['test']});assert.equal(E.inspectCandidate(f).status,'UNKNOWN');assert.equal(R.verifyReviewRecord({packet,reviewRecord:{...fixture().reviewRecord,scope:'R1'}}),false)});
test('stale source and packet pins fail closed',()=>{for(const path of ['source','packet']){const f=fixture();f.definition=structuredClone(f.definition);if(path==='source')f.definition.sourcePins[0].sha256='0'.repeat(64);else f.definition.packetDigest='0'.repeat(64);f.definition.canonicalDigest=A.digest(f.definition);assert.equal(E.inspectCandidate(f).status,'UNKNOWN')}assert.equal(S.verifySweepEvidence({packet,initialWorld:G.validatePacket(packet),sweepEvidence:{...S.wrapper(packet),manifestDigest:'0'.repeat(64)}}),false)});
test('R1 envelope cannot be replayed against scene extension',()=>{const f=fixture();const d={bodyDefinitionId:'test-only-r1',bodyRevision:1,canonicalDigest:'1'.repeat(64)};f.envelope=A.createDraft({envelopeId:'r1-test-only',definitionRef:A.refFor('PHYSICAL_BODY',d)});assert.equal(E.inspectCandidate(f).status,'UNKNOWN')});
test('revoked/rejected/deferred/superseded record reuse fails closed in isolated registry',()=>{for(const decision of ['REVOKED','REJECTED','DEFERRED','SUPERSEDED']){const f=fixture(),registry=E.createRegistry();registry.recordInert({extensionId:f.definition.extensionId,decision,decisionMessageRef:'test-only:revocation',decisionQuestionRef:'test-only:scope',expectedDefinitionDigest:f.definition.canonicalDigest});assert.equal(registry.inspect(f).reason,'RECORD_INERT_OR_REVOKED');assert.equal(registry.snapshot()[0].decision,decision)}});
test('OPERATIONAL effect is declared but has no executable admission path',()=>{const f=fixture();f.definition=E.definition(packet,'OPERATIONAL');assert.equal(E.inspectCandidate(f).reason,'OPERATIONAL_INTEGRATION_NOT_IMPLEMENTED');assert.throws(()=>E.definition(packet,'ANYTHING'))});
test('owner question/effect and review digest cannot be replaced silently',()=>{const f=fixture();f.reviewRecord={...f.reviewRecord,questionEffectScope:'OPERATIONAL'};assert.equal(E.inspectCandidate(f).status,'UNKNOWN');assert.equal(P.exactPins(P.sourcePins()),true)});

test('a valid digest envelope with wrong scope is rejected, not merely a malformed draft',()=>{const f=fixture();f.envelope=structuredClone(f.envelope);f.envelope.reviewScope='GATE_A_R1';delete f.envelope.envelopeDigest;f.envelope=A.validateEnvelope(f.envelope).envelope;assert.equal(E.inspectCandidate(f).status,'UNKNOWN')});
test('superseded verified envelope remains inert even with intact owner/question refs',()=>{const f=fixture();f.envelope=A.supersede({activeEnvelope:f.envelope,supersedingEnvelopeId:'test-only-next',evidenceRefs:['test-only']});assert.equal(E.inspectCandidate(f).status,'UNKNOWN')});

test('raw generic admit SCENE_EXTENSION cannot bypass executor even with verified envelope',()=>{const f=fixture();assert.equal(A.admit({definitionType:E.TYPE,definition:f.definition,envelope:f.envelope,expectedScope:R.SCOPE}).status,'REJECTED');assert.equal(A.admit({definitionType:E.TYPE,definition:f.definition,envelope:f.envelope}).failure.code,'SCENE_EXTENSION_EXECUTOR_REQUIRED')});
test('defer applies to exact revision; new revision can be prepared; history never overwritten',()=>{const f=fixture(),r=E.createRegistry();r.recordInert({extensionId:f.definition.extensionId,extensionRevision:1,decision:'DEFERRED',decisionMessageRef:'test:defer',decisionQuestionRef:'test:question',expectedDefinitionDigest:f.definition.canonicalDigest});r.recordInert({extensionId:f.definition.extensionId,extensionRevision:1,decision:'REVOKED',decisionMessageRef:'test:revoke',decisionQuestionRef:'test:question',expectedDefinitionDigest:f.definition.canonicalDigest});assert.deepEqual(r.snapshot().map(x=>x.decision),['DEFERRED','REVOKED']);assert.equal(r.snapshot()[1].priorDecisionIndex,0);const next={...f,definition:E.definition(packet,'EVIDENCE_ONLY_CAMERA_COVERAGE',2)};assert.notEqual(r.inspect(next).reason,'RECORD_INERT_OR_REVOKED');assert.equal(r.inspect(f).reason,'RECORD_INERT_OR_REVOKED')});
