'use strict';
// Loopback-only candidate evidence host. No runtime commit/admission surface.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const vendorBytes=fs.readFileSync(path.join(__dirname,'vendor/three.module.js'));if(crypto.createHash('sha256').update(vendorBytes).digest('hex')!=='76dea8151bc9352aef3528b4262e249b2604f62543828328db978d060d61a495')throw Error('EVIDENCE_RENDER_RUNTIME_PIN_MISMATCH');
const packet=require('../../../evidence/track-b/scene-camera-candidate/packet-v1_5.json');
const {validatePacket,evaluateCandidateVolumes}=require('../../../src/clean-runtime/school/scene-camera-geometry'),{projectKnownBodyBounds}=require('../../../src/clean-runtime/school/door-legality-adapter'),{model}=require('../../../src/clean-runtime/school/scene-v2/package'),{digest}=require('../../../src/clean-runtime/contracts/canonical');
const initial=validatePacket(packet),entities=Object.values(initial.entities).map(e=>({entityId:e.entityId,physicalBodyRef:e.physicalBodyRef,transform:e.transform,lifecycle:e.lifecycleState,bounds:projectKnownBodyBounds(e),supportRelations:initial.supportRelations.filter(r=>r.supportedEntityId===e.entityId)}));
const binding={kind:'CANDIDATE_AUTHORITY_BOUNDS_MESH_NOT_REALISTIC_ASSET',worldDigest:initial.stateDigest,packetDigest:digest(packet),surfaceModelDigest:model.surfaceModelDigest,entities,surfaces:model.surfaces,sweepSpec:packet.sweepSpec,cameraBody:packet.cameraBody,admitted:false,gameplay:false};
let last=null;
const server=http.createServer((req,res)=>{if(req.socket.remoteAddress!=='127.0.0.1'||req.headers.host!==`127.0.0.1:${req.socket.localPort}`){res.writeHead(403);return res.end()}
 const send=x=>{res.setHeader('content-type','application/json');res.end(JSON.stringify(x))};
 if(req.method==='GET'&&req.url==='/')return res.end(fs.readFileSync(path.join(__dirname,'host.html')));
 if(req.method==='GET'&&req.url==='/vendor/three.module.js'){res.setHeader('content-type','text/javascript');return res.end(fs.readFileSync(path.join(__dirname,'vendor/three.module.js')))}
 if(req.method==='GET'&&req.url==='/bindings')return send(binding);
 if(req.method==='POST'&&req.url==='/camera'&&req.headers.origin===`http://127.0.0.1:${req.socket.localPort}`){let body='';req.on('data',b=>{body+=b;if(body.length>2048)req.destroy()});req.on('end',()=>{try{const data=JSON.parse(body);if(data.negative){const altered=structuredClone(packet),t=altered.sweepSpec.waypoints[0].transform;const targets={belowFloor:[0,-1000000,1000000],wall:[-7000000,1600000,1000000],closedDoor:[5400000,1600000,-3840000],insideSolid:[0,1200000,-3500000],outsideBounds:[10000000,1600000,0]};t.positionMicrounits=targets[data.negative];if(!t.positionMicrounits)return send({renderAllowed:false,reason:'UNKNOWN_NEGATIVE'});altered.extension.sweepSpecRef.digest=digest(altered.sweepSpec);const verdict=evaluateCandidateVolumes({packet:altered,proposedState:initial,cameraTransform:t});return send({renderAllowed:false,verdict,classification:'HOSTILE_CANDIDATE_POSE_NOT_ADMITTED'})}const w=packet.sweepSpec.waypoints.find(w=>w.id===data.id);if(!w)return send({renderAllowed:false,reason:'UNKNOWN_VIEWPOINT'});const verdict=structuredClone(evaluateCandidateVolumes({packet,proposedState:initial,cameraTransform:w.transform,previousCameraTransform:last}));if(verdict.evidence?.componentVerdict!=='CANDIDATE_VOLUMES_CLEAR')return send({renderAllowed:false,verdict});let transform=w.transform;if(data.transition){const from=packet.sweepSpec.waypoints.find(x=>x.id===data.transition.from),alpha=data.transition.alpha;if(!from||![.25,.5,.75].includes(alpha))return send({renderAllowed:false,reason:'TRANSITION_INVALID'});const route=evaluateCandidateVolumes({packet,proposedState:initial,cameraTransform:w.transform,previousCameraTransform:from.transform});if(route.evidence?.componentVerdict!=='CANDIDATE_VOLUMES_CLEAR')return send({renderAllowed:false,verdict:route});const position=from.transform.positionMicrounits.map((x,i)=>Math.round(x*(1-alpha)+w.transform.positionMicrounits[i]*alpha)),target=packet.sweepSpec.transitionContract.targetMicrounits,dx=target[0]-position[0],dy=target[1]-position[1],dz=target[2]-position[2],yaw=Math.atan2(-dx,-dz),pitch=Math.atan2(dy,Math.hypot(dx,dz)),sy=Math.sin(yaw/2),cy=Math.cos(yaw/2),sx=Math.sin(pitch/2),cx=Math.cos(pitch/2);transform={positionMicrounits:position,orientation:[cy*sx,sy*cx,-sy*sx,cy*cx],nearPlaneMicrounits:w.transform.nearPlaneMicrounits};verdict.routeProof=route;verdict.interpolation='AUTHORED_SEGMENT_POSITION_FIXED_TARGET_LOOK_AT_CONTAINED_BY_ROTATION_ENVELOPE'}last=w.transform;send({renderAllowed:true,transform,verdict,classification:'EVIDENCE_ONLY_NOT_ADMITTED',worldDigest:initial.stateDigest})}catch(e){send({renderAllowed:false,reason:String(e.message)})}});return}
 res.writeHead(404);res.end();
});server.listen(0,'127.0.0.1',()=>console.log('http://127.0.0.1:'+server.address().port));
