from PIL import Image,ImageDraw
import json,hashlib,os
x=json.load(open('/downloads/r3-sweep-full.json'));colors={'school-casualty-adult-v1':(255,0,0),'school-medical-bag':(0,255,0),'school-treatment-chair':(0,0,255)};rows=[];rect=x['canvasRect'];thumb=Image.new('RGB',(1200,800))
for i,s in enumerate(x['shots']):
 rect=s['canvasRect'];im=Image.open(s['idPath']).convert('RGB');row={'name':s['name'],'beautySha256':hashlib.sha256(open(s['path'],'rb').read()).hexdigest(),'idSha256':hashlib.sha256(open(s['idPath'],'rb').read()).hexdigest(),'entities':[]}
 for e,color in colors.items():
  pts=[(j%im.width,j//im.width) for j,c in enumerate(im.get_flattened_data()) if c==color];b=next(t['pixelBounds'] for t in s['frame']['projectedBounds'] if t['entityId']==e);ok=all(b[0]+rect['x']-2<=px<=b[2]+rect['x']+2 and b[1]+rect['y']-2<=py<=b[3]+rect['y']+2 for px,py in pts);row['entities'].append({'entityId':e,'visiblePixelCount':len(pts),'pixelsInsideCommittedProjectedBounds':bool(pts) and ok,'projectedPixelBounds':b,'fullyFramed':0<=b[0]<b[2]<=rect['width'] and 0<=b[1]<b[3]<=rect['height']})
 rows.append(row);im=Image.open(s['path']).convert('RGB');im.thumbnail((240,158));a=(i%5)*240;b=(i//5)*200;thumb.paste(im,(a,b));ImageDraw.Draw(thumb).text((a+3,b+160),s['name'],fill='white')
proof={'classification':'SOURCE_BOUND_BOUNDS_MESH_RASTER_ALIGNMENT_ONLY','worldDigest':x['bindings']['worldDigest'],'packetDigest':x['bindings']['packetDigest'],'canvasRect':rect,'boundaryMarginPixels':2,'all17PatientChairBagVisibleAndFramed':all(e['visiblePixelCount']>0 and e['fullyFramed'] for r in rows for e in r['entities']),'all17VisiblePixelsAligned':all(e['pixelsInsideCommittedProjectedBounds'] for r in rows for e in r['entities']),'entityTransformsInvariant':all(s['frame']['entityTransforms']==x['shots'][0]['frame']['entityTransforms'] for s in x['shots']),'rootsMatchAuthoritativeTransforms':all(all(t['position']==[v/1e6 for v in next(e for e in x['bindings']['entities'] if e['entityId']==t['entityId'])['transform']['positionMicrounits']] and t['orientation']==next(e for e in x['bindings']['entities'] if e['entityId']==t['entityId'])['transform']['orientation'] and t['scale']==[v/1e6 for v in next(e for e in x['bindings']['entities'] if e['entityId']==t['entityId'])['transform']['scaleMicrounits']] for t in s['frame']['entityTransforms']) for s in x['shots']),'meshWorldBoundsMatchPhysicalBodies':all(all(all(abs(b['worldBounds'][side][i]-(e['bounds'][side+axis]+e['transform']['positionMicrounits'][i])/1e6)<1e-7 for i,axis in enumerate('XYZ') for side in ['min','max']) for b in s['frame']['projectedBounds'] for e in [next(e for e in x['bindings']['entities'] if e['entityId']==b['entityId'])]) for s in x['shots']),'parallaxMeasured':all(len(set(tuple(e['projectedPixelBounds']) for r in rows for e in r['entities'] if e['entityId']==entity))>1 for entity in colors),'negativeReplayDeterministic':all(x['negatives'][i]['result']==x['negatives'][i+5]['result'] for i in range(5)),'negativeNoRender':all(n['before']==n['after']==17 and n['result']['verdict']['outcome']=='FAIL' for n in x['negatives']),'externalRequests':x['externalRequests'],'errors':x['errors'],'rows':rows,'limitations':['NO_REALISTIC_ASSET_OR_INTEGRATED_SHELL_PROOF','UNIT_OCCLUDED_NOT_CLAIMED_VISIBLE','NO_SCENE_ADMISSION','TWO_PIXEL_MARGIN_FOR_AABB_RASTER_BOUNDARY','AUTHORITY_DERIVED_AGGREGATE_BOXES_NOT_SUBMESH_CONTACT_CERTIFICATION']};json.dump(proof,open('/downloads/r3-sweep-pixel-verdict.json','w'),indent=2);print({k:v for k,v in proof.items() if k!='rows'});thumb.save('/downloads/r3-sweep-contact-sheet.png')
