'use strict';
// TRACK B / PHASE B3 evidence: male casualty visual dimensioned to the certified adult-v1 envelope.
const test=require('node:test'),assert=require('node:assert/strict'),
 {buildVisualCasualty}=require('../../src/clean-runtime/school/scene-v2/visual-casualty'),
 {buildVisualSceneDescriptor}=require('../../src/clean-runtime/school/scene-v2/visual-descriptor'),
 D=require('../../src/clean-runtime/school/definitions/adult-v1-male-supine-floor');
test('casualty visual is dimensioned exactly to the certified adult-v1 envelope',()=>{const v=buildVisualCasualty();assert.equal(v.status,'DIMENSIONED_TO_CERTIFIED_ENVELOPE');assert.deepEqual(v.envelopeCheck.dimensionsMicrounits,[660000,302000,1946000]);assert.equal(v.envelopeCheck.floorContactY0,true);assert.equal(v.envelopeCheck.componentUnionEqualsAggregateBounds,true);assert.equal(v.components.length,5);assert.deepEqual(v.components.map(c=>c.componentId).sort(),['head','left-arm','legs','right-arm','torso']);for(const c of v.components){assert.equal(c.floorContact,true,c.componentId);assert.equal(c.worldAabbMicrounits.minY,0,c.componentId)}});
test('placement comes from the authoritative descriptor, never from visual data',()=>{const d=buildVisualSceneDescriptor(),v=buildVisualCasualty(d),e=d.entities.find(x=>x.entityId==='school-casualty-adult-v1');assert.deepEqual(v.authoritativeTransformMicrounits,e.transform);assert.equal(v.entityRef.physicalBodyRef.digest,D.BODY.canonicalDigest);assert.equal(v.entityRef.profileRef.subjectSex,'MALE');assert.equal(v.entityRef.postureRef.semanticType,'SUPINE_FLOOR');assert.equal(v.entityRef.postureRef.digest,D.POSTURE.canonicalDigest)});
test('physical posture stays certified SUPINE_FLOOR; visual pose is static and separate',()=>{const v=buildVisualCasualty();assert.equal(v.physicalPosture.semantic,'SUPINE_FLOOR');assert.equal(v.physicalPosture.source,'CERTIFIED_AUTHORITATIVE_STATE');assert.equal(v.physicalPosture.visualMayAlter,false);assert.equal(v.visualPose.kind,'STATIC');assert.equal(v.visualPose.matchesCertifiedPosture,true);assert.equal(v.visualPose.articulation,false);assert.equal(v.visualPose.deformation,false);assert.equal(v.boundary.visualPoseFeedsPhysicalPosture,false);assert.equal(v.boundary.physicalProof,false);assert.equal(v.boundary.geometryGateBypass,false)});
test('VALIDATED-not-VERIFIED status caveat is carried visibly',()=>{const v=buildVisualCasualty();assert.equal(v.statusCaveat.gateResult,'PASS_PENDING_LIFECYCLE_REVIEW');assert.equal(v.statusCaveat.bodyLifecycle,'AUTHORED_NEW_DRAFT/VALIDATED/AWAITING_USER_GATE_REVIEW');assert.equal(v.statusCaveat.verifiedForSlice,false);assert(v.statusCaveat.caveat.includes('NOT VERIFIED_FOR_SLICE'))});
test('non-identity orientation is rejected (rotated contacts are a declared unknown)',()=>{const d=buildVisualSceneDescriptor();const tampered=JSON.parse(JSON.stringify(d));tampered.entities.find(x=>x.entityId==='school-casualty-adult-v1').transform.orientation=[0,0,707107,707107];const v=buildVisualCasualty(tampered);assert.equal(v.status,'REJECTED');assert.equal(v.code,'NON_IDENTITY_ORIENTATION_UNSUPPORTED')});
test('body digest mismatch is rejected',()=>{const d=buildVisualSceneDescriptor();const tampered=JSON.parse(JSON.stringify(d));tampered.entities.find(x=>x.entityId==='school-casualty-adult-v1').physicalBodyRef.digest='0'.repeat(64);const v=buildVisualCasualty(tampered);assert.equal(v.status,'REJECTED');assert.equal(v.code,'BODY_DIGEST_MISMATCH')});
test('visual is deterministic, deeply frozen plain data with integer microunits only',()=>{const a=buildVisualCasualty(),b=buildVisualCasualty();assert.equal(a.visualDigest,b.visualDigest);const walk=(v,p)=>{if(typeof v==='number')assert(Number.isInteger(v),'non-integer at '+p);if(v&&typeof v==='object'){assert(Object.isFrozen(v),'not frozen at '+p);for(const k of Object.keys(v))walk(v[k],p+'.'+k)}assert.notEqual(typeof v,'function')};walk(a,'$')});
