'use strict';
// TRACK B / PHASE B5 evidence: browser preview bundle + page integrity.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execSync}=require('node:child_process'),
 ROOT=path.join(__dirname,'../..'),
 {buildVisualSceneDescriptor}=require('../../src/clean-runtime/school/scene-v2/visual-descriptor'),
 {buildVisualSurfaceSet}=require('../../src/clean-runtime/school/scene-v2/visual-surfaces'),
 {buildVisualCasualty}=require('../../src/clean-runtime/school/scene-v2/visual-casualty'),
 {buildVisualEquipment}=require('../../src/clean-runtime/school/scene-v2/visual-equipment');
const bundle=()=>JSON.parse(fs.readFileSync(path.join(ROOT,'visual-slice/scene-bundle.json'),'utf8'));
test('bundle build is reproducible and READY with digests matching the live builders',()=>{execSync('node scripts/track-b/build-scene-bundle.js',{cwd:ROOT});const b=bundle(),d=buildVisualSceneDescriptor(),s=buildVisualSurfaceSet(),c=buildVisualCasualty(d),e=buildVisualEquipment(d);assert.equal(b.status,'READY');assert.equal(b.inputs.descriptorDigest,d.descriptorDigest);assert.equal(b.inputs.surfaceSetDigest,s.setDigest);assert.equal(b.inputs.casualtyDigest,c.visualDigest);assert.equal(b.inputs.equipmentDigest,e.visualDigest);assert.equal(b.inputs.sourcePackageDigest,'187cf1a4c0af01ef12087879f44eeb88a355499a860665e29cdb2f5ab0d06aec');assert.equal(b.inputs.worldStateDigest,'fa1bbaa985a63a8bfa30c2bbd7fbaf14b2c4972d985815a093bdd68f7fe954ea');assert.equal(b.git.branch,'candidate5-track-b-visual-slice');assert.match(b.git.commit,/^[0-9a-f]{40}$/)});
test('bundle carries the mandatory caveats, distinction banner and camera/lighting honesty notes',()=>{const b=bundle();assert.equal(b.banner.warning,'VISUALS ARE NOT CERTIFIED PHYSICS');assert(b.banner.distinction.includes('presentation-only projection'));assert.equal(b.statusCaveats.casualty.verifiedForSlice,true);assert.equal(b.statusCaveats.chair.verifiedForSlice,true);assert(b.camera.note.includes('belongs in the ScenePackage'));assert(b.lighting.note.includes('Visual-only'));assert.equal(b.microunitsPerWorldUnit,1000000)});
test('bundle room/casualty/equipment payloads match the builders exactly',()=>{const b=bundle(),d=buildVisualSceneDescriptor();assert.deepEqual(b.room,JSON.parse(JSON.stringify(buildVisualSurfaceSet().surfaces)));assert.deepEqual(b.casualty,JSON.parse(JSON.stringify(buildVisualCasualty(d))));assert.deepEqual(b.equipment,JSON.parse(JSON.stringify(buildVisualEquipment(d))))});
test('preview page carries the banner, downstream conversion, FPS meter and no production URL',()=>{const html=fs.readFileSync(path.join(ROOT,'visual-slice/index.html'),'utf8');assert(html.includes('VISUALS ARE NOT CERTIFIED PHYSICS'));assert(html.includes('1e6'),'microunit conversion present');assert(html.includes('three@0.160.0'),'pinned three.js');assert(html.includes('FPS(measured on this hardware)'));assert(!html.includes('ko-rishon-first-aid.pages.dev'),'no production URL');const fetches=[...html.matchAll(/fetch\((['"])(.*?)\1/g)].map(x=>x[2]);assert(fetches.length>0,'expected the bundle fetch');for(const u of fetches)assert(u.startsWith('./'),'external data endpoint: '+u)});
test('clean core never imports Three.js and preview layer never writes to authoritative runtime',()=>{const out=execSync('grep -rn "three" src/clean-runtime --include=*.js -il || true',{cwd:ROOT,encoding:'utf8'});assert.equal(out.trim(),'','Three.js reference found in clean core: '+out);const html=fs.readFileSync(path.join(ROOT,'visual-slice/index.html'),'utf8');assert(!html.includes('worldMutationAPI')&&!html.includes('proposeTransaction'),'renderer must not touch authoritative write paths')});
test('preview page wires the PW-2 procedural room behind the same fail-closed pmCheck as the package',()=>{const html=fs.readFileSync(path.join(ROOT,'visual-slice/index.html'),'utf8');
 assert(html.includes("import {buildProceduralRoom} from './package/procedural-room.mjs'"),'page imports the package procedural-room builder');
 assert(html.includes("import {validatePresentationManifest} from './package/presentation-guard.mjs'"),'page imports the package presentation guard');
 assert(html.includes('if(pmCheck.ok){scene.add(buildProceduralRoom(THREE,bundle.room))}'),'procedural room renders ONLY behind pmCheck.ok');
 assert(html.includes("else{for(const s of bundle.room)scene.add(box(s.geometryMicrounits,s.visualOnlyClaims.colorHex,{cast:false}))}"),'certified debug boxes remain the explicit fallback');
 assert(html.includes('PRESENTATION MANIFEST PLACEHOLDER:'),'loud placeholder line - never a silent fallback');
 assert(html.includes('dataset.presentationLayer'),'machine-readable presentation-layer state for smoke and tests');
 const pkg=fs.readFileSync(path.join(ROOT,'visual-slice/package/renderer-package.mjs'),'utf8');
 const pageCall=html.match(/validatePresentationManifest\(presentationManifest,\{map[:,][\s\S]*?sha256hex[^}]*\}\)/)[0];
 const pkgCall=pkg.match(/validatePresentationManifest\(presentationManifest,\{map[:,][\s\S]*?sha256hex[^}]*\}\)/)[0];
 assert.equal(pageCall,pkgCall,'page pmCheck must not drift from the package reference call')});
