'use strict';
// TRACK B / PHASE B2 evidence: visual surfaces with written per-surface lineage.
const test=require('node:test'),assert=require('node:assert/strict'),
 {buildVisualSurfaceSet,SOURCE_SHA256}=require('../../src/clean-runtime/school/scene-v2/visual-surfaces'),
 model=require('../../evidence/verified-architecture-phase2/surface-models/school.json');
test('every visual surface is lineage-evidenced against the locked source and physical model',()=>{const s=buildVisualSurfaceSet();assert.equal(s.status,'LINEAGE_EVIDENCED');assert.equal(s.surfaces.length,10);for(const x of s.surfaces){assert.equal(x.lineage.visualPhysicalLineage,'EVIDENCED');assert.equal(x.lineage.sourceArtifact.sha256,SOURCE_SHA256);assert.equal(x.lineage.sourceRange.locatedInSourceBytes,true,x.visualSurfaceId+' range not located in real bytes');assert.equal(x.lineage.sourceRange.rangeDigestMatches,true,x.visualSurfaceId+' range digest mismatch');assert.equal(x.lineage.crossCheck.match,true,x.visualSurfaceId+' physical cross-check failed: '+x.lineage.crossCheck.detail);assert.equal(x.lineage.physicalSurfaceRef.surfaceModelRef.digest,model.surfaceModelDigest)}});
test('all physical surfaces in the certified model are covered by a visual surface',()=>{const s=buildVisualSurfaceSet();assert.deepEqual(s.uncoveredPhysicalSurfaces,[]);for(const p of model.surfaces)assert(s.surfaces.some(x=>x.lineage.physicalSurfaceRef.surfaceId===p.surfaceId),'uncovered physical surface '+p.surfaceId)});
test('geometry is integer microunits and matches authored dimensions exactly',()=>{const s=buildVisualSurfaceSet(),by=Object.fromEntries(s.surfaces.map(x=>[x.visualSurfaceId,x]));assert.deepEqual(by['visual:floor'].geometryMicrounits,{minX:-9000000,maxX:9000000,minY:-120000,maxY:0,minZ:-9000000,maxZ:9000000});assert.deepEqual(by['visual:back-wall'].geometryMicrounits,{minX:-9000000,maxX:9000000,minY:0,maxY:6000000,minZ:-4080000,maxZ:-3920000});assert.deepEqual(by['visual:door'].geometryMicrounits,{minX:4725000,maxX:6075000,minY:0,maxY:2900000,minZ:-3900000,maxZ:-3780000});assert.deepEqual(by['visual:locker-2'].geometryMicrounits,{minX:-500000,maxX:500000,minY:0,maxY:2400000,minZ:-3775000,maxZ:-3225000});for(const x of s.surfaces)for(const v of Object.values(x.geometryMicrounits))assert(Number.isInteger(v))});
test('boundary statements hold and panorama is not promoted',()=>{const s=buildVisualSurfaceSet();assert.equal(s.boundary.presentationOnly,true);assert.equal(s.boundary.neverInputToPhysicalRequest,true);assert.equal(s.boundary.physicalProof,false);assert.equal(s.boundary.geometryGateBypass,false);assert.equal(s.boundary.panorama.role,'PIXEL_DIAGNOSTIC_ONLY');assert.equal(s.boundary.panorama.geometryBindingStatus,'UNKNOWN');assert.equal(s.boundary.panorama.promoted,false);assert.equal(s.numericContract.contractId,'ED-P2-02')});
test('set is deeply frozen, deterministic, and plain data',()=>{const a=buildVisualSurfaceSet(),b=buildVisualSurfaceSet();assert.equal(a.setDigest,b.setDigest);const walk=(v,p)=>{if(v&&typeof v==='object'){assert(Object.isFrozen(v),'not frozen at '+p);for(const k of Object.keys(v))walk(v[k],p+'.'+k)}assert.notEqual(typeof v,'function')};walk(a,'$');JSON.parse(JSON.stringify(a))});
