'use strict';
// TRACK B / PHASE B4 evidence: chair and bag visuals dimensioned to certified bodies.
const test=require('node:test'),assert=require('node:assert/strict'),
 {buildVisualEquipment}=require('../../src/clean-runtime/school/scene-v2/visual-equipment'),
 {buildVisualSceneDescriptor}=require('../../src/clean-runtime/school/scene-v2/visual-descriptor'),
 C=require('../../src/clean-runtime/school/definitions/treatment-chair'),
 {SCHOOL_BAG_BODY}=require('../../src/clean-runtime/school/school-physical-contract');
test('chair visual matches the certified body: 0.5x0.9x0.5m, seat plane 0.49m, Y=0 contact',()=>{const v=buildVisualEquipment();assert.equal(v.status,'DIMENSIONED_TO_CERTIFIED_BODIES');assert.deepEqual(v.chair.envelopeCheck.dimensionsMicrounits,[500000,900000,500000]);assert.equal(v.chair.envelopeCheck.seatPlaneYMicrounits,490000);assert.equal(v.chair.envelopeCheck.floorContactY0,true);assert.equal(v.chair.components.length,3);assert.deepEqual(v.chair.components.map(c=>c.componentId),['lower-frame','seat-slab','backrest']);assert.equal(v.chair.entityRef.physicalBodyRef.digest,C.BODY.canonicalDigest);assert.equal(v.chair.entityRef.supportSurfaceRef.digest,C.SURFACE.canonicalDigest);const d=buildVisualSceneDescriptor(),e=d.entities.find(x=>x.entityId==='school-treatment-chair');assert.deepEqual(v.chair.authoritativeTransformMicrounits,e.transform)});
test('chair Gate C caveat is carried visibly',()=>{const v=buildVisualEquipment();assert.equal(v.chair.statusCaveat.gateResult,'PASS_PENDING_USER_REVIEW_FOR_ADMISSION');assert.equal(v.chair.statusCaveat.verifiedForSlice,false)});
test('bag visual matches the locked RECOVERED box .55x.35x.35m with exact floor contact',()=>{const v=buildVisualEquipment();assert.deepEqual(v.bag.envelopeCheck.dimensionsMicrounits,[550000,350000,350000]);assert.equal(v.bag.envelopeCheck.floorContactY0,true);assert.equal(v.bag.entityRef.physicalBodyRef.digest,SCHOOL_BAG_BODY.geometryDigest);assert.equal(v.bag.provenance.classification,'RECOVERED');assert.equal(v.bag.provenance.sourceRange,'school-bag-lockers');assert.equal(v.bag.provenance.sourceDigest,SCHOOL_BAG_BODY.sourceDigest)});
test('authored-vs-authoritative placement difference is recorded, authoritative wins',()=>{const v=buildVisualEquipment();const a=v.bag.authoredVsAuthoritative;assert.equal(a.yDifferenceMicrounits,-5000);assert.deepEqual(a.authoritativePositionMicrounits,[-3000000,175000,1000000]);assert(a.resolution.startsWith('AUTHORITATIVE_TRANSFORM_WINS'));assert.equal(v.bag.worldAabbMicrounits.minY,0)});
test('no equipment beyond bag+chair without the Gate A lifecycle',()=>{const v=buildVisualEquipment();assert.deepEqual(v.equipmentBeyondBagAndChair.included,[]);assert.equal(v.equipmentBeyondBagAndChair.policy,'REQUIRES_GATE_A_LIFECYCLE')});
test('tampered digests and orientations are rejected',()=>{const d=JSON.parse(JSON.stringify(buildVisualSceneDescriptor()));d.entities.find(x=>x.entityId==='school-treatment-chair').physicalBodyRef.digest='0'.repeat(64);assert.equal(buildVisualEquipment(d).code,'BODY_DIGEST_MISMATCH:school-treatment-chair');const d2=JSON.parse(JSON.stringify(buildVisualSceneDescriptor()));d2.entities.find(x=>x.entityId==='school-medical-bag').transform.orientation=[0,707107,0,707107];assert.equal(buildVisualEquipment(d2).code,'NON_IDENTITY_ORIENTATION_UNSUPPORTED:school-medical-bag')});
test('output is deterministic, deeply frozen, integer microunits only',()=>{const a=buildVisualEquipment(),b=buildVisualEquipment();assert.equal(a.visualDigest,b.visualDigest);const walk=(v,p)=>{if(typeof v==='number')assert(Number.isInteger(v),'non-integer at '+p);if(v&&typeof v==='object'){assert(Object.isFrozen(v),'not frozen at '+p);for(const k of Object.keys(v))walk(v[k],p+'.'+k)}assert.notEqual(typeof v,'function')};walk(a,'$')});
