'use strict';
// TRACK B / PHASE B1 evidence: read-only visual scene descriptor.
const test=require('node:test'),assert=require('node:assert/strict'),
 {buildVisualSceneDescriptor,SEMANTIC_SCENE_ID,STATUS_CAVEATS}=require('../../src/clean-runtime/school/scene-v2/visual-descriptor'),
 {PACKAGE}=require('../../src/clean-runtime/school/scene-v2/package');
const GATE_D_WORLD_DIGEST='fa1bbaa985a63a8bfa30c2bbd7fbaf14b2c4972d985815a093bdd68f7fe954ea',GATE_D_PACKAGE_DIGEST='187cf1a4c0af01ef12087879f44eeb88a355499a860665e29cdb2f5ab0d06aec';
function walk(v,fn,path='$'){fn(v,path);if(v&&typeof v==='object')for(const k of Object.keys(v))walk(v[k],fn,path+'.'+k)}
test('descriptor commits through the sole placement path and matches Gate D world',()=>{const d=buildVisualSceneDescriptor();assert.equal(d.status,'COMMITTED');assert.equal(d.sourcePackage.scenePackageDigest,GATE_D_PACKAGE_DIGEST);assert.equal(d.sourcePackage.scenePackageDigest,PACKAGE.scenePackageDigest);assert.equal(d.worldRef.stateDigest,GATE_D_WORLD_DIGEST);assert.equal(d.worldRef.revision,1);assert.equal(d.worldRef.replayMatchesCommittedState,true);assert.deepEqual(d.placementPath,['WorldMutationAPI','PhysicalLegalityPort','SchoolGeometryAdapter','Phase 2 Geometry Gate (PASS, phase2ByteIdentical)'])});
test('descriptor carries exact entity refs, digests and integer microunit transforms',()=>{const d=buildVisualSceneDescriptor();assert.equal(d.entities.length,3);const by=Object.fromEntries(d.entities.map(e=>[e.entityId,e]));assert.deepEqual(by['school-casualty-adult-v1'].transform.positionMicrounits,[0,0,1000000]);assert.deepEqual(by['school-treatment-chair'].transform.positionMicrounits,[-2000000,0,1000000]);assert.deepEqual(by['school-medical-bag'].transform.positionMicrounits,[-3000000,175000,1000000]);assert.equal(by['school-casualty-adult-v1'].physicalState.profileRef.subjectSex,'MALE');assert.equal(by['school-casualty-adult-v1'].physicalState.postureRef.semanticType,'SUPINE_FLOOR');assert.equal(by['school-casualty-adult-v1'].physicalBodyRef.digest,PACKAGE.refs.bodies.casualty.digest);assert.equal(by['school-treatment-chair'].physicalBodyRef.digest,PACKAGE.refs.bodies.chair.digest);assert.equal(by['school-medical-bag'].physicalBodyRef.digest,PACKAGE.refs.bodies.bag.digest);walk(d.entities,(v,p)=>{if(typeof v==='number')assert(Number.isInteger(v),'non-integer number in entities at '+p+': '+v)});const bagRel=d.supportRelations.find(r=>r.relationId==='school:bag:floor');const {SCHOOL_BAG_BODY}=require('../../src/clean-runtime/school/school-physical-contract');assert.deepEqual(bagRel.contactRegionGeometry,SCHOOL_BAG_BODY.geometry,'bag contactRegionGeometry must be verbatim locked meters');const casRel=d.supportRelations.find(r=>r.relationId==='school:casualty:floor');walk(casRel.contactRegionGeometry,(v,p)=>{if(typeof v==='number')assert(Number.isInteger(v),'casualty contactRegionGeometry not integer microunits at '+p)})});
test('descriptor carries canonical support relations and surface model refs',()=>{const d=buildVisualSceneDescriptor();assert.equal(d.supportRelations.length,3);assert.deepEqual(d.supportRelations.map(r=>r.relationId).sort(),['school:bag:floor','school:casualty:floor','school:chair:floor']);for(const r of d.supportRelations){assert.equal(r.surfaceId,'floor');assert.equal(r.surfaceModelRef.digest,d.surfaces.surfaceModelRef.digest)}assert.equal(d.surfaces.surfaceModelRef.id,'school-surface-v1');assert.equal(d.surfaces.surfaceModelRef.revision,1)});
test('descriptor is deeply frozen, plain data, and exposes no mutation handles',()=>{const d=buildVisualSceneDescriptor();walk(d,(v,p)=>{if(v&&typeof v==='object')assert(Object.isFrozen(v),'not frozen at '+p);assert.notEqual(typeof v,'function','function leaked at '+p)});const round=JSON.parse(JSON.stringify(d));assert.equal(round.descriptorDigest,d.descriptorDigest);assert.equal(typeof d.worldMutationAPI,'undefined');assert.equal(typeof d.writer,'undefined');assert.equal(typeof d.proposeTransaction,'undefined')});
test('descriptor digest is deterministic across independent builds',()=>{const a=buildVisualSceneDescriptor(),b=buildVisualSceneDescriptor();assert.equal(a.descriptorDigest,b.descriptorDigest);assert.notEqual(a,b)});
test('numeric contract and boundary statements are explicit',()=>{const d=buildVisualSceneDescriptor();assert.equal(d.numericContract.contractId,'ED-P2-02');assert.equal(d.numericContract.microunitsPerWorldUnit,1000000);assert.equal(d.numericContract.rendererConversion,'DOWNSTREAM_ONLY');assert.equal(d.numericContract.rendererFloatsFeedAuthoritativeState,false);assert.equal(d.boundary.readOnly,true);assert.equal(d.boundary.physicalProof,false);assert.equal(d.boundary.visualsRepresentCertifiedPhysics,false);assert.equal(d.boundary.physicalTruthFromPixels,false);assert.equal(d.boundary.geometryGateBypass,false);assert.equal(d.boundary.rendererMayWriteToAuthoritativeState,false);assert.equal(d.semanticRef.semanticId,SEMANTIC_SCENE_ID)});
test('status caveats and declared unknowns travel visibly',()=>{const d=buildVisualSceneDescriptor();assert.equal(d.statusCaveats.casualty.gateResult,'PASS_PENDING_LIFECYCLE_REVIEW');assert.equal(d.statusCaveats.casualty.bodyLifecycle,'AUTHORED_NEW_DRAFT/VALIDATED/AWAITING_USER_GATE_REVIEW');assert.equal(d.statusCaveats.casualty.verifiedForSlice,false);assert.equal(d.statusCaveats.chair.gateResult,'PASS_PENDING_USER_REVIEW_FOR_ADMISSION');assert.equal(d.statusCaveats.chair.verifiedForSlice,false);assert(d.declaredUnknowns.includes('visual-physical lineage'));assert(d.declaredUnknowns.includes('panorama-geometry lineage'));assert.equal(STATUS_CAVEATS.casualty.verifiedForSlice,false)});
