'use strict';
// Read-only exact CLOSED empty-genesis path mechanics. No gameplay authority.
const {digest,deepFreeze}=require('../../contracts/canonical'),C=require('../door-world-genesis/candidate'),S=require('../door-world-structure/candidate');
const axes=['X','Y','Z'],keys=axes.flatMap(k=>['min'+k,'max'+k]);
function inspectClosedPath({packet,surfaceModel,committedWorld,from,to,...extra}={}){const out=(status,reason,detail={})=>deepFreeze({status,reason,classification:'EXACT_CLOSED_GENESIS_NAVIGATION_PREPARATION_NOT_ADMITTED',operationalStatus:'UNKNOWN',...detail});try{
 if(Object.keys(extra).length)return out('UNKNOWN','CALLER_DOOR_STATE_OR_EXTRA_INPUT_FORBIDDEN');const g=C.prepareGenesis(packet);if(digest(surfaceModel)!==digest(g.surfaceModel)||digest(committedWorld)!==digest(g.genesis))return out('UNKNOWN','EXACT_EMPTY_GENESIS_MODEL_REQUIRED');if(S.validateStructure(surfaceModel).status!=='DOORWAY_FLOOR_STATIC_TOPOLOGY_VALIDATED_NOT_ADMITTED')return out('UNKNOWN','STRUCTURE_INVALID');
 if(![from,to].every(p=>Array.isArray(p)&&p.length===3&&p.every(Number.isSafeInteger)))return out('UNKNOWN','POSITION_NOT_EXACT');
 const camera=packet.cameraBody,h=camera.conservativeVolume.halfExtentsMicrounits,near=camera.nearPlaneMicrounits;if(![h.halfWidth,h.halfHeight,h.halfDepth,near].every(v=>Number.isSafeInteger(v)&&v>0)||near%2)return out('UNKNOWN','CAMERA_ENVELOPE_UNSUPPORTED');const sq=BigInt(h.halfWidth)**2n+BigInt(h.halfHeight)**2n+BigInt(h.halfDepth)**2n;let lo=0n,hi=BigInt(h.halfWidth+h.halfHeight+h.halfDepth);while(lo<hi){const mid=(lo+hi)/2n;if(mid*mid>=sq)hi=mid;else lo=mid+1n}const radius=Number(lo)+near/2+near,sweep=Object.fromEntries(keys.map(k=>[k,(k.startsWith('min')?Math.min:Math.max)(from[axes.indexOf(k.slice(-1))],to[axes.indexOf(k.slice(-1))])+(k.startsWith('min')?-radius:radius)]));if(!Object.values(sweep).every(Number.isSafeInteger))return out('UNKNOWN','SWEEP_OVERFLOW');
 const floor=surfaceModel.surfaces.find(s=>s.surfaceId==='floor'),floorY=Math.round(floor.planeOrDepth.planeY*1e6),room=floor.region.allowed[0],height=Math.min(...surfaceModel.surfaces.filter(s=>s.type==='WALL').flatMap(s=>s.region.volumes.map(v=>Math.round(v.maxY*1e6))));
 const evidence={worldDigest:committedWorld.stateDigest,modelDigest:surfaceModel.surfaceModelDigest,sweepBoundsMicrounits:sweep,radiusMicrounits:radius,floorPlaneMicrounits:floorY,doorStateSource:'EXACT_GENESIS_ENVIRONMENT_RECORD_CLOSED',limitations:['EMPTY_GENESIS_NO_PATIENT_CHAIR_BAG_UNIT_WORLD_PROOF','APRON_EXCLUDED_PENDING_DESTINATION_DECISION','CONSERVATIVE_AABB_FALSE_REJECTION_POSSIBLE','NO_CONTROL_INPUT_RENDER_CLIPPING_OR_OPERATIONAL_AUTHORITY','HEIGHT_BOUND_NOT_CEILING_GEOMETRY','NO_OPEN_STATE_OR_SWING']};
 if(sweep.minY<floorY)return out('BLOCKED_PREPARATION_ONLY','BELOW_AUTHORITATIVE_FLOOR',evidence);if(sweep.maxY>height)return out('BLOCKED_PREPARATION_ONLY','DECLARED_HEIGHT_BOUND',evidence);
 const solids=surfaceModel.surfaces.filter(s=>['WALL','OBSTACLE'].includes(s.type)).flatMap(s=>s.region.volumes.map(v=>({id:s.surfaceId+':'+v.volumeId,b:Object.fromEntries(keys.map(k=>[k,Math.round(v[k]*1e6)]))}))).concat(committedWorld.environmentPhysicalState.doorEntities.map(d=>({id:d.entityId,b:d.collisionBoundsMicrounits})));const hit=solids.find(s=>axes.every(k=>sweep['min'+k]<=s.b['max'+k]&&s.b['min'+k]<=sweep['max'+k]));if(hit)return out('BLOCKED_PREPARATION_ONLY','COMMITTED_CLOSED_STATIC_SOLID_CONTACT',{...evidence,hitSolid:hit.id});
 if(sweep.minX<room.minX*1e6||sweep.maxX>room.maxX*1e6||sweep.minZ<room.minZ*1e6||sweep.maxZ>room.maxZ*1e6)return out('UNKNOWN','ROOM_FLOOR_COVERAGE_OR_APRON_UNAUTHORIZED',evidence);
 return out('CLOSED_PATH_CLEAR_PREPARATION_ONLY_NOT_ADMITTED','EXACT_GENESIS_STATIC_SWEEP_CLEAR',evidence);
 }catch{return out('UNKNOWN','CLOSED_PATH_INPUT_INVALID')}}
module.exports={inspectClosedPath};
