'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {buildV21}=require('../../../scripts/track-b/gate-a-r1v4-package-builder');
const {instantiate}=require('../../../src/clean-runtime/school/scene-v2/instantiate');
const {validateScenePackage}=require('../../../src/clean-runtime/school/scene-v2/validate');
const {createMultiSupportRuntime}=require('../../../src/clean-runtime/multi-support/runtime');
const {schoolGeometryAdapter}=require('../../../src/clean-runtime/school/school-geometry-adapter');
const {model}=require('../../../src/clean-runtime/school/scene-v2/package');
function source(){const p=buildV21(),x=instantiate(p);assert.equal(x.status,'COMMITTED');return {p,x}}
function fresh(){const {p,x}=source();return createMultiSupportRuntime({initialWorld:x.after,legalityPort:schoolGeometryAdapter({surfaceModel:model}),ownerBodyBindings:validateScenePackage(p).ownerBodyBindings})}
function commands(api,change){return api.getWorldState().supportRelations.map(r=>({commandId:'rebind:'+r.relationId,type:'ReplaceSupportRelation',expectedWorldRevision:1,relationId:r.relationId,relation:{...structuredClone(r),boundWorldRevision:2,...(r.supportedEntityId==='school-casualty-adult-v1'?change:{})}}))}
for(const [name,change,reason] of [['wall-mismatch',{surfaceId:'wall'},'SUPPORT_SELECTED_SURFACE_MISMATCH'],['real-wall-mismatch',{surfaceId:'back-wall',expectedSurfaceType:'WALL'},'SUPPORT_SELECTED_SURFACE_MISMATCH'],['stale-reference',{boundWorldRevision:1},'STALE_WORLD_REVISION']])test(name+' atomically preserves world events support index',()=>{const api=fresh(),before=JSON.stringify([api.getWorldState(),api.getEventLog(),api.getSupportIndex()]);const r=api.proposeTransaction({transactionId:name,expectedWorldRevision:1,commands:commands(api,change)});assert.equal(r.status,'REJECTED');assert.equal(r.evidence?.detail?.evidence?.adapterReason||r.evidence?.detail?.code||r.code,reason);assert.equal(JSON.stringify([api.getWorldState(),api.getEventLog(),api.getSupportIndex()]),before)});
for(const [name,surfaceId,type] of [['unknown-both','not-a-surface','FLOOR'],['wall-as-floor','back-wall','FLOOR'],['wall-both','back-wall','WALL']])test(name+' adapter rejects semantic mismatch',()=>{const {x}=source(),w=structuredClone(x.after);w.entities['school-casualty-adult-v1'].physicalState.surfaceId=surfaceId;const r=w.supportRelations.find(r=>r.supportedEntityId==='school-casualty-adult-v1');r.surfaceId=surfaceId;r.expectedSurfaceType=type;const out=schoolGeometryAdapter({surfaceModel:model}).evaluate({worldState:x.after,proposedState:w,command:{commandId:name,entityId:r.supportedEntityId}});assert.equal(out.outcome,'UNKNOWN');assert.equal(out.evidence.adapterReason,'SUPPORT_SURFACE_SEMANTIC_MISMATCH')});
test('benign revision rebind commits; unchanged adapter control passes',()=>{const api=fresh();const r=api.proposeTransaction({transactionId:'benign',expectedWorldRevision:1,commands:commands(api,{})});assert.equal(r.status,'COMMITTED');const {x}=source();assert.equal(schoolGeometryAdapter({surfaceModel:model}).evaluate({worldState:x.after,proposedState:x.after,command:{commandId:'control',entityId:'school-casualty-adult-v1'}}).outcome,'PASS')});
