'use strict';
const {digest}=require('./definitions');
function seal(kind,x,idKey){if(!x||typeof x!=='object'||!x[idKey]||!Number.isInteger(x.revision)||x.revision<1)throw Error('INVALID_INPUT');const y=structuredClone(x);y.recordKind=kind;y.digest=digest(y,'digest');return Object.freeze(y)}
function contactRegion(x){if(!x.supportedBodyRef||!x.geometryRef||!x.expectedContactNormal||!x.expectedContactNormal.frameRef)throw Error('INVALID_INPUT');return seal('CONTACT_REGION_DEFINITION',x,'contactRegionId')}
function supportRelation(x){if(!x.relationId||!['REQUIRED','OPTIONAL'].includes(x.requirement)||!x.bodyRef||!x.contactRegionRef||!x.supportSurfaceRef||x.contactPolicy!=='EXACT_OPPOSED_PHYSICAL_NORMAL'||!Array.isArray(x.frameRefs))throw Error('INVALID_INPUT');const y=structuredClone(x);y.recordKind='SUPPORT_RELATION';y.digest=digest(y,'digest');return Object.freeze(y)}
function refCmp(a,b){for(const k of ['geometryId','frameId','bodyId','contactRegionId']){const c=String(a[k]||'').localeCompare(String(b[k]||''));if(c)return c}if((a.revision||0)!==(b.revision||0))return (a.revision||0)-(b.revision||0);return String(a.digest||'').localeCompare(String(b.digest||''))}
function noConflictingRefs(refs){const seen=new Map;for(const r of refs){if(!r||!r.geometryId||!Number.isInteger(r.revision)||!r.digest)throw Error('INVALID_INPUT');const key=r.geometryId+'@'+r.revision,old=seen.get(key);if(old&&old!==r.digest)throw Error('INVALID_INPUT');if(old)throw Error('INVALID_INPUT');seen.set(key,r.digest)}}
function boundaryFeature(x){if(!x.localFrameRef||!Array.isArray(x.solidGeometryRefs)||!Array.isArray(x.openingRegionRefs))throw Error('INVALID_INPUT');const y=structuredClone(x);noConflictingRefs(y.solidGeometryRefs);noConflictingRefs(y.openingRegionRefs);y.solidGeometryRefs.sort(refCmp);y.openingRegionRefs.sort(refCmp);return seal('BOUNDARY_FEATURE_DEFINITION',y,'boundaryFeatureId')}
function openingBackRef(x){const r=x?.shape?.boundaryFeatureRef||x?.boundaryFeatureRef;if(!r||!r.boundaryFeatureId||!Number.isInteger(r.revision)||r.revision<1||Object.prototype.hasOwnProperty.call(r,'digest'))throw Error('INVALID_INPUT');return Object.freeze({boundaryFeatureId:r.boundaryFeatureId,revision:r.revision})}
module.exports={contactRegion,supportRelation,boundaryFeature,openingBackRef,refCmp};
