'use strict';
const D=require('./definitions'),{digest}=D;
function seal(kind,x,idKey){if(!x||typeof x!=='object'||!x[idKey]||!Number.isInteger(x.revision)||x.revision<1)throw Error('INVALID_INPUT');const y=structuredClone(x);y.recordKind=kind;y.digest=digest(y,'digest');return Object.freeze(y)}
function refCmp(a,b){for(const k of ['childId','geometryId','frameId','bodyId','contactRegionId']){const c=String(a[k]||'').localeCompare(String(b[k]||''));if(c)return c}if((a.revision||0)!==(b.revision||0))return (a.revision||0)-(b.revision||0);return String(a.digest||'').localeCompare(String(b.digest||''))}
function noConflictingRefs(refs,{child=false}={}){const seen=new Map;for(const r of refs){if(!r||!r.geometryId||!Number.isInteger(r.revision)||!r.digest||(child&&!r.childId))throw Error('INVALID_INPUT');const key=(child?r.childId+'@':'')+r.geometryId+'@'+r.revision;if(seen.has(key))throw Error('INVALID_INPUT');seen.set(key,r.digest)}}
function canonicalPolygonVertices(vertices){if(!Array.isArray(vertices)||vertices.length<3)throw Error('INVALID_INPUT');const vs=vertices.map(v=>v.map(String)),seqs=[];for(const base of [vs,[...vs].reverse()])for(let i=0;i<base.length;i++)seqs.push([...base.slice(i),...base.slice(0,i)]);seqs.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));return seqs[0]}
function physicalPlanarDefinition(x){const y=structuredClone(x);if(!y.shape||!Array.isArray(y.shape.vertices))throw Error('INVALID_INPUT');y.shape.vertices=canonicalPolygonVertices(y.shape.vertices);return D.define(y)}
function finitePlanarRegion(x){if(x.representationKind!=='FINITE_PLANAR_REGION')throw Error('INVALID_INPUT');return physicalPlanarDefinition(x)}function openingRegion(x){if(x.representationKind!=='OPENING_REGION')throw Error('INVALID_INPUT');openingBackRef(x);return physicalPlanarDefinition(x)}
function contactRegion(x){if(!x.supportedBodyRef||!x.geometryRef||!x.expectedContactNormal||!x.expectedContactNormal.frameRef)throw Error('INVALID_INPUT');const y=structuredClone(x);if(y.compoundChildRefs!==undefined){if(!Array.isArray(y.compoundChildRefs)||!y.compoundChildRefs.length)throw Error('INVALID_INPUT');noConflictingRefs(y.compoundChildRefs,{child:true});y.compoundChildRefs.sort(refCmp)}return seal('CONTACT_REGION_DEFINITION',y,'contactRegionId')}
function supportRelation(x){if(!x.relationId||!['REQUIRED','OPTIONAL'].includes(x.requirement)||!x.bodyRef||!x.contactRegionRef||!x.supportSurfaceRef||x.contactPolicy!=='EXACT_OPPOSED_PHYSICAL_NORMAL'||!Array.isArray(x.frameRefs))throw Error('INVALID_INPUT');const y=structuredClone(x);y.recordKind='SUPPORT_RELATION';y.digest=digest(y,'digest');return Object.freeze(y)}
function boundaryFeature(x){if(!x.localFrameRef||!Array.isArray(x.solidGeometryRefs)||!Array.isArray(x.openingRegionRefs))throw Error('INVALID_INPUT');const y=structuredClone(x);noConflictingRefs(y.solidGeometryRefs);noConflictingRefs(y.openingRegionRefs);y.solidGeometryRefs.sort(refCmp);y.openingRegionRefs.sort(refCmp);return seal('BOUNDARY_FEATURE_DEFINITION',y,'boundaryFeatureId')}
function openingBackRef(x){const r=x?.shape?.boundaryFeatureRef||x?.boundaryFeatureRef;if(!r||!r.boundaryFeatureId||!Number.isInteger(r.revision)||r.revision<1||Object.prototype.hasOwnProperty.call(r,'digest'))throw Error('INVALID_INPUT');return Object.freeze({boundaryFeatureId:r.boundaryFeatureId,revision:r.revision})}
module.exports={contactRegion,supportRelation,boundaryFeature,openingBackRef,refCmp,canonicalPolygonVertices,finitePlanarRegion,openingRegion};
