'use strict';const X=require('./fraction'),V=require('./vectors'),{resolve}=require('../numeric-frame-rotation/graph'),{materializeVector}=require('../numeric-frame-rotation/materialize'),{digest}=require('./definitions');
function tr(frames,id){const r=resolve(frames,id),t=r.translation.numerators.map((n,i)=>X.F(n,r.translation.denominator));return {t,q:r.rotationQuaternionRatio,evidence:{frameId:id,dependencies:r.dependencyRefs,snapshotDigest:r.snapshotDigest}}}
function tx(p,T){return V.add(T.t,V.rotate(p,T.q))}function box(g,frames){const T=tr(frames,g.localFrameId),h=g.shape.halfExtentsMicrounits.map(v=>X.F(v)),corners=[];for(const x of [-1n,1n])for(const y of [-1n,1n])for(const z of [-1n,1n])corners.push(tx([X.mul(h[0],X.F(x)),X.mul(h[1],X.F(y)),X.mul(h[2],X.F(z))],T));const axes=[[X.F(1),X.F(0),X.F(0)],[X.F(0),X.F(1),X.F(0)],[X.F(0),X.F(0),X.F(1)]].map(a=>V.rotate(a,T.q));return {kind:'CONVEX',id:g.geometryId,digest:g.digest,corners,axes,frameEvidence:T.evidence,materialization:corners.map(c=>materializeVector(toCommon(c)))}}
function commonDen(v){let d=1n;for(const x of v)d=d*x.d;return String(d)}
function convex(g,frames){const T=tr(frames,g.localFrameId),points=g.shape.vertices.map(p=>tx(p.map(v=>X.F(v)),T)),axes=g.shape.faceNormals.map(n=>V.rotate(n.map(v=>X.F(v)),T.q));return {kind:'CONVEX',id:g.geometryId,digest:g.digest,corners:points,axes,frameEvidence:T.evidence,materialization:points.map(c=>materializeVector(toCommon(c)))}}
function toCommon(v){let d=v.reduce((z,x)=>z*x.d,1n);return {numerators:v.map(x=>String(x.n*(d/x.d))),denominator:String(d)}}
function aabb(s){const mins=[0,1,2].map(i=>s.corners.reduce((a,p)=>X.cmp(p[i],a)<0?p[i]:a,s.corners[0][i])),maxs=[0,1,2].map(i=>s.corners.reduce((a,p)=>X.cmp(p[i],a)>0?p[i]:a,s.corners[0][i]));return {mins,maxs,digest:digest({id:s.id,mins:mins.map(X.str),maxs:maxs.map(X.str)})}}
function proj(s,a){const x=s.corners.map(p=>V.dot(p,a));return {min:x.reduce((m,v)=>X.cmp(v,m)<0?v:m),max:x.reduce((m,v)=>X.cmp(v,m)>0?v:m)}}
function broad(A,B){const a=aabb(A),b=aabb(B);for(let i=0;i<3;i++)if(X.cmp(a.maxs[i],b.mins[i])<0||X.cmp(b.maxs[i],a.mins[i])<0)return {status:'DEFINITELY_DISJOINT',aabbA:a,aabbB:b};return {status:'NARROW_PHASE_REQUIRED',aabbA:a,aabbB:b}}
function sat(A,B){const map=new Map;for(const a of [...A.axes,...B.axes])if(!V.isZero(a))map.set(V.key(a),a);for(const a of A.axes)for(const b of B.axes){const c=V.cross(a,b);if(!V.isZero(c))map.set(V.key(c),c)}const axes=[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])),ev=[];for(const [id,a] of axes){const p=proj(A,a),q=proj(B,a),sep=X.cmp(p.max,q.min)<0||X.cmp(q.max,p.min)<0,touch=X.cmp(p.max,q.min)===0||X.cmp(q.max,p.min)===0;ev.push({axisId:id,a:[X.str(p.min),X.str(p.max)],b:[X.str(q.min),X.str(q.max)],separated:sep,touching:touch});if(sep)return {status:'SEPARATED',axes:ev}}return {status:ev.some(x=>x.touching)?'TOUCHING':'PENETRATING',axes:ev}}
function materialize(g,frames){return g.representationKind==='ORIENTED_BOX'?box(g,frames):g.representationKind==='CONVEX_POLYHEDRON'?convex(g,frames):null}
module.exports={tr,tx,box,convex,aabb,broad,sat,materialize,toCommon};
