'use strict';
const X=require('./fraction'),I=require('./interval'),V=require('./vectors'),M=require('./materialized'),T=require('./topology'),S=require('./sat-interval'),{tr}=require('./geometry'),{digest}=require('./definitions');
const p=x=>I.point(x),iv=v=>M.pointIntervals(v);
function primitiveVertices(g,frames,childId){const c=S.primitiveCandidate(g,frames);if(!c)throw Error('UNSUPPORTED_GEOMETRY');return c.vertices.map(v=>Object.freeze({...v,childId:childId||v.childId}))}
function regionVertices(g,frames){return g.shape.vertices.map((q,i)=>M.vertex({vertexId:g.geometryId+':region:'+i,geometry:g,localCoordinate:q,frames}))}
function worldNormal(g,frames){const f=tr(frames,g.localFrameId);return V.rotate(g.shape.normal.map(v=>X.F(v)),f.q)}
function intervalSub2(a,b){return [I.sub(a.u,b.u),I.sub(a.v,b.v)]}function cross2(a,b){return I.sub(I.mul(a[0],b[1]),I.mul(a[1],b[0]))}function signInterval(x){if(X.cmp(x.lower,X.zero())>0)return 1;if(X.cmp(x.upper,X.zero())<0)return -1;if(X.cmp(x.lower,X.zero())===0&&X.cmp(x.upper,X.zero())===0)return 0;return null}
function result(classification,evidence){const o={classification,evidence};o.digest=digest(o);return Object.freeze(o)}
function polygonContainment(subjectVertices,region,frames){const basis=T.basis(region,frames),rv=regionVertices(region,frames).map(v=>T.project2D(v,basis)),sv=subjectVertices.map(v=>T.project2D(v,basis));if(rv.length<3)throw Error('INVALID_INPUT');let orientation=0;for(let i=0;i<rv.length;i++){const a=rv[i],b=rv[(i+1)%rv.length],c=rv[(i+2)%rv.length],s=signInterval(cross2(intervalSub2(b,a),intervalSub2(c,b)));if(s===null)return result('QUANTIZATION_AMBIGUITY',{basis,region:rv,subject:sv,why:'REGION_ORIENTATION_UNCERTAIN'});if(s!==0){if(orientation&&orientation!==s)throw Error('INVALID_INPUT');orientation=s}}if(!orientation)throw Error('INVALID_INPUT');let boundary=false;const edges=[];for(const q of sv)for(let i=0;i<rv.length;i++){const a=rv[i],b=rv[(i+1)%rv.length],z=cross2(intervalSub2(b,a),intervalSub2(q,a)),s=signInterval(z);edges.push({subject:q.vertexId,edge:i,sign:s,interval:z});if(s===null)return result('QUANTIZATION_AMBIGUITY',{basis,region:rv,subject:sv,edges});if(s===0){boundary=true;continue}if(s!==orientation)return result('DEFINITELY_OUTSIDE',{basis,region:rv,subject:sv,edges})}return result(boundary?'BOUNDARY_CONTACT':'DEFINITELY_INSIDE',{basis,region:rv,subject:sv,edges})}
function normalCompatibility(expected,region,frames){if(!expected)return result('UNSUPPORTED',{why:'EXPECTED_CONTACT_NORMAL_REQUIRED'});const actual=worldNormal(region,frames),ef=tr(frames,expected.frameId||region.localFrameId),exp=V.rotate(expected.components.map(v=>X.F(v)),ef.q),cross=V.cross(exp,actual),dot=V.dot(exp,actual);if(!V.isZero(cross)||X.cmp(dot,X.zero())>=0)return result('MISMATCH',{expected:exp.map(X.str),surface:actual.map(X.str),policy:'EXACT_OPPOSED_PHYSICAL_NORMAL'});return result('MATCH',{expected:exp.map(X.str),surface:actual.map(X.str),policy:'EXACT_OPPOSED_PHYSICAL_NORMAL'})}
function axisContainment(bodyVertices,targetCandidate){const axes=targetCandidate.kind==='OBB'?targetCandidate.axes:targetCandidate.faceNormals,ev=[];for(const a of axes){const axis=S.axisCanonical(a,{kind:'TARGET_CONTAINMENT_AXIS'}),bp=S.relation(bodyVertices,axis),tp=S.relation(targetCandidate.vertices,axis);if(bp.classification||tp.classification)return result('QUANTIZATION_AMBIGUITY',{axes:ev});const outside=X.cmp(bp.min.upper,tp.min.lower)<0||X.cmp(bp.max.lower,tp.max.upper)>0||X.cmp(bp.min.lower,tp.min.upper)<0||X.cmp(bp.max.upper,tp.max.lower)>0,definiteInside=X.cmp(bp.min.lower,tp.min.upper)>=0&&X.cmp(bp.max.upper,tp.max.lower)<=0;ev.push({axisId:axis.axisId,body:bp,target:tp,outside,definiteInside});if(outside)return result('DEFINITELY_OUTSIDE',{axes:ev});if(!definiteInside)return result('QUANTIZATION_AMBIGUITY',{axes:ev})}return result('DEFINITELY_INSIDE',{axes:ev})}
function containment(req,ctx){const body=ctx.definitions[req.bodyGeometryId],target=ctx.definitions[req.targetGeometryId];if(!body||!target)throw Error('STALE_EVIDENCE');const targetCandidate=S.primitiveCandidate(target,ctx.frames);if(!targetCandidate)throw Error('UNSUPPORTED_GEOMETRY');const children=(body.representationKind==='COMPOUND'?body.shape.children.map(c=>({id:c.childId,g:ctx.definitions[c.geometryId]})):[{id:body.geometryId,g:body}]).sort((a,b)=>a.id.localeCompare(b.id)),proofs=[];for(const c of children){if(!c.g)throw Error('STALE_EVIDENCE');const r=axisContainment(primitiveVertices(c.g,ctx.frames,c.id),targetCandidate);proofs.push({childId:c.id,geometryDigest:c.g.digest,proof:r})}const e={containment:proofs,targetGeometryDigest:target.digest,childOrderCanonical:true};if(proofs.some(x=>x.proof.classification==='DEFINITELY_OUTSIDE'))return verdict('FAIL','OUTSIDE_ALLOWED_REGION',e);if(proofs.some(x=>x.proof.classification!=='DEFINITELY_INSIDE'))return verdict('UNKNOWN','QUANTIZATION_AMBIGUITY',e);return verdict('PASS','VALID',e)}
function verdict(status,reason,evidence){const o={status,reason,evidence};o.evidenceDigest=digest(o);return Object.freeze(o)}
module.exports={polygonContainment,normalCompatibility,containment,axisContainment,primitiveVertices,regionVertices,worldNormal,verdict};
