'use strict';
const X=require('./fraction'),I=require('./interval'),V=require('./vectors'),M=require('./materialized'),T=require('./topology'),S=require('./sat-interval'),{tr}=require('./geometry'),{digest}=require('./definitions');
const p=x=>I.point(x),iv=v=>M.pointIntervals(v);
function geomVertices(g,defs,frames){if(!g)throw Error('STALE_EVIDENCE');if(g.representationKind==='COMPOUND')return g.shape.children.flatMap(c=>{const d=defs[c.geometryId];if(!d)throw Error('STALE_EVIDENCE');return primitiveVertices(d,frames,c.childId)});return primitiveVertices(g,frames,null)}
function primitiveVertices(g,frames,childId){const c=S.primitiveCandidate(g,frames);if(!c)throw Error('UNSUPPORTED_GEOMETRY');return c.vertices.map(v=>Object.freeze({...v,childId:childId||v.childId}))}
function regionVertices(g,frames){return g.shape.vertices.map((q,i)=>M.vertex({vertexId:g.geometryId+':region:'+i,geometry:g,localCoordinate:q,frames}))}
function originVertex(g,frames){return M.vertex({vertexId:g.geometryId+':origin',geometry:g,localCoordinate:['0','0','0'],frames})}
function worldNormal(g,frames){const f=tr(frames,g.localFrameId);return V.rotate(g.shape.normal.map(v=>X.F(v)),f.q)}
function planeDistance(vertex,origin,normal){return I.dot(iv(vertex).map((a,k)=>I.sub(a,iv(origin)[k])),normal.map(p))}
function distanceClass(vertices,origin,normal){const ds=vertices.map(v=>planeDistance(v,origin,normal));const minLower=ds.reduce((a,b)=>X.cmp(a,b.lower)<0?a:b.lower,ds[0].lower),minUpper=ds.reduce((a,b)=>X.cmp(a,b.upper)<0?a:b.upper,ds[0].upper);let classification;if(X.cmp(minLower,X.zero())>0)classification='FLOATING';else if(X.cmp(minUpper,X.zero())<0)classification='PENETRATING';else if(X.cmp(minLower,X.zero())===0&&X.cmp(minUpper,X.zero())===0)classification='CONTACT';else classification='QUANTIZATION_AMBIGUITY';return {classification,min:I.I(minLower,minUpper),distances:ds}}
function intervalSub2(a,b){return [I.sub(a.u,b.u),I.sub(a.v,b.v)]}function cross2(a,b){return I.sub(I.mul(a[0],b[1]),I.mul(a[1],b[0]))}function signInterval(x){if(X.cmp(x.lower,X.zero())>0)return 1;if(X.cmp(x.upper,X.zero())<0)return -1;if(X.cmp(x.lower,X.zero())===0&&X.cmp(x.upper,X.zero())===0)return 0;return null}
function polygonContainment(subjectVertices,region,frames){const basis=T.basis(region,frames),rv=regionVertices(region,frames).map(v=>T.project2D(v,basis)),sv=subjectVertices.map(v=>T.project2D(v,basis));if(rv.length<3)throw Error('INVALID_INPUT');let orientation=0;for(let i=0;i<rv.length;i++){const a=rv[i],b=rv[(i+1)%rv.length],c=rv[(i+2)%rv.length],s=signInterval(cross2(intervalSub2(b,a),intervalSub2(c,b)));if(s===null)return result('QUANTIZATION_AMBIGUITY',{basis,region:rv,subject:sv,why:'REGION_ORIENTATION_UNCERTAIN'});if(s!==0){if(orientation&&orientation!==s)throw Error('INVALID_INPUT');orientation=s}}if(!orientation)throw Error('INVALID_INPUT');let boundary=false;const edges=[];for(const q of sv)for(let i=0;i<rv.length;i++){const a=rv[i],b=rv[(i+1)%rv.length],z=cross2(intervalSub2(b,a),intervalSub2(q,a)),s=signInterval(z);edges.push({subject:q.vertexId,edge:i,sign:s,interval:z});if(s===null)return result('QUANTIZATION_AMBIGUITY',{basis,region:rv,subject:sv,edges});if(s===0){boundary=true;continue}if(s!==orientation)return result('DEFINITELY_OUTSIDE',{basis,region:rv,subject:sv,edges})}return result(boundary?'BOUNDARY_CONTACT':'DEFINITELY_INSIDE',{basis,region:rv,subject:sv,edges})}
function result(classification,evidence){const o={classification,evidence};o.digest=digest(o);return Object.freeze(o)}
function normalCompatibility(expected,region,frames){if(!expected)return result('UNSUPPORTED',{why:'EXPECTED_CONTACT_NORMAL_REQUIRED'});const actual=worldNormal(region,frames),ef=tr(frames,expected.frameId||region.localFrameId),exp=V.rotate(expected.components.map(v=>X.F(v)),ef.q),cross=V.cross(exp,actual),dot=V.dot(exp,actual);if(!V.isZero(cross)||X.cmp(dot,X.zero())>=0)return result('MISMATCH',{expected:exp.map(X.str),surface:actual.map(X.str),policy:'EXACT_OPPOSED_PHYSICAL_NORMAL'});return result('MATCH',{expected:exp.map(X.str),surface:actual.map(X.str),policy:'EXACT_OPPOSED_PHYSICAL_NORMAL'})}
function support(req,ctx){const body=ctx.definitions[req.contactRegionGeometryId||req.bodyGeometryId],surface=ctx.definitions[req.targetGeometryId];if(!body||!surface)throw Error('STALE_EVIDENCE');if(surface.representationKind!=='FINITE_PLANAR_REGION'||surface.shape.sidedness!=='FRONT_ONLY')throw Error('UNSUPPORTED_GEOMETRY');const vs=geomVertices(body,ctx.definitions,ctx.frames),origin=originVertex(surface,ctx.frames),normal=worldNormal(surface,ctx.frames),d=distanceClass(vs,origin,normal),poly=polygonContainment(vs,surface,ctx.frames),nc=normalCompatibility(req.expectedContactNormal,surface,ctx.frames),e={relationId:req.relationId||null,bodyGeometryDigest:body.digest,surfaceGeometryDigest:surface.digest,materializationEvidenceDigests:vs.map(v=>v.evidenceDigest).sort(),contactDistance:d,polygon:poly,normal:nc,wholeContactRegionRequired:true};if(d.classification==='PENETRATING')return verdict('FAIL','CONTACT_PENETRATION',e);if(d.classification==='FLOATING')return verdict('FAIL','CONTACT_FLOATING',e);if(poly.classification==='DEFINITELY_OUTSIDE')return verdict('FAIL','CONTACT_OUTSIDE_REGION',e);if(nc.classification==='MISMATCH')return verdict('FAIL','NORMAL_MISMATCH',e);if(nc.classification==='UNSUPPORTED')return verdict('UNKNOWN','UNSUPPORTED_GEOMETRY',e);if(d.classification==='QUANTIZATION_AMBIGUITY'||poly.classification==='QUANTIZATION_AMBIGUITY'||poly.classification==='BOUNDARY_CONTACT')return verdict('UNKNOWN','QUANTIZATION_AMBIGUITY',e);return verdict('PASS','VALID',e)}
function axisContainment(bodyVertices,targetCandidate){const axes=targetCandidate.kind==='OBB'?targetCandidate.axes:targetCandidate.faceNormals,ev=[];for(const a of axes){const axis=S.axisCanonical(a,{kind:'TARGET_CONTAINMENT_AXIS'}),bp=S.relation(bodyVertices,axis),tp=S.relation(targetCandidate.vertices,axis);if(bp.classification||tp.classification)return result('QUANTIZATION_AMBIGUITY',{axes:ev});const outside=X.cmp(bp.min.upper,tp.min.lower)<0||X.cmp(bp.max.lower,tp.max.upper)>0||X.cmp(bp.min.lower,tp.min.upper)<0||X.cmp(bp.max.upper,tp.max.lower)>0,definiteInside=X.cmp(bp.min.lower,tp.min.upper)>=0&&X.cmp(bp.max.upper,tp.max.lower)<=0;ev.push({axisId:axis.axisId,body:bp,target:tp,outside,definiteInside});if(outside)return result('DEFINITELY_OUTSIDE',{axes:ev});if(!definiteInside)return result('QUANTIZATION_AMBIGUITY',{axes:ev})}return result('DEFINITELY_INSIDE',{axes:ev})}
function containment(req,ctx){const body=ctx.definitions[req.bodyGeometryId],target=ctx.definitions[req.targetGeometryId];if(!body||!target)throw Error('STALE_EVIDENCE');const targetCandidate=S.primitiveCandidate(target,ctx.frames);if(!targetCandidate)throw Error('UNSUPPORTED_GEOMETRY');const children=body.representationKind==='COMPOUND'?body.shape.children.map(c=>({id:c.childId,g:ctx.definitions[c.geometryId]})):[{id:body.geometryId,g:body}],proofs=[];for(const c of children){if(!c.g)throw Error('STALE_EVIDENCE');const r=axisContainment(primitiveVertices(c.g,ctx.frames,c.id),targetCandidate);proofs.push({childId:c.id,geometryDigest:c.g.digest,proof:r});if(r.classification==='DEFINITELY_OUTSIDE')return verdict('FAIL','OUTSIDE_ALLOWED_REGION',{containment:proofs,targetGeometryDigest:target.digest});if(r.classification!=='DEFINITELY_INSIDE')return verdict('UNKNOWN','QUANTIZATION_AMBIGUITY',{containment:proofs,targetGeometryDigest:target.digest})}return verdict('PASS','VALID',{containment:proofs,targetGeometryDigest:target.digest})}
function opening(req,ctx){const body=ctx.definitions[req.bodyGeometryId],o=ctx.definitions[req.targetGeometryId];if(!body||!o)throw Error('STALE_EVIDENCE');if(o.representationKind!=='OPENING_REGION'||!o.shape.boundaryFeatureRef||!Array.isArray(o.shape.axes)||o.shape.axes.length<2)throw Error('UNSUPPORTED_GEOMETRY');const vs=geomVertices(body,ctx.definitions,ctx.frames),f=tr(ctx.frames,o.localFrameId),ov=regionVertices(o,ctx.frames),axes=o.shape.axes.map(a=>V.rotate(a.map(v=>X.F(v)),f.q)),proofs=[];for(const a of axes){const axis=S.axisCanonical(a,{kind:'OPENING_LOCAL_AXIS',boundaryFeatureRef:o.shape.boundaryFeatureRef}),bp=S.relation(vs,axis),op=S.relation(ov,axis);if(bp.classification||op.classification)return verdict('UNKNOWN','QUANTIZATION_AMBIGUITY',{openingAxisProofs:proofs});const outside=X.cmp(bp.min.upper,op.min.lower)<0||X.cmp(bp.max.lower,op.max.upper)>0||X.cmp(bp.min.lower,op.min.upper)<0||X.cmp(bp.max.upper,op.max.lower)>0,strict=X.cmp(bp.min.lower,op.min.upper)>0&&X.cmp(bp.max.upper,op.max.lower)<0;proofs.push({axisId:axis.axisId,body:bp,opening:op,outside,strict});if(outside)return verdict('FAIL','BOUNDARY_PENETRATION',{openingAxisProofs:proofs,boundaryFeatureRef:o.shape.boundaryFeatureRef});if(!strict)return verdict('UNKNOWN','QUANTIZATION_AMBIGUITY',{openingAxisProofs:proofs,boundaryFeatureRef:o.shape.boundaryFeatureRef})}return verdict('PASS','VALID',{openingAxisProofs:proofs,boundaryFeatureRef:o.shape.boundaryFeatureRef,explicitOpeningRequired:true})}
function verdict(status,reason,evidence){const o={status,reason,evidence};o.evidenceDigest=digest(o);return Object.freeze(o)}
module.exports={polygonContainment,normalCompatibility,support,containment,opening,axisContainment};
