'use strict';const X=require('./fraction'),I=require('./interval'),V=require('./vectors'),{materializeVector}=require('../numeric-frame-rotation/materialize'),{tr,tx,toCommon}=require('./geometry'),{digest}=require('./definitions');
function scalarFromEvidence(source,fixed,error){const f=X.F(fixed,1000000n),e=X.abs(X.F(error.numerators[0],error.denominator)),interval=I.I(X.sub(f,e),X.add(f,e));return Object.freeze({valueClass:'MATERIALIZED_WITH_INTERVAL',exactSource:Object.freeze({numerator:String(source.n),denominator:String(source.d)}),fixedMicrounits:String(fixed),error:Object.freeze({numerator:String(e.n),denominator:String(e.d)}),interval})}
function intervalVector3(exact,policy={id:'numeric-frame-materialize-v1',scale:1000000n}){const ev=materializeVector(toCommon(exact),{scale:policy.scale}),components=exact.map((x,k)=>scalarFromEvidence(x,ev.fixedMicrounits[k],ev.errors[k]));const out={valueClass:'MATERIALIZED_WITH_INTERVAL',components,materializationPolicyId:policy.id,materializationEvidence:ev};out.digest=digest(out);return Object.freeze(out)}
function vertex({vertexId,geometry,childId=null,localCoordinate,frames,ownerRef='synthetic'}){const T=tr(frames,geometry.localFrameId),local=localCoordinate.map(v=>X.F(v)),exact=tx(local,T),iv=intervalVector3(exact),out={vertexId,geometryId:geometry.geometryId,geometryRevision:geometry.revision,geometryDigest:geometry.digest,childId,ownerRef,sourceLocalCoordinate:local.map(X.str),exactWorldCoordinate:exact.map(x=>({numerator:String(x.n),denominator:String(x.d)})),intervalVector:iv,frameEvidence:T.evidence,valueClass:'MATERIALIZED_WITH_INTERVAL'};out.evidenceDigest=digest(out);return Object.freeze(out)}
function pointIntervals(v){return v.intervalVector.components.map(c=>c.interval)}
function exactDirection({directionId,localDirection,frameEvidence,sourceKind,sourceRefs}){const out={directionId,valueClass:'EXACT_RATIONAL',homogeneousComponents:localDirection.map(X.str),frameEvidence,sourceKind,sourceRefs};out.digest=digest(out);return Object.freeze(out)}
function derivedDirection({directionId,a,b,sourceKind}){const av=a.map(x=>I.point(x)),bv=b.map(x=>I.point(x)),c=[I.sub(I.mul(av[1],bv[2]),I.mul(av[2],bv[1])),I.sub(I.mul(av[2],bv[0]),I.mul(av[0],bv[2])),I.sub(I.mul(av[0],bv[1]),I.mul(av[1],bv[0]))],out={directionId,valueClass:'DERIVED_INTERVAL',components:c,sourceKind,sourceDigests:[a.digest,b.digest].filter(Boolean)};out.digest=digest(out);return Object.freeze(out)}
function broadAabb(vertices,source){const ps=vertices.map(pointIntervals),bounds=[0,1,2].map(k=>I.I(ps.reduce((a,p)=>X.cmp(p[k].lower,a)<0?p[k].lower:a,ps[0][k].lower),ps.reduce((a,p)=>X.cmp(p[k].upper,a)>0?p[k].upper:a,ps[0][k].upper))),out={kind:'ERROR_EXPANDED_AABB',valueClass:'DERIVED_INTERVAL',bounds,sourceGeometryDigest:source.geometryDigest,materializedVertexEvidenceDigests:vertices.map(v=>v.evidenceDigest).sort(),frameDependencyDigest:digest(vertices.flatMap(v=>v.frameEvidence.dependencies).sort((a,b)=>a.frameId.localeCompare(b.frameId))),intervalPolicyVersion:'1.0.0',accelerationOnly:true};out.digest=digest(out);return Object.freeze(out)}
function validateBroad(aabb,vertices){const canonical=broadAabb(vertices,{geometryDigest:aabb.sourceGeometryDigest});if(canonical.digest!==aabb.digest)throw Error('INCONSISTENT_BROAD_EVIDENCE');return true}
function stale(element,frames){const by=new Map(frames.map(f=>[f.frameId,f]));return element.frameEvidence.dependencies.some(r=>{const f=by.get(r.frameId);return !f||f.revision!==r.revision||f.digest!==r.digest})}
module.exports={scalarFromEvidence,intervalVector3,vertex,pointIntervals,exactDirection,derivedDirection,broadAabb,validateBroad,stale};
