'use strict';
// Hypothetical continuous sweep conservative enclosure, not sampled angles or door command.
const {digest,deepFreeze}=require('../../contracts/canonical'),C=require('../door-world-genesis/candidate'),S=require('../door-world-structure/candidate'),N=require('../closed-world-navigation-preparation/candidate'),{projectKnownBodyBounds}=require('../door-legality-adapter');
const axes=['X','Y','Z'],keys=axes.flatMap(k=>['min'+k,'max'+k]),contact=(a,b)=>axes.every(k=>a['min'+k]<=b['max'+k]&&b['min'+k]<=a['max'+k]);
function inspectHypotheticalSweep({packet,surfaceModel,committedWorld,cameraRoute,...extra}={}){const out=(status,reason,detail={})=>deepFreeze({status,reason,classification:'HYPOTHETICAL_DOOR_SWEEP_PREPARATION_NOT_ADMITTED_NOT_ACTIVATED',operationalStatus:'UNKNOWN',...detail});try{if(Object.keys(extra).length)return out('UNKNOWN','CALLER_STATE_OR_EXTRA_INPUT');const g=C.prepareGenesis(packet);if(digest(surfaceModel)!==digest(g.surfaceModel)||digest(committedWorld)!==digest(g.genesis)||S.validateStructure(surfaceModel).status!=='DOORWAY_FLOOR_STATIC_TOPOLOGY_VALIDATED_NOT_ADMITTED')return out('UNKNOWN','EXACT_EMPTY_CLOSED_WORLD_MODEL_REQUIRED');if(!cameraRoute||Object.keys(cameraRoute).sort().join(',')!=='from,to'||![cameraRoute.from,cameraRoute.to].every(p=>Array.isArray(p)&&p.length===3&&p.every(Number.isSafeInteger)))return out('UNKNOWN','EXPLICIT_CONCURRENT_CAMERA_ROUTE_REQUIRED');
 const d=surfaceModel.doorDefinition,p=d.pivot,c=d.closedLeaf;const farX=Math.max(Math.abs(c.minX-p.xMicrounits),Math.abs(c.maxX-p.xMicrounits)),farZ=Math.max(Math.abs(c.minZ-p.zMicrounits),Math.abs(c.maxZ-p.zMicrounits));if(![farX,farZ].every(Number.isSafeInteger))return out('UNKNOWN','PIVOT_LEAF_NOT_INTEGER');const sq=BigInt(farX)**2n+BigInt(farZ)**2n;let lo=0n,hi=BigInt(farX+farZ);while(lo<hi){const mid=(lo+hi)/2n;if(mid*mid>=sq)hi=mid;else lo=mid+1n}const r=Number(lo),swept={minX:p.xMicrounits-r,maxX:p.xMicrounits+r,minY:c.minY,maxY:c.maxY,minZ:p.zMicrounits-r,maxZ:p.zMicrounits+r};if(!Object.values(swept).every(Number.isSafeInteger))return out('UNKNOWN','SWEEP_OVERFLOW');
 const nav=N.inspectClosedPath({packet,surfaceModel,committedWorld,from:[0,1600000,1000000],to:[0,1600000,1000000]});if(nav.status!=='CLOSED_PATH_CLEAR_PREPARATION_ONLY_NOT_ADMITTED')return out('UNKNOWN','CAMERA_ENVELOPE_UNAVAILABLE');const cr=nav.radiusMicrounits,cb=Object.fromEntries(keys.map(k=>[k,(k.startsWith('min')?Math.min:Math.max)(cameraRoute.from[axes.indexOf(k.slice(-1))],cameraRoute.to[axes.indexOf(k.slice(-1))])+(k.startsWith('min')?-cr:cr)]));if(!Object.values(cb).every(Number.isSafeInteger))return out('UNKNOWN','CAMERA_SWEEP_OVERFLOW');
 const statics=surfaceModel.surfaces.filter(s=>['WALL','OBSTACLE'].includes(s.type)).flatMap(s=>s.region.volumes.map(v=>({id:s.surfaceId+':'+v.volumeId,b:Object.fromEntries(keys.map(k=>[k,Math.round(v[k]*1e6)]))}))),hits=statics.filter(s=>contact(swept,s.b)).map(s=>s.id),bodyChecks=[];for(const e of Object.values(committedWorld.entities)){const b=projectKnownBodyBounds(e),ep=e.transform?.positionMicrounits;if(!b||!Array.isArray(ep)||ep.length!==3||!ep.every(Number.isSafeInteger)||digest(e.transform.orientation)!==digest([0,0,0,1]))return out('UNKNOWN','BODY_UNSUPPORTED');const wb=Object.fromEntries(keys.map(k=>[k,b[k]+ep[axes.indexOf(k.slice(-1))]]));bodyChecks.push({entityId:e.entityId,sweepContact:contact(swept,wb),openLeafContact:contact(d.openLeaf,wb)})}
 return out('UNKNOWN','CONSERVATIVE_SWEEP_CONTACT_IS_NOT_EXACT_COLLISION_OR_ACTIVATION_PROOF',{modelDigest:surfaceModel.surfaceModelDigest,worldDigest:committedWorld.stateDigest,pivot:p,leafDefinitionDigest:digest(d),radiusMicrounits:r,sweptBoundsMicrounits:swept,enclosureRule:'FULL_ROTATION_RADIAL_SQUARE_SUPERSET_CONTAINS_ALL_CONTINUOUS_0_TO_90_DEGREE_LEAF_POSES_NO_SAMPLES',staticContactCandidates:hits,concurrentCameraContactCandidate:contact(swept,cb),concurrentCameraOpenLeafContact:contact(d.openLeaf,cb),bodyChecks,limitations:['CONSERVATIVE_FULL_DISK_BOX_OVERREJECTS_FRAME_WALL_AND_LOCKER','CONTACT_CANDIDATE_NOT_PROVEN_ACTUAL_SWING_COLLISION','EMPTY_WORLD_BODY_CHECKS_VACUOUS_NO_POPULATED_WORLD_PROOF','NO_EXACT_SECTOR_OR_DYNAMIC_CLEARANCE_PROOF','NO_SETDOORSTATE_EVENT_COMMIT_RENDER_OR_ACTIVATION','ENDPOINT_CLEARANCE_ALONE_INSUFFICIENT']});
 }catch{return out('UNKNOWN','HYPOTHETICAL_SWEEP_INPUT_INVALID')}}
module.exports={inspectHypotheticalSweep};
