'use strict';const {digest}=require('../../src/verified-architecture-phase2/canonical'),{buildSurfaceModel}=require('../../src/verified-architecture-phase2/surface-model'),V=require('../../src/verified-architecture-phase2/geometry-gate-v2');
function model(){return buildSurfaceModel({sceneId:'synthetic-v2',surfaceModelId:'synthetic-v2-surfaces',revision:1,sourceEvidence:{classification:'SYNTHETIC_TEST'},surfaces:[
{surfaceId:'floor',type:'FLOOR',region:{allowed:[{regionId:'floor-r',minX:-5,maxX:5,minY:0,maxY:0,minZ:-5,maxZ:5}],volumes:[]},planeOrDepth:{kind:'PLANE',planeY:0},contactPlane:{axis:'Y',coordinate:0,normalSign:1},contactCapabilities:[{capabilityId:'floor-support',kind:'SUPPORT_CONTACT'}],contactRules:[],confidence:'SYNTHETIC',provenance:{classification:'SYNTHETIC_TEST'}},
{surfaceId:'platform',type:'SUPPORT_SURFACE',region:{allowed:[{regionId:'platform-r',minX:.1,maxX:.5,minY:.5,maxY:.5,minZ:-.5,maxZ:.5}],volumes:[]},planeOrDepth:{kind:'PLANE',planeY:.5},contactPlane:{axis:'Y',coordinate:.5,normalSign:1},contactCapabilities:[{capabilityId:'platform-support',kind:'SUPPORT_CONTACT'}],contactRules:[],confidence:'SYNTHETIC',provenance:{classification:'SYNTHETIC_TEST'}},
{surfaceId:'wall',type:'WALL',region:{allowed:[{regionId:'wall-r',minX:-1,maxX:1,minY:0,maxY:2,minZ:.5,maxZ:.5}],volumes:[{volumeId:'wall-v',minX:-1,maxX:1,minY:0,maxY:2,minZ:.5,maxZ:.7}]},planeOrDepth:{kind:'BOX_DEPTH'},contactPlane:{axis:'Z',coordinate:.5,normalSign:-1},contactCapabilities:[{capabilityId:'wall-support',kind:'SUPPORT_CONTACT'}],contactRules:[],confidence:'SYNTHETIC',provenance:{classification:'SYNTHETIC_TEST'}},
{surfaceId:'wall-no-support',type:'WALL',region:{allowed:[{regionId:'wn-r',minX:-1,maxX:1,minY:0,maxY:2,minZ:-.5,maxZ:-.5}],volumes:[{volumeId:'wn-v',minX:-1,maxX:1,minY:0,maxY:2,minZ:-.7,maxZ:-.5}]},planeOrDepth:{kind:'BOX_DEPTH'},contactPlane:{axis:'Z',coordinate:-.5,normalSign:1},contactCapabilities:[],contactRules:[],confidence:'SYNTHETIC',provenance:{classification:'SYNTHETIC_TEST'}},
{surfaceId:'door',type:'DOOR_OR_OPENING',region:{allowed:[],volumes:[{volumeId:'door-v',minX:2,maxX:3,minY:0,maxY:2,minZ:-1,maxZ:1}]},planeOrDepth:{kind:'BOX_DEPTH'},contactRules:[],confidence:'SYNTHETIC',provenance:{}},
{surfaceId:'obstacle',type:'OBSTACLE',region:{allowed:[],volumes:[{volumeId:'obs-v',minX:-3,maxX:-2,minY:0,maxY:2,minZ:-1,maxZ:1}]},planeOrDepth:{kind:'BOX_DEPTH'},contactRules:[],confidence:'SYNTHETIC',provenance:{}}
]})}
function body(){const geometry={minX:-.5,maxX:.5,minY:0,maxY:1,minZ:-.5,maxZ:.5},contactRegions=[['floor-contact',{minX:-.5,maxX:.1,minY:0,maxY:0,minZ:-.5,maxZ:.5}],['elevated-contact',{minX:.1,maxX:.5,minY:.5,maxY:.5,minZ:-.5,maxZ:.5}],['wall-contact',{minX:-.5,maxX:.5,minY:.2,maxY:.9,minZ:.5,maxZ:.5}],['third-contact',{minX:-.4,maxX:-.2,minY:0,maxY:0,minZ:-.4,maxZ:.4}]].map(([contactRegionId,geometry])=>({contactRegionId,geometry}));const b={id:'synthetic/body-v2',revision:1,digest:'b'.repeat(64),geometry,geometryDigest:digest(geometry),proofGeometryDigest:digest(geometry),contactRegions,evidenceRefs:['synthetic-body']};return b}
function contact(id,regionId,surfaceId,type,capabilityId,normal){const b=body(),m=model(),r=b.contactRegions.find(x=>x.contactRegionId===regionId);return {relationId:id,requirement:'REQUIRED',contactRole:'GENERIC',supportedBodyRef:{id:b.id,revision:b.revision,digest:b.digest},contactRegionRef:{bodyId:b.id,bodyRevision:b.revision,bodyDigest:b.digest,contactRegionId:regionId},contactRegionGeometry:r.geometry,contactRegionDigest:digest(r),surfaceModelRef:{id:m.surfaceModelId,revision:m.revision,digest:m.surfaceModelDigest},surfaceId,expectedSurfaceType:type,capabilityId,contactNormal:normal,evidenceRefs:['synthetic-contact:'+id]}}
function req(contacts,transform={x:0,y:0,z:0}){contacts=contacts===undefined?[contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0})]:contacts;const m=model(),x={version:'2.0.0',requestId:'v2-request',requiresContacts:true,body:body(),surfaceModelRef:{id:m.surfaceModelId,revision:m.revision,digest:m.surfaceModelDigest},transform,contacts};x.requestDigest=V.requestDigest(x);return x}
module.exports={model,body,contact,req};
