'use strict';const test=require('node:test'),assert=require('node:assert/strict'),V=require('../../src/verified-architecture-phase2/geometry-gate-v2'),V1=require('../../src/verified-architecture-phase2/geometry-gate'),{digest}=require('../../src/verified-architecture-phase2/canonical'),H=require('./helpers');
const ev=(r,m=H.model())=>V.evaluateV2(r,m),refresh=r=>{r.requestDigest=V.requestDigest(r);return r};
test('single required floor contact passes with global and per-relation evidence',()=>{const x=ev(H.req());assert.equal(x.result,'PASS');assert.equal(x.evidence.global.fullBodyCollisionEvaluated,true);assert.equal(x.evidence.contacts.length,1);assert(V.verifyV2Result(x))});
test('floor plus elevated support at different height passes',()=>{const cs=[H.contact('floor','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),H.contact('legs','elevated-contact','platform','SUPPORT_SURFACE','platform-support',{x:0,y:1,z:0})],x=ev(H.req(cs));assert.equal(x.result,'PASS');assert.deepEqual(x.evidence.canonicalRelationIds,['floor','legs'])});
test('floor plus support-capable WALL passes without relabeling wall',()=>{const cs=[H.contact('floor','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),H.contact('wall','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1})],x=ev(H.req(cs));assert.equal(x.result,'PASS');assert.equal(x.evidence.contacts[1].surfaceRef.type,'WALL')});
test('three independent contacts pass with independent evidence',()=>{const cs=[H.contact('z-wall','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1}),H.contact('a-floor','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),H.contact('m-third','third-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0})],x=ev(H.req(cs));assert.equal(x.result,'PASS');assert.deepEqual(x.evidence.canonicalRelationIds,['a-floor','m-third','z-wall'])});
test('contact insertion order changes neither request identity nor result evidence',()=>{const a=H.contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),b=H.contact('b','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1}),x=H.req([a,b]),y=H.req([b,a]);assert.equal(x.requestDigest,y.requestDigest);const ex=ev(x),ey=ev(y);assert.equal(ex.result,ey.result);assert.deepEqual(ex.evidence.contacts,ey.evidence.contacts)});
for(const [name,mut,code] of [
['V1 sent to V2',r=>{delete r.version},'V2_SCHEMA_OR_VERSION'],['malformed',r=>{delete r.requestId},'V2_SCHEMA_OR_VERSION'],['missing body geometry',r=>{delete r.body.geometry},'V2_BODY_IDENTITY_OR_EVIDENCE'],['wrong body geometry digest',r=>{r.body.geometryDigest='f'.repeat(64)},'V2_BODY_IDENTITY_OR_EVIDENCE'],['stale body contact ref',r=>{r.contacts[0].supportedBodyRef.revision=2},'V2_CONTACT_IDENTITY_INVALID'],['missing contact region',r=>{r.contacts[0].contactRegionRef.contactRegionId='missing'},'V2_CONTACT_REGION_MISSING_OR_STALE'],['wrong region digest',r=>{r.contacts[0].contactRegionDigest='f'.repeat(64)},'V2_CONTACT_REGION_DIGEST_MISMATCH'],['duplicate relation id',r=>{r.contacts.push(structuredClone(r.contacts[0]))},'V2_DUPLICATE_RELATION_ID'],['zero required contacts',r=>{r.contacts=[]},'V2_REQUIRED_CONTACT_MISSING'],['stale SurfaceModel ref',r=>{r.surfaceModelRef.revision=2},'V2_SURFACE_MODEL_STALE_OR_MISSING'],['stale contact SurfaceModel',r=>{r.contacts[0].surfaceModelRef.revision=2},'V2_CONTACT_SURFACE_MODEL_STALE'],['missing surface',r=>{r.contacts[0].surfaceId='missing'},'V2_CONTACT_SURFACE_MISSING'],['wrong semantic type',r=>{r.contacts[0].expectedSurfaceType='WALL'},'V2_CONTACT_SURFACE_TYPE_MISMATCH'],['unsupported wall capability',r=>{r.contacts[0]=H.contact('a','wall-contact','wall-no-support','WALL','wall-support',{x:0,y:0,z:1})},'V2_SUPPORT_CAPABILITY_MISSING'],['wrong normal',r=>{r.contacts[0].contactNormal={x:1,y:0,z:0}},'V2_CONTACT_NORMAL_MISMATCH'],['floating contact',r=>{r.transform.y=.1},'V2_CONTACT_FLOATING'],['excessive penetration',r=>{r.transform.y=-.1},'V2_CONTACT_EXCESSIVE_PENETRATION'],['contact outside support region',r=>{r.contacts=[H.contact('a','elevated-contact','platform','SUPPORT_SURFACE','platform-support',{x:0,y:1,z:0})];r.transform.x=.6},'V2_CONTACT_OUTSIDE_SURFACE_REGION']
])test(name+' fails deterministically',()=>{const r=H.req();mut(r);if(r.version==='2.0.0'&&r.requestId)refresh(r);assert.equal(ev(r).reasonCode,code)});
test('V2 sent to V1 cannot be interpreted as V1 PASS',()=>{assert.notEqual(V1.evaluate(H.req(),H.model()).result,'PASS')});
for(const [name,t,code] of [['illegal wall penetration',{x:0,y:0,z:.1},'V2_GLOBAL_WALL_PENETRATION'],['door penetration',{x:2.4,y:0,z:0},'V2_GLOBAL_DOOR_PENETRATION'],['obstacle penetration',{x:-2.4,y:0,z:0},'V2_GLOBAL_OBSTACLE_PENETRATION']])test('legal contact cannot hide '+name,()=>{assert.equal(ev(refresh({...H.req([],t),requiresContacts:false})).reasonCode,code)});
test('one valid plus one invalid contact fails whole request and preserves completed evidence',()=>{const cs=[H.contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),H.contact('b','elevated-contact','platform','SUPPORT_SURFACE','missing',{x:0,y:1,z:0})],x=ev(H.req(cs));assert.equal(x.result,'FAIL');assert.equal(x.reasonCode,'V2_SUPPORT_CAPABILITY_MISSING');assert.equal(x.evidence.completed.length,1)});
test('three contacts middle invalid fails by canonical relation order',()=>{const cs=[H.contact('z','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1}),H.contact('m','elevated-contact','platform','SUPPORT_SURFACE','missing',{x:0,y:1,z:0}),H.contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0})],x=ev(H.req(cs));assert.equal(x.evidence.relationId,'m');assert.equal(x.evidence.completed[0].relationId,'a')});
test('tampered result evidence does not verify',()=>{const x=structuredClone(ev(H.req()));x.evidence.contacts[0].result='FAIL';assert.equal(V.verifyV2Result(x),false)});
test('geometry mutation after proof rejects',()=>{const r=H.req();r.body.geometry.maxX=.6;refresh(r);assert.equal(ev(r).reasonCode,'V2_BODY_IDENTITY_OR_EVIDENCE')});
test('floor FAIL plus chair PASS rejects whole request',()=>{const a=H.contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),b=H.contact('b','elevated-contact','platform','SUPPORT_SURFACE','platform-support',{x:0,y:1,z:0});a.contactNormal={x:1,y:0,z:0};const r=H.req([a,b]);r.requestDigest=V.requestDigest(r);const x=ev(r);assert.equal(x.result,'FAIL');assert.equal(x.evidence.relationId,'a')});
test('floor PASS plus wall UNKNOWN capability rejects whole request',()=>{const cs=[H.contact('a','floor-contact','floor','FLOOR','floor-support',{x:0,y:1,z:0}),H.contact('b','wall-contact','wall-no-support','WALL','wall-support',{x:0,y:0,z:1})],x=ev(H.req(cs));assert.equal(x.result,'FAIL');assert.equal(x.reasonCode,'V2_SUPPORT_CAPABILITY_MISSING');assert.equal(x.evidence.completed.length,1)});
test('wall gap and penetration have exact deterministic reasons',()=>{for(const [z,code] of [[-.1,'V2_GLOBAL_WALL_PENETRATION'],[.1,'V2_CONTACT_EXCESSIVE_PENETRATION']]){const c=H.contact('a','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1}),r=H.req([c],{x:0,y:0,z});r.body.geometry.maxZ=.5-z;r.body.geometryDigest=digest(r.body.geometry);r.body.proofGeometryDigest=r.body.geometryDigest;r.requestDigest=V.requestDigest(r);assert.equal(ev(r).reasonCode,code)}});
test('stale wall surface-model ref and wrong wall region fail',()=>{const c=H.contact('a','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1});c.surfaceModelRef.digest='f'.repeat(64);let r=H.req([c]);assert.equal(ev(r).reasonCode,'V2_CONTACT_SURFACE_MODEL_STALE');const d=H.contact('a','wall-contact','wall','WALL','wall-support',{x:0,y:0,z:-1});d.contactRegionGeometry={...d.contactRegionGeometry,minX:-2};r=H.req([d]);assert.equal(ev(r).reasonCode,'V2_CONTACT_REGION_DIGEST_MISMATCH')});
