'use strict';const {digest,canonicalBytes}=require('../../contracts/canonical'),{PACKAGE,model}=require('./package'),D=require('../definitions/adult-v1-male-supine-floor'),SYN=require('../definitions/synthetic-training-unit-v1'),C=require('../definitions/treatment-chair'),{SCHOOL_BAG_BODY}=require('../school-physical-contract'),{validateRelations,buildIndex}=require('../../multi-support/relations');
const fail=(code)=>({status:'REJECTED',code});function validateScenePackage(p){if(!p||(p.scenePackageVersion!=='2.0.0'&&p.scenePackageVersion!=='2.1.0')||p.scenePackageId!=='SCHOOL_TREATMENT_ROOM_PHYSICAL_V2')return fail('MALFORMED_OR_WRONG_VERSION');const isV21=p.scenePackageVersion==='2.1.0',entityCount=isV21?4:3;if(digest({...p,scenePackageDigest:undefined},'scenePackageDigest')!==p.scenePackageDigest)return fail('PACKAGE_DIGEST_MISMATCH');if(p.refs?.surfaceModel?.id!==model.surfaceModelId||p.refs.surfaceModel.revision!==model.revision||p.refs.surfaceModel.digest!==model.surfaceModelDigest)return fail('SURFACE_MODEL_MISMATCH');for(const s of model.surfaces)if(!p.refs.requiredSurfaces.some(x=>x.id===s.surfaceId&&x.type===s.type))return fail('REQUIRED_SURFACE_MISSING');const ids=p.entities?.map(x=>x.entityId)||[];if(ids.length!==entityCount||new Set(ids).size!==ids.length||p.requiredEntityIds?.length!==entityCount||p.requiredEntityIds.some(id=>!ids.includes(id)))return fail('ENTITY_MISSING_OR_DUPLICATE');const by=Object.fromEntries(p.entities.map(x=>[x.entityId,x])),cas=by['school-casualty-adult-v1'],chair=by['school-treatment-chair'],bag=by['school-medical-bag'];if(!cas||cas.physicalBodyRef.recordId!==D.BODY.bodyDefinitionId||cas.physicalBodyRef.revision!==D.BODY.bodyRevision||cas.physicalBodyRef.digest!==D.BODY.canonicalDigest||cas.physicalState.profileRef.digest!==D.PROFILE.profileDigest||cas.physicalState.profileRef.subjectSex!=='MALE'||cas.physicalState.postureRef.digest!==D.POSTURE.canonicalDigest||cas.physicalState.postureRef.semanticType!=='SUPINE_FLOOR')return fail('CASUALTY_REF_MISMATCH');if(!chair||chair.physicalBodyRef.recordId!==C.BODY.bodyDefinitionId||chair.physicalBodyRef.revision!==C.BODY.bodyRevision||chair.physicalBodyRef.digest!==C.BODY.canonicalDigest||chair.physicalState.supportSurface?.surfaceRevision!==C.SURFACE.surfaceRevision||chair.physicalState.supportSurface?.canonicalDigest!==C.SURFACE.canonicalDigest||p.refs.bodies.seat.owner.id!==C.ENTITY.entityDefinitionId||p.refs.bodies.seat.owner.digest!==C.ENTITY.entityDigest)return fail('CHAIR_OR_SEAT_MISMATCH');if(!bag||bag.physicalBodyRef.recordId!==SCHOOL_BAG_BODY.bodyId||bag.physicalBodyRef.revision!==SCHOOL_BAG_BODY.revision||bag.physicalBodyRef.digest!==SCHOOL_BAG_BODY.geometryDigest)return fail('BAG_REF_MISMATCH');
 // R1 v4 / v2.1.0: exactly one additional entity - the synthetic training unit - with
 // exact pinned refs, an admitted owner-body binding linking the recovered bag body
 // to the AUTHORED_NEW owner body, and the bag carrying the interior floor surface.
 let v21Bindings=null;
 if(isV21){const unit=by['synthetic-training-unit-v1'],UB=SYN.UNIT_BODY.definition,OE=SYN.OWNER_ENTITY.definition,FL=SYN.INTERIOR_FLOOR.definition;
  if(!unit||unit.physicalBodyRef.recordId!==UB.bodyDefinitionId||unit.physicalBodyRef.revision!==UB.bodyRevision||unit.physicalBodyRef.digest!==UB.canonicalDigest)return fail('SYNTHETIC_UNIT_REF_MISMATCH');
  if(bag.physicalState?.supportSurface?.supportSurfaceId!==FL.supportSurfaceId||bag.physicalState.supportSurface.surfaceRevision!==FL.surfaceRevision||bag.physicalState.supportSurface.canonicalDigest!==FL.canonicalDigest)return fail('BAG_INTERIOR_FLOOR_MISMATCH');
  const bd=SYN.OWNER_BODY_BINDING.binding;
  if(!Array.isArray(p.ownerBodyBindings)||p.ownerBodyBindings.length!==1||p.ownerBodyBindings[0].canonicalDigest!==bd.canonicalDigest)return fail('OWNER_BODY_BINDING_MISMATCH');
  v21Bindings=[SYN.OWNER_BODY_BINDING];}if(p.supportRelations.some(r=>digest(r.contactRegionGeometry)!==r.contactRegionDigest))return fail('CONTACT_REGION_DIGEST_MISMATCH');if(p.supportRelations.length!==p.entities.length||p.entities.some(e=>!p.supportRelations.some(r=>r.supportedEntityId===e.entityId)))return fail('REQUIRED_SUPPORT_RELATION_MISSING');const state={entities:by,supportRelations:p.supportRelations};const r=validateRelations(p.supportRelations,state,{targetWorldRevision:1,ownerBodyBindings:v21Bindings});if(r.status!=='VALIDATED')return fail('SUPPORT_RELATION_INVALID:'+r.code);return Object.freeze({status:'VALIDATED',canonicalBytes:canonicalBytes(p).toString('hex'),package:p,index:buildIndex(p.supportRelations)})}module.exports={validateScenePackage};
