'use strict';
const CONTRACT_VERSION='1.0.0';
const RECORD_TYPES=Object.freeze(['ASSET','GEOMETRY','SEMANTIC_ENTITY','BINDING_PROOF','CONTACT_MODEL','ENTITY_PACKAGE','SCENE_PACKAGE']);
const LIFECYCLE_STATES=Object.freeze(['REFERENCE','VIEW_ONLY','QUARANTINED','REJECTED','CANDIDATE']);
const PROOF_STATUSES=Object.freeze(['UNVERIFIED','INVALID','CANDIDATE']);
module.exports={CONTRACT_VERSION,RECORD_TYPES,LIFECYCLE_STATES,PROOF_STATUSES};
