'use strict';
const {digest}=require('./canonical'),{isCanonical}=require('./rotation');
const PROVENANCE=new Set(['RECOVERED','AUTHORED_NEW','VERIFIED','REFERENCE_ONLY','UNKNOWN']);
const ROLES=new Set(['CASUALTY','BYSTANDER','RESPONDER','OTHER_NPC']);
const ACCESS=new Set(['REACHABLE','PARTIALLY_REACHABLE','BLOCKED','HAZARD_GATED','REQUIRES_ENVIRONMENTAL_ACTION','REQUIRES_ACCESS_CHANGE','UNKNOWN']);
function sealed(kind,x){const y={contractVersion:'1.0.0',kind,...structuredClone(x)};y.digest=digest(y,'digest');return Object.freeze(y)}
function frame(x){if(!x.frameId||!['WORLD','ENTITY_LOCAL','FEATURE_LOCAL','SURFACE_LOCAL','BODY_LOCAL','CONTACT_REGION_LOCAL'].includes(x.frameKind)||x.frameKind==='WORLD'&&x.parentFrameRef||x.frameKind!=='WORLD'&&!x.parentFrameRef||!Array.isArray(x.translationMicrounits)||x.translationMicrounits.length!==3||!isCanonical(x.rotationQuaternionRatio))throw TypeError('INVALID_FRAME');return sealed('CoordinateFrameDefinition',x)}
function domainDescriptor(x){if(!x.domain||!x.authorityId||!Array.isArray(x.permittedWriters)||!Array.isArray(x.readDependencies)||!Array.isArray(x.invalidationDependencies)||!x.eventContractRef||!x.evidenceContractRef)throw TypeError('INVALID_DOMAIN_DESCRIPTOR');return sealed('DomainAuthorityDescriptor',x)}
function scenarioDefinition(x){if(!x.scenarioDefinitionId||!Array.isArray(x.casualtyRefs)||!Array.isArray(x.entityRefs)||!Array.isArray(x.eventRefs)||!Array.isArray(x.hazardRefs)||!Array.isArray(x.constraintRefs))throw TypeError('INVALID_SCENARIO_MANIFEST');return sealed('ScenarioDefinition',x)}
function scenarioInstance(x){if(!x.scenarioInstanceId||!Array.isArray(x.domainStateRefs)||!Array.isArray(x.casualties)||new Set(x.casualties.map(c=>c.casualtyId)).size!==x.casualties.length||!Array.isArray(x.causalLedger))throw TypeError('INVALID_SCENARIO_INSTANCE');return sealed('ScenarioInstance',x)}
function entityDefinition(x){if(!x.entityDefinitionId||!x.semanticRef||!Array.isArray(x.components)||!Array.isArray(x.capabilityRefs))throw TypeError('INVALID_ENTITY_DEFINITION');return sealed('EntityDefinition',x)}
function actor(x){if(!x.actorId||!ROLES.has(x.role)||!x.entityRef)throw TypeError('INVALID_ACTOR');return sealed('ActorDefinition',x)}
function constraint(x){if(!x.constraintId||!x.constrainedEntityRef||!x.constrainedBodyRegionRef||!x.constrainingFeatureRef||!x.frameRef||!x.semanticType||!x.motionDeclaration||!Array.isArray(x.dependencyRefs)||!x.lifecycle||!Array.isArray(x.releasePreconditions)||!x.postReleaseTransitionIntent)throw TypeError('INVALID_CONSTRAINT');return sealed('ConstraintRelation',x)}
function accessibility(x){if(!x.assessmentId||!x.actorRef||!x.targetRef||!x.objective||!ACCESS.has(x.status)||!Array.isArray(x.topologyRefs)||!Array.isArray(x.dependencyRefs)||!Array.isArray(x.blockers)||!Array.isArray(x.evidenceRefs))throw TypeError('INVALID_ACCESSIBILITY_ASSESSMENT');return sealed('AccessibilityAssessment',x)}
function hazard(x){if(!x.hazardStateId||!Array.isArray(x.hazards)||!x.environmentStateRef)throw TypeError('INVALID_HAZARD_STATE');for(const h of x.hazards)if(!h.hazardId||!h.semanticType||!h.sourceOrRegionRef||!h.effectBindings)throw TypeError('INVALID_HAZARD');return sealed('HazardState',x)}
function clinicalBoundary(x){if(!x.clinicalStateRef||!x.presentationProjectionId||!Array.isArray(x.exposedObservationRefs)||!Array.isArray(x.hiddenStateRefs))throw TypeError('INVALID_CLINICAL_PRESENTATION_BOUNDARY');return sealed('ClinicalPresentationProjection',x)}
function progressionIntent(x){if(!x.intentId||!['PHYSICAL','CLINICAL','HAZARD','CONSTRAINT','ENVIRONMENT'].includes(x.targetDomain)||!x.authorityId||!Array.isArray(x.dependencyRefs)||!x.causeRef)throw TypeError('INVALID_PROGRESSION_INTENT');return sealed('TypedDomainIntent',x)}
function visualBinding(x){if(!x.bindingId||!x.semanticEntityRef||!x.physicalEntityRef||!x.physicalBodyRef||!x.visualAssetFamilyRef||!x.visualVariantId||!Array.isArray(x.alignmentAnchors)||!x.transformSync||!x.visibilityPolicy||!x.qualityTierPolicy)throw TypeError('INVALID_VISUAL_BINDING');return sealed('VisualBindingDefinition',x)}
function provenance(x){if(!PROVENANCE.has(x.classification)||!x.domain||!Array.isArray(x.evidenceRefs))throw TypeError('INVALID_PROVENANCE');return sealed('ProvenanceRecord',x)}
module.exports={PROVENANCE,ROLES,ACCESS,frame,domainDescriptor,scenarioDefinition,scenarioInstance,entityDefinition,actor,constraint,accessibility,hazard,clinicalBoundary,progressionIntent,visualBinding,provenance};
