'use strict';
function abs(x){return x<0n?-x:x}function gcd(a,b){a=abs(a);b=abs(b);while(b)[a,b]=[b,a%b];return a}
function canonicalQuaternion(q){if(!Array.isArray(q)||q.length!==4)throw TypeError('INVALID_QUATERNION');let x=q.map(v=>{if(!/^-?(0|[1-9][0-9]*)$/.test(String(v)))throw TypeError('NON_INTEGER_QUATERNION');return BigInt(v)});if(x.every(v=>v===0n))throw TypeError('ZERO_QUATERNION');let g=x.reduce(gcd);x=x.map(v=>v/g);const first=x.find(v=>v!==0n);if(first<0n)x=x.map(v=>-v);return Object.freeze(x.map(String))}
function isCanonical(q){try{return JSON.stringify(canonicalQuaternion(q))===JSON.stringify(q)}catch{return false}}
function rotationMatrixRational(q){const [w,x,y,z]=canonicalQuaternion(q).map(BigInt),d=w*w+x*x+y*y+z*z;const n=[[w*w+x*x-y*y-z*z,2n*(x*y-w*z),2n*(x*z+w*y)],[2n*(x*y+w*z),w*w-x*x+y*y-z*z,2n*(y*z-w*x)],[2n*(x*z-w*y),2n*(y*z+w*x),w*w-x*x-y*y+z*z]];return Object.freeze({numerators:n.map(r=>Object.freeze(r.map(String))),denominator:String(d)})}
function lcmGcd(a,b){return gcd(a,b)}
function reduceVector(ns,d){let g=abs(d);for(const n of ns)g=gcd(g,n);if(d<0n){d=-d;ns=ns.map(n=>-n)}return {numerators:ns.map(n=>String(n/g)),denominator:String(d/g)}}
function multiplyQuaternion(a,b){const [aw,ax,ay,az]=canonicalQuaternion(a).map(BigInt),[bw,bx,by,bz]=canonicalQuaternion(b).map(BigInt);return canonicalQuaternion([aw*bw-ax*bx-ay*by-az*bz,aw*bx+ax*bw+ay*bz-az*by,aw*by-ax*bz+ay*bw+az*bx,aw*bz+ax*by-ay*bx+az*bw].map(String))}
function composeRigid(parent,local){const pq=canonicalQuaternion(parent.rotationQuaternionRatio),lq=canonicalQuaternion(local.rotationQuaternionRatio),m=rotationMatrixRational(pq),md=BigInt(m.denominator),pd=BigInt(parent.translationDenominator||'1'),ld=BigInt(local.translationDenominator||'1'),pn=(parent.translationNumerators||parent.translationMicrounits).map(BigInt),ln=(local.translationNumerators||local.translationMicrounits).map(BigInt),mn=m.numerators.map(r=>r.map(BigInt)),d=pd*md*ld,nums=[0,1,2].map(i=>pn[i]*md*ld+pd*mn[i].reduce((z,v,j)=>z+v*ln[j],0n));const t=reduceVector(nums,d);return Object.freeze({translationNumerators:Object.freeze(t.numerators),translationDenominator:t.denominator,rotationQuaternionRatio:multiplyQuaternion(pq,lq)})}
module.exports={canonicalQuaternion,isCanonical,rotationMatrixRational,multiplyQuaternion,composeRigid};
