'use strict';
// Exact-proposal equality validator (not an independent structural validator) and restricted preparation port. Not scene admission.
const {digest,deepFreeze}=require('../../contracts/canonical');
const C=require('../door-world-genesis/candidate');
const {model:oldModel}=require('../scene-v2/package');
const {schoolGeometryAdapter}=require('../school-geometry-adapter');
const {projectKnownBodyBounds}=require('../door-legality-adapter');
const keys=['minX','maxX','minY','maxY','minZ','maxZ'];
const box=v=>Object.fromEntries(keys.map(k=>[k,Math.round(v[k]*1e6)]));
const contact=(a,b)=>!['X','Y','Z'].some(k=>a['max'+k]<b['min'+k]||b['max'+k]<a['min'+k]);
function validateNewModel({packet,surfaceModel,...extra}={}){try{if(Object.keys(extra).length)return deepFreeze({status:'REJECTED',reason:'EXTRA_INPUT'});const exact=C.definition(packet);if(surfaceModel.units!=='METERS'||surfaceModel.surfaceModelDigest!==digest({...surfaceModel,surfaceModelDigest:undefined})||digest(surfaceModel)!==digest(exact))return deepFreeze({status:'REJECTED',reason:'MODEL_NOT_EXACT_REVIEWED_PROPOSAL'});return deepFreeze({status:'VALIDATED_PREPARATION_NOT_ADMITTED',modelDigest:surfaceModel.surfaceModelDigest})}catch{return deepFreeze({status:'REJECTED',reason:'MODEL_INVALID'})}}
function changedRegions(surfaceModel){const oldBy=new Map(oldModel.surfaces.map(s=>[s.surfaceId,s])),newBy=new Map(surfaceModel.surfaces.map(s=>[s.surfaceId,s])),regions=[];for(const id of new Set([...oldBy.keys(),...newBy.keys()])){const a=oldBy.get(id),b=newBy.get(id);if(digest(a||null)!==digest(b||null)){if(id==='floor'){const oldAllowed=a.region.allowed;for(const r of b.region.allowed)if(!oldAllowed.some(x=>digest(x)===digest(r)))regions.push({minX:Math.round(r.minX*1e6),maxX:Math.round(r.maxX*1e6),minZ:Math.round(r.minZ*1e6),maxZ:Math.round(r.maxZ*1e6),minY:-Number.MAX_SAFE_INTEGER,maxY:Number.MAX_SAFE_INTEGER})}else for(const s of [a,b].filter(Boolean))for(const v of s.region.volumes)regions.push(box(v))}}regions.push(surfaceModel.doorDefinition.closedLeaf,surfaceModel.doorDefinition.openLeaf);return regions}
function createPreparationLegalityPort({packet,surfaceModel}){const validated=validateNewModel({packet,surfaceModel});const fail=(reason,detail={})=>deepFreeze({outcome:'UNKNOWN',reason,classification:'NEW_WORLD_LEGALITY_PREPARATION_NOT_ADMITTED',...detail});return Object.freeze({kind:'RESTRICTED_NEW_MODEL_PREPARATION_PORT',evaluate(input){try{
 if(validated.status!=='VALIDATED_PREPARATION_NOT_ADMITTED')return fail('MODEL_NOT_VALIDATED');
 const state=input.proposedState,id=input.command.entityId,e=state.entities[id],b=projectKnownBodyBounds(e);if(!e||!b||JSON.stringify(e.transform.orientation)!=='[0,0,0,1]'||JSON.stringify(e.transform.scaleMicrounits)!=='[1000000,1000000,1000000]'||e.transform.positionMicrounits?.length!==3||!e.transform.positionMicrounits.every(Number.isSafeInteger))return fail('BODY_TRANSFORM_OR_POSTURE_UNSUPPORTED');
 if(state.surfaces?.digest!==surfaceModel.surfaceModelDigest||state.sceneDefinitionRef?.digest!==surfaceModel.surfaceModelDigest||state.environmentPhysicalState?.surfaceModelDigest!==surfaceModel.surfaceModelDigest)return fail('STATE_MODEL_BINDING_MISSING');
 const door=state.environmentPhysicalState.doorEntities;if(door?.length!==1||door[0].state!=='CLOSED'||digest(door[0].collisionBoundsMicrounits)!==digest(surfaceModel.doorDefinition.closedLeaf))return fail('CLOSED_DOOR_RECORD_REQUIRED');
 const bounds=Object.fromEntries(keys.map(k=>[k,b[k]+e.transform.positionMicrounits['XYZ'.indexOf(k.slice(-1))]]));
 const solids=surfaceModel.surfaces.filter(s=>['WALL','OBSTACLE'].includes(s.type)).flatMap(s=>s.region.volumes.map(v=>({id:s.surfaceId,bounds:box(v)}))).concat([{id:'CLOSED_DOOR',bounds:door[0].collisionBoundsMicrounits}]);const hit=solids.find(s=>contact(bounds,s.bounds));if(hit)return deepFreeze({outcome:'PREPARATION_SOLID_CONTACT_NOT_ADMITTED',reason:'NEW_SOLID_CONTACT',solidId:hit.id,classification:'NEW_WORLD_LEGALITY_PREPARATION_NOT_ADMITTED'});
 if(changedRegions(surfaceModel).some(r=>contact(bounds,r)))return fail('CHANGED_REGION_NO_OLD_EVIDENCE_REUSE');
 const oldFloor=oldModel.surfaces.find(s=>s.surfaceId==='floor'),newFloor=surfaceModel.surfaces.find(s=>s.surfaceId==='floor');if(JSON.stringify(oldFloor.planeOrDepth)!==JSON.stringify(newFloor.planeOrDepth)||JSON.stringify(oldFloor.region.allowed)!==JSON.stringify(newFloor.region.allowed.slice(0,oldFloor.region.allowed.length)))return fail('FLOOR_SLICE_NOT_IDENTICAL');
 for(const old of oldModel.surfaces.filter(s=>s.surfaceId.startsWith('locker')))if(JSON.stringify(old)!==JSON.stringify(surfaceModel.surfaces.find(s=>s.surfaceId===old.surfaceId)))return fail('LOCKER_SLICE_NOT_IDENTICAL');
 // Explicit query-scoped evidence comparison: old adapter sees OLD model/scene,
 // not a forged assertion that its pins certify the new model. New exclusion above is separate.
 const oldQuery={...input,proposedState:{...state,sceneDefinitionRef:{sceneId:'school'},surfaces:{id:oldModel.surfaceModelId,revision:oldModel.revision,digest:oldModel.surfaceModelDigest}}};const r=schoolGeometryAdapter({surfaceModel:oldModel}).evaluate(oldQuery);
 return deepFreeze({outcome:r.outcome==='PASS'?'OLD_EVIDENCE_REUSE_CLEAR_NOT_ADMITTED':'PREPARATION_'+r.outcome+'_NOT_ADMITTED',reason:'QUERY_SCOPED_IDENTICAL_FLOOR_LOCKER_EVIDENCE_PLUS_NEW_SOLID_CHECK',classification:'NEW_WORLD_LEGALITY_PREPARATION_NOT_ADMITTED',reuseRegionProofDigest:digest({bounds,changedRegions:changedRegions(surfaceModel)}),oldEvidence:r.evidence,limitations:['OLD_QUERY_EVIDENCE_ONLY_NOT_NEW_MODEL_ADMISSION','CHANGED_REGION_AND_APRON_QUERIES_UNKNOWN','NO_RUNTIME_COMMIT_RENDER_OR_MOVEMENT_ACTIVATION']});
 }catch{return fail('LEGALITY_INPUT_UNSUPPORTED')}}})}
module.exports={validateNewModel,createPreparationLegalityPort,changedRegions};
