'use strict';const {LIMITS,parse,checked,reduce,bitLength}=require('./integer'),{quaternion,matrix,multiply}=require('./rotation');
function vector(numerators,denominator='1'){if(!Array.isArray(numerators)||numerators.length!==3)throw Error('MALFORMED_VECTOR');const d=parse(String(denominator));if(d<=0n)throw Error('INVALID_DENOMINATOR');return Object.freeze(reduce(numerators.map(s=>parse(String(s))),d))}
function rotate(v,q){v=vector(v.numerators,v.denominator);const m=matrix(q),d=checked(BigInt(v.denominator)*BigInt(m.denominator)),ns=m.numerators.map(r=>r.reduce((z,n,i)=>checked(z+BigInt(n)*BigInt(v.numerators[i])),0n));return Object.freeze(reduce(ns,d))}
function add(a,b){a=vector(a.numerators,a.denominator);b=vector(b.numerators,b.denominator);const ad=BigInt(a.denominator),bd=BigInt(b.denominator),d=checked(ad*bd);return Object.freeze(reduce(a.numerators.map((n,i)=>checked(BigInt(n)*bd+BigInt(b.numerators[i])*ad)),d))}
function transform({translationNumerators,translationDenominator='1',rotationQuaternionRatio}){return Object.freeze({translation:vector(translationNumerators,translationDenominator),rotationQuaternionRatio:quaternion(rotationQuaternionRatio)})}
function compose(parent,local){parent=transform(parentToInput(parent));local=transform(parentToInput(local));return Object.freeze({translation:add(parent.translation,rotate(local.translation,parent.rotationQuaternionRatio)),rotationQuaternionRatio:multiply(parent.rotationQuaternionRatio,local.rotationQuaternionRatio)})}
function parentToInput(t){return t.translation?{translationNumerators:t.translation.numerators,translationDenominator:t.translation.denominator,rotationQuaternionRatio:t.rotationQuaternionRatio}:t}
function stats(t){t=transform(parentToInput(t));return {translationNumeratorBits:Math.max(...t.translation.numerators.map(x=>bitLength(BigInt(x)))),translationDenominatorBits:bitLength(BigInt(t.translation.denominator)),quaternionComponentBits:Math.max(...t.rotationQuaternionRatio.map(x=>bitLength(BigInt(x))))}}
module.exports={vector,rotate,add,transform,compose,stats,parentToInput};
