'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../../src/verified-architecture-phase2-v3/definitions'),G=require('../../src/numeric-frame-rotation/graph'),C=require('../../src/verified-architecture-phase2-v3/closure-records'),{evaluateV3}=require('../../src/verified-architecture-phase2-v3/evaluate');
const q=['1','0','0','0'],rf=f=>({frameId:f.frameId,revision:f.revision,digest:f.digest}),rg=g=>({geometryId:g.geometryId,revision:g.revision,digest:g.digest});
function F(id,p=null,t=['0','0','0']){return G.sealFrame({frameId:id,frameKind:p?'ENTITY_LOCAL':'WORLD',parentFrameRef:p?rf(p):null,translationMicrounits:t,rotationQuaternionRatio:q,revision:1,provenance:'SYNTHETIC'})}
function B(id,f,h=['5','5','5']){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:f.frameId,representationKind:'ORIENTED_BOX',shape:{halfExtentsMicrounits:h},capabilities:[],limitations:[]})}
function R(id,f,support=false,e='20'){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:f.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:[['-'+e,'0','-'+e],[e,'0','-'+e],[e,'0',e],['-'+e,'0',e]],normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:support?['SUPPORT']:[],limitations:[]})}
function O(id,f,owner){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:f.frameId,representationKind:'OPENING_REGION',shape:{vertices:[['-50','-50','0'],['50','-50','0'],['50','50','0'],['-50','50','0']],normal:['0','0','1'],sidedness:'FRONT_ONLY',localFrameRef:rf(f),boundaryFeatureRef:{boundaryFeatureId:owner,revision:1}},capabilities:[],limitations:[]})}
function pin(g,f){return {geometryId:g.geometryId,revision:g.revision,digest:g.digest,localFrameRef:rf(f)}}
function body(id){const b={bodyId:id,revision:1,provenance:'SYNTHETIC',limitations:[]};b.digest=D.digest(b,'digest');return b}
function rb(b){return {bodyId:b.bodyId,revision:b.revision,digest:b.digest}}
function openingRun({bodyPin=true,solidAuthorityPin=true,forgeBody=false,forgeSolid=false}={}){const w=F('w'),of=F('of',w),bf=F('bf',w),sf=F('sf',w,['1000','0','0']),bd=B('body',bf),solid=B('solid',sf),open=O('open',of,'wall'),owner=C.boundaryFeature({boundaryFeatureId:'wall',revision:1,localFrameRef:rf(of),solidGeometryRefs:[rg(solid)],openingRegionRefs:[rg(open)],provenance:'SYNTHETIC',limitations:[]}),bp=pin(bd,bf),sp=pin(solid,sf);if(forgeBody)bp.digest='f'.repeat(64);if(forgeSolid)sp.digest='e'.repeat(64);const req={apiVersion:'3.0.0',requestId:'audit-opening',queryType:'BODY_VS_OPENING_BOUNDARY',bodyGeometryId:'body',targetGeometryId:'open',boundaryFeatureRef:{boundaryFeatureId:'wall',revision:1,digest:owner.digest}};if(bodyPin)req.bodyGeometryRef=bp;return evaluateV3(req,{frames:[w,of,bf,sf],definitions:{body:bd,solid,open},boundaryFeatures:{wall:owner},authoritativeGeometryRefs:solidAuthorityPin?{solid:sp}:{}})}
function containmentRun({bodyPin=true,targetPin=true,forgeBody=false,forgeTarget=false}={}){const w=F('cw'),bf=F('cb',w),tf=F('ct',w),bd=B('cbody',bf),target=B('ctarget',tf,['50','50','50']),bp=pin(bd,bf),tp=pin(target,tf);if(forgeBody)bp.digest='a'.repeat(64);if(forgeTarget)tp.digest='b'.repeat(64);const req={apiVersion:'3.0.0',requestId:'audit-containment',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',bodyGeometryId:bd.geometryId,targetGeometryId:target.geometryId};if(bodyPin)req.bodyGeometryRef=bp;if(targetPin)req.targetGeometryRef=tp;return evaluateV3(req,{frames:[w,bf,tf],definitions:{[bd.geometryId]:bd,[target.geometryId]:target}})}
function supportRun({authority=true,embedded=true,forgeAuthority=false}={}){const w=F('sw'),cg=R('contactGeom',w,false,'2'),surface=R('surface',w,true,'10'),bd=body('sb'),br=rb(bd),geomRef={...rg(cg)},surfRef={...rg(surface)};if(embedded){geomRef.localFrameRef=rf(w);surfRef.localFrameRef=rf(w)}const cr=C.contactRegion({contactRegionId:'sc',revision:1,supportedBodyRef:br,geometryRef:geomRef,expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:rf(w),components:['0','-1','0']},provenance:'SYNTHETIC',limitations:[]}),rel=C.supportRelation({relationId:'sr',requirement:'REQUIRED',bodyRef:br,contactRegionRef:{contactRegionId:cr.contactRegionId,revision:cr.revision,digest:cr.digest},supportSurfaceRef:surfRef,contactPolicy:'EXACT_OPPOSED_PHYSICAL_NORMAL',frameRefs:[rf(w)]}),p=rf(w);if(forgeAuthority)p.digest='c'.repeat(64);return evaluateV3({apiVersion:'3.0.0',requestId:'audit-support',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',supportRelations:[rel]},{frames:[w],definitions:{contactGeom:cg,surface},bodies:{sb:bd},contactRegions:{sc:cr},authoritativeGeometryFrameRefs:authority?{contactGeom:p,surface:p}:undefined})}

test('AUDIT-OPENING-VALID fully pinned opening can reach PASS',()=>{const r=openingRun();assert.equal(r.status,'PASS');assert.equal(r.reason,'VALID');assert.ok(r.evidence.bodyAuthorityPin);assert.ok(r.evidence.validatedRefs.solids[0].frame)});
test('AUDIT-OPENING-BODY-PIN-MISSING cannot reach geometry',()=>{const r=openingRun({bodyPin:false});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-OPENING-BODY-DIGEST-FORGED is stale before geometry',()=>{const r=openingRun({forgeBody:true});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('AUDIT-OPENING-SOLID-AUTHORITY-PIN-MISSING cannot reach SAT',()=>{const r=openingRun({solidAuthorityPin:false});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-OPENING-SOLID-DIGEST-FORGED is stale before SAT',()=>{const r=openingRun({forgeSolid:true});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});

test('AUDIT-CONTAINMENT-VALID independent body and target pins can reach PASS',()=>{const r=containmentRun();assert.equal(r.status,'PASS');assert.equal(r.reason,'VALID')});
test('AUDIT-CONTAINMENT-BODY-PIN-MISSING is unsupported before geometry',()=>{const r=containmentRun({bodyPin:false});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-CONTAINMENT-TARGET-PIN-MISSING is unsupported before geometry',()=>{const r=containmentRun({targetPin:false});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-CONTAINMENT-FORGED-BODY is stale before geometry',()=>{const r=containmentRun({forgeBody:true});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('AUDIT-CONTAINMENT-FORGED-TARGET is stale before geometry',()=>{const r=containmentRun({forgeTarget:true});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});

test('AUDIT-SUPPORT-VALID independently pinned frames can reach PASS',()=>{const r=supportRun();assert.equal(r.status,'PASS');assert.equal(r.reason,'VALID')});
test('AUDIT-SUPPORT-EMBEDDED-PINS-ARE-NOT-INDEPENDENT embedded localFrameRef without authority is unsupported',()=>{const r=supportRun({authority:false,embedded:true});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-SUPPORT-NO-PINS is unsupported',()=>{const r=supportRun({authority:false,embedded:false});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('AUDIT-SUPPORT-FORGED-INDEPENDENT-FRAME-PIN is stale before proof',()=>{const r=supportRun({forgeAuthority:true});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
