'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../../src/verified-architecture-phase2-v3/definitions'),G=require('../../src/numeric-frame-rotation/graph'),{evaluateV3}=require('../../src/verified-architecture-phase2-v3/evaluate');
const q=['1','0','0','0'];function F(id,p=null,rev=1){return G.sealFrame({frameId:id,frameKind:p?'ENTITY_LOCAL':'WORLD',parentFrameRef:p?rf(p):null,translationMicrounits:['0','0','0'],rotationQuaternionRatio:q,revision:rev,provenance:'SYNTHETIC'})}function rf(f){return {frameId:f.frameId,revision:f.revision,digest:f.digest}}function B(id,f,h=['5','5','5'],rev=1){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:rev,provenance:{},localFrameId:f.frameId,representationKind:'ORIENTED_BOX',shape:{halfExtentsMicrounits:h},capabilities:[],limitations:[]})}function pg(g,f){return {geometryId:g.geometryId,revision:g.revision,digest:g.digest,localFrameRef:rf(f)}}function C(id,w,children){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:w.frameId,representationKind:'COMPOUND',shape:{children},capabilities:[],limitations:[]})}function run(body,target,frames,defs,bp,tp){return evaluateV3({apiVersion:'3.0.0',requestId:'containment-preflight',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',bodyGeometryId:body.geometryId,targetGeometryId:target.geometryId,bodyGeometryRef:bp,targetGeometryRef:tp},{frames,definitions:Object.fromEntries(defs.map(x=>[x.geometryId,x]))})}function base(){const w=F('w'),bf=F('bf',w),tf=F('tf',w),b=B('body',bf),t=B('target',tf,['50','50','50']);return {w,bf,tf,b,t,bp:pg(b,bf),tp:pg(t,tf)}}
test('REG-V3-CONTAINMENT-FORGED-BODY-DIGEST stops before axisContainment',()=>{const x=base(),p={...x.bp,digest:'e'.repeat(64)},r=run(x.b,x.t,[x.w,x.bf,x.tf],[x.b,x.t],p,x.tp);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE');assert.equal(r.evidence.containment,undefined)});
test('REG-V3-CONTAINMENT-FORGED-TARGET-DIGEST stops before axisContainment',()=>{const x=base(),p={...x.tp,digest:'f'.repeat(64)},r=run(x.b,x.t,[x.w,x.bf,x.tf],[x.b,x.t],x.bp,p);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE');assert.equal(r.evidence.containment,undefined)});
test('REG-V3-CONTAINMENT-STALE-TARGET-FRAME stops before axisContainment',()=>{const x=base(),p={...x.tp,localFrameRef:{...x.tp.localFrameRef,digest:'a'.repeat(64)}},r=run(x.b,x.t,[x.w,x.bf,x.tf],[x.b,x.t],x.bp,p);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('REG-V3-CONTAINMENT-STALE-BODY-FRAME stops before axisContainment',()=>{const x=base(),p={...x.bp,localFrameRef:{...x.bp.localFrameRef,revision:99}},r=run(x.b,x.t,[x.w,x.bf,x.tf],[x.b,x.t],p,x.tp);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('REG-V3-CONTAINMENT-FORGED-COMPOUND-CHILD-REF stops before axisContainment',()=>{const x=base(),cf=F('childf',x.w),child=B('child',cf),compound=C('compound',x.w,[{childId:'c1',geometryId:'child'}]),bp={...pg(compound,x.w),childGeometryRefs:[{childId:'c1',...pg(child,cf),digest:'b'.repeat(64)}]},r=run(compound,x.t,[x.w,cf,x.tf],[compound,child,x.t],bp,x.tp);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE');assert.equal(r.evidence.containment,undefined)});
test('REG-V3-CONTAINMENT-MISSING-INDEPENDENT-PIN is unsupported and never PASS',()=>{const x=base(),r=evaluateV3({apiVersion:'3.0.0',requestId:'missing-pin',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',bodyGeometryId:'body',targetGeometryId:'target'},{frames:[x.w,x.bf,x.tf],definitions:{body:x.b,target:x.t}});assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY');assert.equal(r.evidence.containment,undefined)});
