'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),D=require('../../src/verified-architecture-phase2-v3/definitions'),G=require('../../src/numeric-frame-rotation/graph'),C=require('../../src/verified-architecture-phase2-v3/closure-records'),{evaluateV3}=require('../../src/verified-architecture-phase2-v3/evaluate');
function F(id){return G.sealFrame({frameId:id,frameKind:'WORLD',parentFrameRef:null,translationMicrounits:['0','0','0'],rotationQuaternionRatio:['1','0','0','0'],revision:1,provenance:'SYNTHETIC'})}const rf=f=>({frameId:f.frameId,revision:f.revision,digest:f.digest}),rg=g=>({geometryId:g.geometryId,revision:g.revision,digest:g.digest});
function region(id,f,y,extent,support=false){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{regression:'OFFSET_SUPPORT_PLANE'},localFrameId:f.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:[[String(-extent),String(y),String(-extent)],[String(extent),String(y),String(-extent)],[String(extent),String(y),String(extent)],[String(-extent),String(y),String(extent)]],normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:support?['SUPPORT']:[],limitations:[]})}
function body(){const b={bodyId:'body',revision:1,provenance:'SYNTHETIC',limitations:[]};b.digest=D.digest(b,'digest');return Object.freeze(b)}const rb=b=>({bodyId:b.bodyId,revision:b.revision,digest:b.digest});
function run(contactY){const w=F('world'),surface=region('support-offset',w,10,20,true),contact=region('contact',w,contactY,2,false),b=body(),cr=C.contactRegion({contactRegionId:'contact-region',revision:1,supportedBodyRef:rb(b),geometryRef:rg(contact),expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:rf(w),components:['0','-1','0']},provenance:'SYNTHETIC',limitations:[]}),rel=C.supportRelation({relationId:'required-offset-contact',requirement:'REQUIRED',bodyRef:rb(b),contactRegionRef:{contactRegionId:cr.contactRegionId,revision:cr.revision,digest:cr.digest},supportSurfaceRef:rg(surface),contactPolicy:'EXACT_OPPOSED_PHYSICAL_NORMAL',frameRefs:[rf(w)]}),result=evaluateV3({apiVersion:'3.0.0',requestId:'offset-plane-regression',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',supportRelations:[rel]},{frames:[w],definitions:{[surface.geometryId]:surface,[contact.geometryId]:contact},bodies:{[b.bodyId]:b},contactRegions:{[cr.contactRegionId]:cr}});return {result,surface}}
test('REG-V3-SUPPORT-OFFSET-PLANE-001 coplanar support at local y=10 is VALID and evidence pins a physical polygon vertex',()=>{const {result,surface}=run(10);assert.equal(result.status,'PASS');assert.equal(result.reason,'VALID');const d=result.evidence.supportRelationProofs[0].contactDistanceEvidence;assert.equal(d.classification,'VALID_CONTACT');assert.equal(d.planeAnchorEvidence.supportSurfaceGeometryDigest,surface.digest);assert.equal(d.planeAnchorEvidence.localFrameId,surface.localFrameId);assert.deepEqual(d.planeAnchorEvidence.localCoordinate,['-20','10','-20']);assert.ok(d.planeAnchorEvidence.materializedVertexEvidenceDigest);/* removal control: restoring synthetic [0,0,0] makes this assertion and the geometric PASS impossible for y=10 */});
test('REG-V3-SUPPORT-OFFSET-PLANE-002 floating sign is relative to offset plane',()=>{const {result}=run(11);assert.equal(result.status,'FAIL');assert.equal(result.reason,'CONTACT_FLOATING');assert.equal(result.evidence.supportRelationProofs[0].contactDistanceEvidence.classification,'DEFINITELY_FLOATING')});
test('REG-V3-SUPPORT-OFFSET-PLANE-003 penetrating sign is relative to offset plane',()=>{const {result}=run(9);assert.equal(result.status,'FAIL');assert.equal(result.reason,'CONTACT_PENETRATION');assert.equal(result.evidence.supportRelationProofs[0].contactDistanceEvidence.classification,'DEFINITELY_PENETRATING')});
