'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../../src/verified-architecture-phase2-v3/definitions'),G=require('../../src/numeric-frame-rotation/graph'),C=require('../../src/verified-architecture-phase2-v3/closure-records'),{evaluateV3}=require('../../src/verified-architecture-phase2-v3/evaluate');
const qi=['1','0','0','0'];
function F(id,p=null,t=['0','0','0'],rev=1){return G.sealFrame({frameId:id,frameKind:p?'ENTITY_LOCAL':'WORLD',parentFrameRef:p?refF(p):null,translationMicrounits:t,rotationQuaternionRatio:qi,revision:rev,provenance:'SYNTHETIC'})}function refF(f){return {frameId:f.frameId,revision:f.revision,digest:f.digest}}
function B(id,f,h=['10','10','10']){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{classification:'AUTHORED_NEW'},localFrameId:f.frameId,representationKind:'ORIENTED_BOX',shape:{halfExtentsMicrounits:h},capabilities:[],limitations:['SYNTHETIC']})}
function R(id,f,verts=[['-20','0','-20'],['20','0','-20'],['20','0','20'],['-20','0','20']],support=true){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:f.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:verts,normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:support?['SUPPORT']:[],limitations:[]})}
function body(id){const x={bodyId:id,revision:1,provenance:'SYNTHETIC',limitations:[]};x.digest=D.digest(x,'digest');return Object.freeze(x)}function refB(b){return {bodyId:b.bodyId,revision:b.revision,digest:b.digest}}function refG(g){return {geometryId:g.geometryId,revision:g.revision,digest:g.digest}}
function CR(id,b,g,f){return C.contactRegion({contactRegionId:id,revision:1,supportedBodyRef:refB(b),geometryRef:refG(g),expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:refF(f),components:['0','-1','0']},provenance:'SYNTHETIC',limitations:[]})}function refC(c){return {contactRegionId:c.contactRegionId,revision:c.revision,digest:c.digest}}
function SR(id,b,c,s,frames){return C.supportRelation({relationId:id,requirement:'REQUIRED',bodyRef:refB(b),contactRegionRef:refC(c),supportSurfaceRef:refG(s),contactPolicy:'EXACT_OPPOSED_PHYSICAL_NORMAL',frameRefs:frames.map(refF)})}
function supportRun(rel,frames,defs,bodies,contacts){return evaluateV3({apiVersion:'3.0.0',requestId:'support',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',supportRelations:Array.isArray(rel)?rel:[rel]},{frames,definitions:Object.fromEntries(defs.map(x=>[x.geometryId,x])),bodies:Object.fromEntries(bodies.map(x=>[x.bodyId,x])),contactRegions:Object.fromEntries(contacts.map(x=>[x.contactRegionId,x]))})}
function opening(id,f,bref,verts=[['-50','-50','0'],['50','-50','0'],['50','50','0'],['-50','50','0']]){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:f.frameId,representationKind:'OPENING_REGION',shape:{vertices:verts,normal:['0','0','1'],sidedness:'FRONT_ONLY',localFrameRef:refF(f),boundaryFeatureRef:bref},capabilities:[],limitations:[]})}
function BF(id,f,openingRefs,solidRefs=[]){return C.boundaryFeature({boundaryFeatureId:id,revision:1,localFrameRef:refF(f),solidGeometryRefs:solidRefs,openingRegionRefs:openingRefs,provenance:'SYNTHETIC',limitations:[]})}
function openRun(b,o,bf,frames,defs,pin=true){const req={apiVersion:'3.0.0',requestId:'opening',queryType:'BODY_VS_OPENING_BOUNDARY',bodyGeometryId:b.geometryId,targetGeometryId:o.geometryId};if(pin)req.boundaryFeatureRef={boundaryFeatureId:bf.boundaryFeatureId,revision:bf.revision,digest:bf.digest};return evaluateV3(req,{frames,definitions:Object.fromEntries(defs.map(x=>[x.geometryId,x])),boundaryFeatures:{[bf.boundaryFeatureId]:bf}})}
const msg=r=>JSON.stringify(D.norm(r));
test('REG-V3-SUPPORT-POLY-001 full explicit ContactRegion outside finite support fails',()=>{const w=F('w'),cf=F('c',w,['30','0','0']),sf=F('s',w),cg=R('cg',cf,[['-10','0','-10'],['10','0','-10'],['10','0','10'],['-10','0','10']],false),s=R('s',sf),b=body('body'),cr=CR('cr',b,cg,w),rel=SR('rel',b,cr,s,[w,cf,sf]),r=supportRun(rel,[w,cf,sf],[cg,s],[b],[cr]);assert.equal(r.status,'FAIL',msg(r));assert.equal(r.reason,'CONTACT_OUTSIDE_REGION')});
test('REG-V3-NORMAL-001 exact physical normal mismatch fails',()=>{const w=F('w'),cf=F('c',w),sf=F('s',w),cg=R('cg',cf,undefined,false),s=R('s',sf),b=body('body'),cr=C.contactRegion({contactRegionId:'cr',revision:1,supportedBodyRef:refB(b),geometryRef:refG(cg),expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:refF(w),components:['1','0','0']},provenance:'SYNTHETIC',limitations:[]}),rel=SR('rel',b,cr,s,[w,cf,sf]),r=supportRun(rel,[w,cf,sf],[cg,s],[b],[cr]);assert.equal(r.status,'FAIL',msg(r));assert.equal(r.reason,'FAIL_NORMAL_COMPATIBILITY')});
test('REG-V3-SUPPORT-COMPOUND-001 required relations aggregate canonically and bad sibling cannot hide',()=>{const w=F('w'),aF=F('a',w),bF=F('b',w,['100','0','0']),sf=F('s',w),ga=R('ga',aF,undefined,false),gb=R('gb',bF,undefined,false),s=R('s',sf),ba=body('ba'),bb=body('bb'),ca=CR('ca',ba,ga,w),cb=CR('cb',bb,gb,w),ra=SR('z-pass',ba,ca,s,[w,aF,sf]),rb=SR('a-fail',bb,cb,s,[w,bF,sf]),x=supportRun([ra,rb],[w,aF,bF,sf],[ga,gb,s],[ba,bb],[ca,cb]),y=supportRun([rb,ra],[w,aF,bF,sf],[ga,gb,s],[ba,bb],[ca,cb]);assert.equal(x.status,'FAIL',msg(x));assert.equal(x.reason,'CONTACT_OUTSIDE_REGION');assert.equal(x.evidenceDigest,y.evidenceDigest);assert.deepEqual(x.evidence.supportRelationProofs.map(p=>p.relationId),['a-fail','z-pass'])});
test('REG-V3-CONTAINMENT-AABB-001 oriented containment remains non-AABB authority',()=>{const w=F('w'),tf=F('t',w),bf=F('b',w,['100','0','0']),t=B('t',tf,['20','20','20']),b=B('b',bf),r=evaluateV3({apiVersion:'3.0.0',requestId:'c',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',bodyGeometryId:'b',targetGeometryId:'t'},{frames:[w,tf,bf],definitions:{b,t}});assert.equal(r.status,'FAIL')});
test('REG-V3-CONTAINMENT-COMPOUND-001 outside child fails independent of insertion order',()=>{const w=F('w'),tf=F('t',w),af=F('a',w),bf=F('b',w,['100','0','0']),t=B('t',tf,['20','20','20']),a=B('a',af),b=B('b',bf),mk=children=>D.define({geometryId:'compound',schemaVersion:'3.0.0',revision:1,provenance:{},localFrameId:w.frameId,representationKind:'COMPOUND',shape:{children},capabilities:[],limitations:[]}),run=c=>evaluateV3({apiVersion:'3.0.0',requestId:'cc',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',bodyGeometryId:'compound',targetGeometryId:'t'},{frames:[w,tf,af,bf],definitions:{compound:c,a,b,t}}),x=run(mk([{childId:'z',geometryId:'a'},{childId:'a',geometryId:'b'}])),y=run(mk([{childId:'a',geometryId:'b'},{childId:'z',geometryId:'a'}]));assert.equal(x.status,'FAIL');assert.equal(x.evidenceDigest,y.evidenceDigest)});
test('REG-V3-OPENING-AABB-001 valid opening requires independently pinned owner',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm,['5','5','5']),o=opening('o',of,{boundaryFeatureId:'wall',revision:1}),owner=BF('wall',of,[refG(o)]),r=openRun(b,o,owner,[w,of,bfm],[b,o]);assert.equal(r.status,'PASS');assert.equal(r.evidence.boundaryFeatureDigest,owner.digest)});
test('MISSING-BOUNDARY hostile regression: unresolved affirmative owner stops before geometry',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm,['5','5','1000']),o=opening('o',of,{boundaryFeatureId:'MISSING-BOUNDARY',revision:1}),fake=BF('MISSING-BOUNDARY',of,[refG(o)]),r=evaluateV3({apiVersion:'3.0.0',requestId:'hostile',queryType:'BODY_VS_OPENING_BOUNDARY',bodyGeometryId:b.geometryId,targetGeometryId:o.geometryId,boundaryFeatureRef:{boundaryFeatureId:fake.boundaryFeatureId,revision:fake.revision,digest:fake.digest}},{frames:[w,of,bfm],definitions:{body:b,o},boundaryFeatures:{}});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('REG-V3-STALE-SURFACE-001 / OWNER_PIN_MISSING self-consistent owner cannot PASS without independent pin',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm,['5','5','5']),o=opening('o',of,{boundaryFeatureId:'wall',revision:1}),owner=BF('wall',of,[refG(o)]),r=openRun(b,o,owner,[w,of,bfm],[b,o],false);assert.equal(r.status,'UNKNOWN');assert.equal(r.reason,'UNSUPPORTED_GEOMETRY')});
test('REG-V3-STALE-SURFACE-001 / BOUNDARY_OWNER_PIN_TAMPER altered owner with old pin is stale',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm,['5','5','5']),o=opening('o',of,{boundaryFeatureId:'wall',revision:1}),owner=BF('wall',of,[refG(o)]),tampered=BF('wall',of,[]),r=evaluateV3({apiVersion:'3.0.0',requestId:'tamper',queryType:'BODY_VS_OPENING_BOUNDARY',bodyGeometryId:'body',targetGeometryId:'o',boundaryFeatureRef:{boundaryFeatureId:'wall',revision:1,digest:owner.digest}},{frames:[w,of,bfm],definitions:{body:b,o},boundaryFeatures:{wall:tampered}});assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
test('REG-V3-STALE-SURFACE-001 / OPENING_MEMBERSHIP_TAMPER and OPENING_BACKREF_TAMPER are stale',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm,['5','5','5']),o=opening('o',of,{boundaryFeatureId:'wall',revision:1}),other=opening('other',of,{boundaryFeatureId:'wall',revision:1}),owner=BF('wall',of,[refG(other)]),r=openRun(b,o,owner,[w,of,bfm],[b,o,other]);assert.equal(r.reason,'STALE_EVIDENCE');const bad=opening('bad',of,{boundaryFeatureId:'elsewhere',revision:1}),owner2=BF('wall',of,[refG(bad)]),r2=openRun(b,bad,owner2,[w,of,bfm],[b,bad]);assert.equal(r2.reason,'STALE_EVIDENCE')});
test('REG-V3-STALE-SURFACE-001 / OWNER_REF_ORDER canonical owner digest is order invariant',()=>{const w=F('w'),a=R('a',w),b=R('b',w),o1=opening('o1',w,{boundaryFeatureId:'wall',revision:1}),o2=opening('o2',w,{boundaryFeatureId:'wall',revision:1}),x=BF('wall',w,[refG(o2),refG(o1)],[refG(b),refG(a)]),y=BF('wall',w,[refG(o1),refG(o2)],[refG(a),refG(b)]);assert.equal(x.digest,y.digest);assert.deepEqual(x,y)});
test('REG-V3-STALE-SURFACE-001 / missing solid ref is stale before SAT',()=>{const w=F('w'),of=F('o',w),bfm=F('body',w),b=B('body',bfm),o=opening('o',of,{boundaryFeatureId:'wall',revision:1}),missing={geometryId:'missing',revision:1,digest:'0'.repeat(64)},owner=BF('wall',of,[refG(o)],[missing]),r=openRun(b,o,owner,[w,of,bfm],[b,o]);assert.equal(r.status,'INVALID');assert.equal(r.reason,'STALE_EVIDENCE')});
