'use strict';
const A=require('../../authoring');
const V=A.V1, decisionId='gate-c-chair-authoring-001';
const rawBody={schemaVersion:'1.0.0',bodyDefinitionId:'school/treatment-chair',bodyRevision:1,semanticType:'treatment-chair',profileId:'school-treatment-chair',postureDefinitionId:'rigid-upright',postureSemanticType:'SYNTHETIC_POSTURE',units:{linear:V.linearUnit,microunitsPerAuthoredUnit:V.microunitsPerAuthoredUnit},coordinateFrame:{handedness:V.handedness,axes:V.axes,upAxis:V.upAxis,forwardDirection:V.forwardDirection,transformOrder:V.transformOrder},localOrigin:{kind:'AUTHOR_DECLARED_CONTACT_FRAME',positionMicrounits:[0,0,0]},orientationContract:{mode:'IDENTITY_ONLY',canonical:V.canonicalOrientation},components:[
{componentId:'lower-frame',primitiveType:'AABB',participationRole:'BOTH',dimensionsMicrounits:[500000,450000,500000],localTransform:{translationMicrounits:[0,225000,0],orientation:V.canonicalOrientation}},
{componentId:'seat-slab',primitiveType:'AABB',participationRole:'BOTH',dimensionsMicrounits:[500000,40000,500000],localTransform:{translationMicrounits:[0,470000,0],orientation:V.canonicalOrientation}},
{componentId:'backrest',primitiveType:'AABB',participationRole:'COLLISION',dimensionsMicrounits:[500000,430000,40000],localTransform:{translationMicrounits:[0,685000,-230000],orientation:V.canonicalOrientation}}],aggregateBounds:{minX:-250000,maxX:250000,minY:0,maxY:900000,minZ:-250000,maxZ:250000},phase2Projection:{kind:V.phase2Projection,bounds:{minX:-250000,maxX:250000,minY:0,maxY:900000,minZ:-250000,maxZ:250000}},footprint:{kind:'XZ_RECT_UNION',regions:[{minX:-250000,maxX:250000,minZ:-250000,maxZ:250000}]},contactRegions:[{contactRegionId:'chair-floor-contact',kind:'HORIZONTAL_XZ_RECT',planeY:0,region:{minX:-250000,maxX:250000,minZ:-250000,maxZ:250000}}],supportCategories:[{supportCategoryId:'floor',supportSemanticType:'FLOOR',provenanceStatus:'AUTHORED_NEW',fixtureOnly:false}],geometrySource:{classification:'AUTHORED_NEW',sourceId:decisionId},authoringProvenance:{decisionId,sourceReferenceEvidenceRefs:['https://ewiworks.com/wp-content/uploads/2023/03/Updated-Chair-Standards-Overview.pdf']},priorRevisionDigest:null};
const BODY=A.validateBody(rawBody).definition;
const ENTITY={entityDefinitionId:'school/treatment-chair-entity',entityRevision:1,physicalBodyRef:{id:BODY.bodyDefinitionId,revision:BODY.bodyRevision,digest:BODY.canonicalDigest},transform:{translationMicrounits:[-2000000,0,1000000],orientation:V.canonicalOrientation}};ENTITY.entityDigest=A.digest(ENTITY,'entityDigest');Object.freeze(ENTITY);
const rawSurface={schemaVersion:'1.0.0',supportSurfaceId:'school/treatment-chair-seat',surfaceRevision:1,ownerDefinitionRef:{id:ENTITY.entityDefinitionId,revision:ENTITY.entityRevision,digest:ENTITY.entityDigest},supportSemanticType:'SUPPORT_SURFACE',transformBinding:'OWNER_TRANSLATION_IDENTITY_ORIENTATION',localPlane:{normal:[0,1000000,0],offsetMicrounits:490000},localRegion:{minX:-240000,maxX:240000,minZ:-240000,maxZ:240000},contactRule:{contactRuleId:'full-footprint-chair-seat',policy:'FULL_FOOTPRINT'},provenance:{classification:'AUTHORED_NEW',decisionId}};
const SURFACE=A.validateSupportSurface(rawSurface,ENTITY).definition;
const SURFACE_ENVELOPE=A.transitionEnvelope(A.createDraft({envelopeId:'gate-c-treatment-chair-seat-v1',definitionRef:A.refFor('SUPPORT_SURFACE',SURFACE),limitations:['SEAT_ONLY','IDENTITY_ORIENTATION_TRANSLATION_ONLY','NOT_REVIEWED_FOR_SLICE']}),'VALIDATED',{validationEvidenceRefs:['gate-c-chair-definition-tests']});
const BODY_ENVELOPE=A.transitionEnvelope(A.createDraft({envelopeId:'gate-c-treatment-chair-body-v1',definitionRef:A.refFor('PHYSICAL_BODY',BODY),limitations:['PHYSICAL_ONLY_NO_VISUAL_BINDING','IDENTITY_ORIENTATION_TRANSLATION_ONLY','NOT_REVIEWED_FOR_SLICE']}),'VALIDATED',{validationEvidenceRefs:['gate-c-chair-definition-tests']});
const REVIEW_SCOPE='SCHOOL_VERTICAL_SLICE|TREATMENT_CHAIR_R1|SEAT_SUPPORT_SURFACE_R1|PHYSICAL_SUPPORT_AND_DEPENDENCY_VALIDATION';
const REVIEW={reviewId:'gate-c-user-review-0c27c92',reviewDecision:'APPROVED_FOR_SLICE',reviewScope:REVIEW_SCOPE,reviewEvidenceRefs:['authority:USER_GATE_REVIEW','commit:0c27c92bb10e6af6e7f4e4fcb61a4a9cdc3e6d45','package-sha256:6efc8f2d860e3b88f307390eab11b14f629a975682365dd8c2aab1d3df2e9e37','whatsapp:wamid.HBgMOTcyNTMyNDkwMzUxFQIAEhgUM0FDNEJFREQzQzM5NUY2OTRERkIA','evidence:gate-c-28-of-28','evidence:ast-pass-geometry-call-sites-1']};
function promote(validated){const r={...REVIEW,reviewedDefinitionDigest:validated.definitionRef.definitionDigest,reviewedDefinitionRevision:validated.definitionRef.revision};return A.transitionEnvelope(A.transitionEnvelope(validated,'REVIEWED',r),'VERIFIED_FOR_SLICE',r)}
const BODY_VERIFIED_ENVELOPE=promote(BODY_ENVELOPE),SURFACE_VERIFIED_ENVELOPE=promote(SURFACE_ENVELOPE);
module.exports={BODY,ENTITY,SURFACE,BODY_ENVELOPE,SURFACE_ENVELOPE,BODY_VERIFIED_ENVELOPE,SURFACE_VERIFIED_ENVELOPE,REVIEW_SCOPE,decisionId};
