'use strict';
// Review-only wrapper. Scratch release anchor required, absent means unissued.
// No caller record can install a positive gate. Private runtime never escapes.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {digest,deepFreeze}=require('../../contracts/canonical'),{replay}=require('../../events/replay'),{createMultiSupportRuntime}=require('../../multi-support/runtime');
const C=require('../door-world-genesis/candidate'),S=require('../door-world-structure/candidate'),Q=require('../door-world-direct-gate/candidate');
const root=path.resolve(__dirname,'../../../..');
const unknown=reason=>deepFreeze({status:'UNKNOWN',reason,classification:'THROWAWAY_PREPARATION_ONLY_NOT_ADMITTED'});
function localClosure(){const seen=new Set(),pending=[__filename,path.join(root,'src/clean-runtime/school/door-world-legality/candidate.js'),path.join(root,'src/clean-runtime/school/door-world-readiness/candidate.js')];while(pending.length){const p=pending.pop();if(seen.has(p))continue;seen.add(p);const text=fs.readFileSync(p,'utf8');for(const match of text.matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g)){if(match[1].startsWith('.')){const next=require.resolve(path.resolve(path.dirname(p),match[1]));if(!next.startsWith(root+path.sep))throw Error('LOCAL_REQUIRE_OUTSIDE_ROOT');pending.push(next)}}}return [...seen].sort().map(p=>path.relative(root,p))}
const scratch=path.join(root,'.throwaway-preparation-scratch'),anchorPath=path.join(scratch,'release-anchor.json'),recordPath=path.join(scratch,'issued-record.json'),markerPath=path.join(scratch,'consumed-marker');

function plan(packet){const g=C.prepareGenesis(packet),pkg=require('../../../../scripts/track-b/gate-a-r1v4-package-builder').buildV21(),entity=pkg.entities.find(e=>e.entityId==='school-casualty-adult-v1'),relation=structuredClone(pkg.supportRelations.find(r=>r.supportedEntityId===entity.entityId));relation.surfaceModelRef={id:g.surfaceModel.surfaceModelId,revision:g.surfaceModel.revision,digest:g.surfaceModel.surfaceModelDigest};const tx={transactionId:'reviewed-one-use-adult-closed-preparation-v1',expectedWorldRevision:0,commands:[{commandId:'reviewed:spawn:adult',type:'SpawnEntity',expectedWorldRevision:0,entity},{commandId:'reviewed:support:adult',type:'AttachSupportRelation',expectedWorldRevision:0,relation}]};return {g,tx}}
const observedDataDependencies=['evidence/verified-architecture-phase2/surface-models/school.json','evidence/track-b/scene-camera-candidate/packet-v1_5.json'];
function bindings(packet){const {g,tx}=plan(packet),structural=S.validateStructure(g.surfaceModel);return {packetDigest:digest(packet),modelDigest:g.surfaceModel.surfaceModelDigest,genesisDigest:g.genesis.stateDigest,structuralValidatorVersion:structural.validatorVersion,structuralResultDigest:digest(structural),gateImplementationVersion:'private-one-use-adult-closed-v1',dataDependencies:observedDataDependencies,sourceDigests:Object.fromEntries([...localClosure(),...observedDataDependencies].sort().map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')])),transactionScopeDigest:digest({entityIds:['school-casualty-adult-v1'],expectedWorldRevision:0,transaction:tx}),scope:'THROWAWAY_PREPARATION_ONLY',maximumUses:1,issuer:'TRACK_B_REVIEW_INTERNAL_ARTIFACT_NOT_OWNER_GRANT',limitations:['EXPLICIT_EXACT_SUPPORT_RELATION_ADULT_ONLY_NOT_NEW_CONTACT_REGION_DERIVATION','BAG_UNIT_UNKNOWN_NOT_GENERALIZED','CLOSED_ONLY_NO_CEILING_OR_BODY_VS_OPEN_LEAF_PROOF','NO_ADMISSION_OPERATIONAL_USE_OR_PERSISTENCE']}}
function inspectExpectedBindings({packet,...extra}={}){if(Object.keys(extra).length)return unknown('EXTRA_INPUT');try{return deepFreeze({status:'UNISSUED_BINDING_PLAN_NOT_AUTHORIZATION',...bindings(packet)})}catch{return unknown('BINDING_PLAN_INVALID')}}
// Fixed-path scratch anchor is review-issued; absent or malformed fails closed.
function readIssuedAnchor(){try{const a=JSON.parse(fs.readFileSync(anchorPath));if(Object.keys(a).length!==1||!/^[a-f0-9]{64}$/.test(a.recordDigest))return null;return a.recordDigest}catch{return null}}
let used=false;
function runThrowawayPreparation({packet,...extra}={}){if(Object.keys(extra).length)return unknown('CALLER_RECORD_OR_EXTRA_INPUT_FORBIDDEN');if(used||fs.existsSync(markerPath))return unknown('SINGLE_USE_EXHAUSTED');const issuedRecordAnchor=readIssuedAnchor();if(!issuedRecordAnchor)return unknown('REVIEWED_PREPARATION_RECORD_NOT_ISSUED');let api=null,port=null;try{
 const record=JSON.parse(fs.readFileSync(recordPath)),expected=bindings(packet);if(digest(record)!==issuedRecordAnchor)return unknown('REVIEWED_RECORD_ANCHOR_MISMATCH');for(const [k,v] of Object.entries(expected))if(digest(record[k])!==digest(v))return unknown('BOUND_DIGEST_OR_SCOPE_CHANGED');
 const {g,tx}=plan(packet);if(S.validateStructure(g.surfaceModel).status!=='DOORWAY_FLOOR_STATIC_TOPOLOGY_VALIDATED_NOT_ADMITTED')return unknown('STRUCTURE_NOT_VALID');try{fs.writeFileSync(markerPath,record.recordDigest||issuedRecordAnchor,{flag:'wx'})}catch(e){return unknown(e.code==='EEXIST'?'SINGLE_USE_EXHAUSTED':'CONSUMED_MARKER_WRITE_FAILED')}used=true;let active=true;
 port=Object.freeze({evaluate(input){if(!active||input.worldState.stateDigest!==g.genesis.stateDigest||input.command.entityId!=='school-casualty-adult-v1'||digest(input.proposedState.entities)!==digest({[tx.commands[0].entity.entityId]:tx.commands[0].entity})||digest(input.proposedState.supportRelations)!==digest([tx.commands[1].relation]))return {outcome:'UNKNOWN'};const r=Q.inspectDirectQuery({packet,model:g.surfaceModel,proposedState:input.proposedState,entityId:input.command.entityId});return {outcome:r.outcome==='DIRECT_QUERY_CLEAR_NOT_ADMITTED'?'PASS':'UNKNOWN'}}});
 api=createMultiSupportRuntime({initialWorld:g.genesis,legalityPort:port});const result=api.proposeTransaction(tx),events=api.getEventLog(),state=api.getWorldState(),replayed=replay(g.genesis,events);active=false;if(result.status!=='COMMITTED'||events.length!==1||state.revision!==1||state.stateDigest!==replayed.stateDigest||digest(state.environmentPhysicalState)!==digest(g.genesis.environmentPhysicalState))return deepFreeze({...unknown('THROWAWAY_COMMIT_REPLAY_CHECK_FAILED'),diagnostic:result.code||'COMMIT_COUNTS_REPLAY_OR_ENVIRONMENT_MISMATCH',eventCount:events.length});
 return deepFreeze({status:'THROWAWAY_REPLAY_SUMMARY_NOT_ADMITTED',entityCount:Object.keys(state.entities).length,supportCount:state.supportRelations.length,eventCount:events.length,worldDigest:state.stateDigest,eventHeadDigest:events[0].eventDigest,transactionDigest:digest(tx),operationalStatus:'UNKNOWN'});
 }catch(e){return deepFreeze({...unknown('THROWAWAY_PREPARATION_FAILED'),diagnostic:e.code||e.message})}finally{api=null;port=null}}
module.exports={inspectExpectedBindings,runThrowawayPreparation};
