'use strict';const A=require('../../authoring'),{digest,deepFreeze}=require('../../contracts/canonical'),{validatePacket}=require('../scene-camera-geometry'),{inspectSceneExtensionAdmission}=require('../scene-extension-admission-evidence'),{sourcePins,exactPins}=require('./pins'),Sweep=require('./sweep-verifier'),Review=require('./review-verifier');const TYPE='SCENE_EXTENSION';
function definition(packet,effectScope='EVIDENCE_ONLY_CAMERA_COVERAGE',extensionRevision=1){if(!Number.isInteger(extensionRevision)||extensionRevision<1)throw Error('EXTENSION_REVISION_INVALID');if(!Review.EFFECTS.includes(effectScope))throw Error('UNKNOWN_EFFECT_SCOPE');const d={extensionId:packet.extension.extensionId,extensionRevision,packetDigest:digest(packet),worldDigest:packet.extension.worldDigest,effectScope,evaluatorId:'CANDIDATE_VOLUME_EVALUATOR@1.0.0',sourcePins:sourcePins(),sweepEvidence:Sweep.wrapper(packet),limitations:['NO_OPERATIONAL_ACTIVATION','NO_A8_MESH_ADMISSION','NO_B7_GAMEPLAY_MODE','NO_CLINICAL_OR_R1_CHANGE']};d.canonicalDigest=A.digest(d);return deepFreeze(d)}
function inspectCandidate({packet,definition:d,envelope,reviewRecord,...extra}){const fail=reason=>deepFreeze({status:'UNKNOWN',reason});try{if(Object.keys(extra).length)return fail('CALLER_VERIFIER_OR_EXTRA_INPUT_FORBIDDEN');if(d.effectScope!=='EVIDENCE_ONLY_CAMERA_COVERAGE')return fail('OPERATIONAL_INTEGRATION_NOT_IMPLEMENTED');if(d.evaluatorId!=='CANDIDATE_VOLUME_EVALUATOR@1.0.0'||!exactPins(d.sourcePins)||d.canonicalDigest!==A.digest(d)||digest(d)!==digest(definition(packet,d.effectScope,d.extensionRevision)))return fail('SOURCE_OR_DEFINITION_PINS_STALE');const v=A.validateEnvelope(envelope,{expectedRef:A.refFor(TYPE,d),requiredScope:Review.SCOPE});if(v.status!=='VALIDATED'||v.envelope.lifecycleState!=='VERIFIED_FOR_SLICE')return fail('ENVELOPE_NOT_VERIFIED');if(!Review.verifyReviewRecord({packet,reviewRecord})||reviewRecord.effectScope!==d.effectScope||envelope.ownerDecisionQuestionRef!==reviewRecord.ownerQuestionRef||envelope.ownerDecisionMessageRef!==reviewRecord.ownerMessageRef||envelope.reviewId!==reviewRecord.reviewId||!envelope.reviewEvidenceRefs.includes('review-record-sha256:'+reviewRecord.reviewRecordDigest))return fail('EXACT_OWNER_REVIEW_REQUIRED');const r=inspectSceneExtensionAdmission({packet,sweepEvidence:d.sweepEvidence,verifySweepEvidence:Sweep.verifySweepEvidence,reviewRecord,verifyReviewRecord:Review.verifyReviewRecord});if(r.status!=='EVIDENCE_COMPLETE_NOT_ADMITTED')return fail('EVIDENCE_INCOMPLETE');return deepFreeze({status:'PREPARED_NOT_ADMITTED',reason:'EXECUTION_REQUIRES_OWNER_APPROVED_RECORD',evidence:r})}catch{return fail('ADMISSION_INPUT_INVALID')}}
// Explicit immutable history, held by the registry instance. No module-load
// activation. Proposed API only; not called for real candidate admission.
function createRegistry(){const history=[];const key=input=>input.definition.extensionId+'@'+input.definition.extensionRevision;
function latest(k){return [...history].reverse().find(r=>r.key===k)}
function inspect(input){const state=latest(key(input));if(state&&['REJECTED','DEFERRED','REVOKED','SUPERSEDED'].includes(state.decision))return deepFreeze({status:'UNKNOWN',reason:'RECORD_INERT_OR_REVOKED'});if(state&&state.definitionDigest!==input.definition.canonicalDigest)return deepFreeze({status:'UNKNOWN',reason:'IMMUTABLE_REVISION_CONFLICT'});return inspectCandidate(input)}
return Object.freeze({inspect,execute(input){const ready=inspect(input);if(ready.status!=='PREPARED_NOT_ADMITTED')return ready;const k=key(input),existing=latest(k);if(existing)return existing;
// Private exact executor result. Generic A.admit deliberately rejects this
// type; this path is reachable only after imported mandatory verifiers pass.
const admission=deepFreeze({status:'ADMITTED',definition:input.definition,envelope:input.envelope});const entry=deepFreeze({key:k,decision:'ADMITTED',definitionDigest:input.definition.canonicalDigest,admission,effectScope:input.definition.effectScope});history.push(entry);return entry},
recordInert({extensionId,extensionRevision=1,decision,decisionMessageRef,decisionQuestionRef,expectedDefinitionDigest}){if(!Number.isInteger(extensionRevision)||extensionRevision<1||!['DEFERRED','REJECTED','REVOKED','SUPERSEDED'].includes(decision)||!decisionMessageRef||!decisionQuestionRef||!expectedDefinitionDigest)throw Error('INERT_DECISION_INVALID');const k=extensionId+'@'+extensionRevision,old=latest(k);if(old&&old.definitionDigest!==expectedDefinitionDigest)throw Error('DECISION_PIN_MISMATCH');const active=[...history].reverse().find(r=>r.key===k&&r.admission);const superseded=old?.superseded||(active?A.supersede({activeEnvelope:active.admission.envelope,supersedingEnvelopeId:k+':'+decision,evidenceRefs:[decisionMessageRef,decisionQuestionRef]}):null);const entry=deepFreeze({key:k,decision,definitionDigest:expectedDefinitionDigest,decisionMessageRef,decisionQuestionRef,superseded,priorDecisionIndex:old?history.indexOf(old):null});history.push(entry);return entry},snapshot(){return deepFreeze([...history])}})}
module.exports={TYPE,definition,inspectCandidate,createRegistry};
