from pathlib import Path
import hashlib
R=Path(__file__).parent;s=(R/'composed-measured-service.review-bytes').read_text();root=R/'rootfs';b=(root/'approved-service/measured-execution-service-closure.v1.bin').read_bytes();n=0
for l in b.splitlines():p,r,z,d=l.split(b'\0');q=root/p.decode().lstrip('/');assert q.stat().st_size==int(z) and hashlib.sha256(q.read_bytes()).hexdigest()==d.decode();n+=1
assert n==44
for token in ['seal pin-record','seal cross-binding','seal offline-input-manifest',"-printf '%f\\0'",'/usr/bin/sort -z','E_INPUT_EXACT_SET','exec {input_fd}<"$p"','/proc/self/fd/$input_fd','E_HASH_OUTPUT','trap cleanup EXIT','cleanup_signal(){ cleanup_signal_code=$1; }','Tri-state probe','findmnt -rn -o TARGET','return 2','E_STAGE_CLEANUP_QUERY_UNPROVEN','E_STAGE_CLEANUP_UNOWNED_MOUNT','parse_object(){','case "$value" in *:*:*)','case "$dev" in 0|[1-9]*)','case "$ino" in 0|[1-9]*)','created_object=$(parse_object "$raw_object")','E_STAGE_OWNERSHIP_ACQUISITION_RESIDUE','E_STAGE_CLEANUP_OWNERSHIP_UNPROVEN','E_STAGE_CLEANUP_OBJECT_CHANGED','latch_traps;/usr/bin/mkdir','latch_traps;/usr/bin/mount','while [ "$attempt" -lt 3 ]','E_STAGE_CLEANUP_MOUNT_RESIDUE','E_STAGE_CLEANUP_PATH_RESIDUE','/usr/bin/mount -t tmpfs','/usr/bin/cat "$src" >"$dst"','E_STAGE_DIGEST','remount,ro,bind','/usr/bin/umount -- "$stage"','/usr/bin/rm -rf -- "$stage"','E_SUCCESSOR','success=1','E_SUCCESS_COMMIT_MISSING','replay is intentionally rejected as already complete','--kill-child --net','"$LAUNCHER_FD"','! -e "$OUTPUT.stage"','! -e "$SERVICE_STAGE"','fail E_CANDIDATE_AUTHORITY']:assert token in s,token
assert s.index('/usr/bin/find "$INPUT"')<s.index('exec {input_fd}')<s.index('fail E_CANDIDATE_AUTHORITY')<s.index('/usr/bin/unshare')<s.index('trap cleanup EXIT')<s.index('latch_traps;/usr/bin/mkdir -m 700')<s.index('/usr/bin/mount -t tmpfs')<s.index('"$launcher" "$root" "$stage"')
assert hashlib.sha256((root/'usr/bin/mount').read_bytes()).hexdigest()=='bad230d68e012eb1a2fcaa3b42688d912940f5c61f041ae9451eee7dfb858ff1'
assert hashlib.sha256((root/'usr/bin/umount').read_bytes()).hexdigest()=='80e84907e5cb4248255c3985e2f7ed55d14fbd45d344a599fdb5cac314b9473c'
print('COMPOSED_SERVICE_STATIC_REVIEW=PASS')
