'use strict';
const FAILURE_CODES=Object.freeze(['INVALID_ENTITY','INVALID_WORLD_REVISION','INVALID_SURFACE','INVALID_PHYSICAL_BODY','INVALID_COMMAND','GEOMETRY_PROOF_FAILED','STALE_GEOMETRY','STALE_SURFACE_MODEL','ILLEGAL_REPARENT','ILLEGAL_SUPPORT_RELATION','TRANSACTION_REJECTED','PHYSICAL_BYPASS_ATTEMPT','VISUAL_SYNC_FAILURE','EVENT_LOG_FAILURE','REPLAY_MISMATCH','PERSISTENCE_INVALID','UNSUPPORTED_SCENE','UNKNOWN']);
const failure=(code,evidence={})=>{if(!FAILURE_CODES.includes(code))throw new TypeError('INVALID_FAILURE_CODE');return Object.freeze({code,evidence:Object.freeze(structuredClone(evidence))})};
module.exports={FAILURE_CODES,failure};
