'use strict';const test=require('node:test'),assert=require('node:assert/strict'),A=require('../../src/clean-runtime/authoring'),F=require('./fixtures/synthetic');
test('valid synthetic support entity and horizontal surface materialize deterministically',()=>{const b=F.validatedBody(),o=A.validateSupportEntity(F.owner(b),b).definition,s=A.validateSupportSurface(F.surface(o),o).definition,a=A.materializeSupportSurface({staticModelRef:{id:'synthetic-static',revision:1,digest:'a'.repeat(64)},owner:o,surface:s}),z=A.materializeSupportSurface({staticModelRef:{digest:'a'.repeat(64),revision:1,id:'synthetic-static'},surface:s,owner:o});assert.deepEqual(a,z);assert.equal(a.type,'SUPPORT_SURFACE');assert.deepEqual(a.region.allowed[0],{regionId:'synthetic/seat:world',minX:.0009,maxX:.0011,minZ:.0028,maxZ:.0032});assert.equal(a.planeOrDepth.planeY,.0021)});
test('rotated support rejects',()=>{const b=F.validatedBody(),x=F.owner(b);x.transform.orientation=[0,1,0,999999];assert.equal(A.validateSupportEntity(x,b).failure.code,'UNSUPPORTED_V1_CAPABILITY')});
test('non-horizontal support rejects',()=>{const b=F.validatedBody(),o=A.validateSupportEntity(F.owner(b),b).definition,x=F.surface(o);x.localPlane.normal=[1,0,0];assert.equal(A.validateSupportSurface(x,o).failure.code,'INVALID_SUPPORT_SURFACE')});
test('stale owner/body references reject',()=>{const b=F.validatedBody(),x=F.owner(b);x.physicalBodyRef.revision=2;assert.equal(A.validateSupportEntity(x,b).failure.code,'STALE_BODY_REVISION');const o=A.validateSupportEntity(F.owner(b),b).definition,s=F.surface(o);s.ownerDefinitionRef.revision=2;assert.equal(A.validateSupportSurface(s,o).failure.code,'INVALID_SUPPORT_REFERENCE')});

test('legacy embedded lifecycle transition is disabled to leave envelope as sole truth',()=>{const b=F.validatedBody();assert.throws(()=>A.transition(b,'VALIDATED',{}),x=>x.code==='DEPRECATED_USE_LIFECYCLE_ENVELOPE');assert.equal(A.canVerify(b,{}),false)});
test('legacy embedded review record is disabled to leave envelope as sole truth',()=>{assert.throws(()=>A.reviewRecord({}),x=>x.code==='DEPRECATED_USE_LIFECYCLE_ENVELOPE')});
test('validator cannot accept pre-claimed VERIFIED status',()=>{const x=F.body();x.status='VERIFIED_FOR_SLICE';assert.equal(A.validateBody(x).failure.code,'INVALID_STATUS')});
