'use strict';const {digest,canonical}=require('./canonical'),{toMicrounits:q}=require('./fixed-point');
const VERSION='2.0.0',ROLE=new Set(['FEET','PELVIS','TORSO','BACK','LEGS','HEAD','KNEES','HANDS','FULL_BODY','GENERIC']);
const fail=(code,stage,e={})=>Object.freeze({placementReady:false,result:'FAIL',reasonCode:code,evidence:Object.freeze({version:VERSION,stage,...e})});
const worldBox=(g,t)=>({minX:g.minX+t.x,maxX:g.maxX+t.x,minY:g.minY+t.y,maxY:g.maxY+t.y,minZ:g.minZ+t.z,maxZ:g.maxZ+t.z});
const disjoint=(a,b)=>q(a.maxX)<=q(b.minX)||q(a.minX)>=q(b.maxX)||q(a.maxY)<=q(b.minY)||q(a.minY)>=q(b.maxY)||q(a.maxZ)<=q(b.minZ)||q(a.minZ)>=q(b.maxZ);
const insideXZ=(a,r)=>q(a.minX)>=q(r.minX)&&q(a.maxX)<=q(r.maxX)&&q(a.minZ)>=q(r.minZ)&&q(a.maxZ)<=q(r.maxZ);
const sorted=(a)=>[...a].sort((x,y)=>x.relationId.localeCompare(y.relationId));
function requestDigest(x){const y=structuredClone(x);delete y.requestDigest;if(Array.isArray(y.contacts))y.contacts=sorted(y.contacts);return digest(y)}
function evaluateV2(req,model){
 if(!req||req.version!==VERSION||!req.requestId||!req.body||!Array.isArray(req.contacts)||typeof req.requiresContacts!=='boolean')return fail('V2_SCHEMA_OR_VERSION','SCHEMA');
 if(req.requestDigest!==requestDigest(req))return fail('V2_REQUEST_DIGEST_MISMATCH','IDENTITY');
 const b=req.body;if(!b.id||!Number.isInteger(b.revision)||b.revision<1||!b.digest||!b.geometry||digest(b.geometry)!==b.geometryDigest||b.proofGeometryDigest!==b.geometryDigest||!Array.isArray(b.contactRegions)||!b.evidenceRefs?.length)return fail('V2_BODY_IDENTITY_OR_EVIDENCE','IDENTITY');
 if(!model||req.surfaceModelRef?.id!==model.surfaceModelId||req.surfaceModelRef?.revision!==model.revision||req.surfaceModelRef?.digest!==model.surfaceModelDigest)return fail('V2_SURFACE_MODEL_STALE_OR_MISSING','IDENTITY');
 if(req.requiresContacts&&!req.contacts.length)return fail('V2_REQUIRED_CONTACT_MISSING','SCHEMA');
 const contacts=sorted(req.contacts);if(new Set(contacts.map(x=>x.relationId)).size!==contacts.length)return fail('V2_DUPLICATE_RELATION_ID','CONFLICT');
 const regions=new Map(b.contactRegions.map(x=>[x.contactRegionId,x]));if(regions.size!==b.contactRegions.length)return fail('V2_DUPLICATE_CONTACT_REGION','BODY');
 for(const c of contacts){if(!c.relationId||c.requirement!=='REQUIRED'||!ROLE.has(c.contactRole)||c.supportedBodyRef?.id!==b.id||c.supportedBodyRef?.revision!==b.revision||c.supportedBodyRef?.digest!==b.digest)return fail('V2_CONTACT_IDENTITY_INVALID','IDENTITY',{relationId:c.relationId||null});const r=regions.get(c.contactRegionRef?.contactRegionId);if(!r||c.contactRegionRef.bodyId!==b.id||c.contactRegionRef.bodyRevision!==b.revision||c.contactRegionRef.bodyDigest!==b.digest)return fail('V2_CONTACT_REGION_MISSING_OR_STALE','BODY',{relationId:c.relationId});if(c.contactRegionDigest!==digest(r)||canonical(c.contactRegionGeometry)!==canonical(r.geometry))return fail('V2_CONTACT_REGION_DIGEST_MISMATCH','BODY',{relationId:c.relationId});if(c.surfaceModelRef?.id!==model.surfaceModelId||c.surfaceModelRef?.revision!==model.revision||c.surfaceModelRef?.digest!==model.surfaceModelDigest)return fail('V2_CONTACT_SURFACE_MODEL_STALE','IDENTITY',{relationId:c.relationId});if(!c.evidenceRefs?.length)return fail('V2_CONTACT_EVIDENCE_MISSING','IDENTITY',{relationId:c.relationId})}
 const whole=worldBox(b.geometry,req.transform);const floor=model.surfaces.find(x=>x.type==='FLOOR'&&x.region?.allowed?.some(r=>insideXZ(whole,r)));if(!floor)return fail('V2_BODY_OUTSIDE_LEGAL_WORLD','GLOBAL',{bounds:whole});for(const s of [...model.surfaces].sort((a,b)=>a.surfaceId.localeCompare(b.surfaceId)))if(['WALL','DOOR_OR_OPENING','OBSTACLE'].includes(s.type))for(const v of s.region?.volumes||[])if(!disjoint(whole,v))return fail(s.type==='WALL'?'V2_GLOBAL_WALL_PENETRATION':s.type==='DOOR_OR_OPENING'?'V2_GLOBAL_DOOR_PENETRATION':'V2_GLOBAL_OBSTACLE_PENETRATION','GLOBAL',{bounds:whole,surfaceId:s.surfaceId,volumeId:v.volumeId});
 const per=[];for(const c of contacts){const r=regions.get(c.contactRegionRef.contactRegionId),g=worldBox(r.geometry,req.transform),s=model.surfaces.find(x=>x.surfaceId===c.surfaceId);if(!s)return fail('V2_CONTACT_SURFACE_MISSING','SEMANTIC',{relationId:c.relationId,completed:per});if(s.type!==c.expectedSurfaceType)return fail('V2_CONTACT_SURFACE_TYPE_MISMATCH','SEMANTIC',{relationId:c.relationId,completed:per});const cap=(s.contactCapabilities||[]).find(x=>x.capabilityId===c.capabilityId&&x.kind==='SUPPORT_CONTACT');if(!cap)return fail('V2_SUPPORT_CAPABILITY_MISSING','SEMANTIC',{relationId:c.relationId,completed:per});const p=s.contactPlane;if(!p||!['X','Y','Z'].includes(p.axis)||![-1,1].includes(p.normalSign)||p.coordinate===undefined)return fail('V2_AXIS_ALIGNED_PLANE_UNSUPPORTED','SEMANTIC',{relationId:c.relationId,completed:per});const expected={x:p.axis==='X'?p.normalSign:0,y:p.axis==='Y'?p.normalSign:0,z:p.axis==='Z'?p.normalSign:0};if(c.contactNormal.x!==expected.x||c.contactNormal.y!==expected.y||c.contactNormal.z!==expected.z)return fail('V2_CONTACT_NORMAL_MISMATCH','SEMANTIC',{relationId:c.relationId,completed:per});const edge=p.axis==='X'?(p.normalSign>0?g.minX:g.maxX):p.axis==='Y'?(p.normalSign>0?g.minY:g.maxY):(p.normalSign>0?g.minZ:g.maxZ),delta=q(edge)-q(p.coordinate);if(delta!==0)return fail(delta*p.normalSign>0?'V2_CONTACT_FLOATING':'V2_CONTACT_EXCESSIVE_PENETRATION','CONTACT',{relationId:c.relationId,deltaMicrounits:delta,completed:per});const allowed=(s.region.allowed||[]).some(a=>p.axis==='Y'?insideXZ(g,a):p.axis==='X'?(q(g.minY)>=q(a.minY)&&q(g.maxY)<=q(a.maxY)&&q(g.minZ)>=q(a.minZ)&&q(g.maxZ)<=q(a.maxZ)):(q(g.minX)>=q(a.minX)&&q(g.maxX)<=q(a.maxX)&&q(g.minY)>=q(a.minY)&&q(g.maxY)<=q(a.maxY)));if(!allowed)return fail('V2_CONTACT_OUTSIDE_SURFACE_REGION','CONTACT',{relationId:c.relationId,completed:per});per.push(Object.freeze({relationId:c.relationId,result:'PASS',contactRegionRef:c.contactRegionRef,surfaceRef:{surfaceId:s.surfaceId,type:s.type,capabilityId:cap.capabilityId},plane:p,worldContactBounds:g,deltaMicrounits:0}))}
 const ev={version:VERSION,requestId:req.requestId,requestDigest:req.requestDigest,bodyRef:{id:b.id,revision:b.revision,digest:b.digest},global:{result:'PASS',bounds:whole,fullBodyCollisionEvaluated:true,legalWorldContainmentEvaluated:true},contacts:per,canonicalRelationIds:contacts.map(x=>x.relationId)};return Object.freeze({placementReady:false,result:'PASS',reasonCode:'V2_PASS',evidence:Object.freeze(ev),proofDigest:digest(ev)})}
function verifyV2Result(x){return !!x&&x.evidence?.version===VERSION&&x.proofDigest===digest(x.evidence)}module.exports={VERSION,evaluateV2,requestDigest,verifyV2Result};
