'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {system,spawn,body}=require('./helpers');
test('spawn commits immutable revision and event',()=>{const {api}=system(),before=api.getWorldState(),r=api.proposeMutation(spawn());assert.equal(r.status,'COMMITTED');assert.equal(r.state.revision,1);assert(r.state.entities.e1);assert.equal(api.getEventLog().length,1);assert.equal(before.revision,0)});
for(const outcome of ['FAIL','UNKNOWN'])test('legality '+outcome+' cannot commit',()=>{const {api}=system(outcome),before=api.getWorldState(),r=api.proposeMutation(spawn());assert.equal(r.status,'REJECTED');assert.equal(api.getWorldState().stateDigest,before.stateDigest);assert.equal(r.failure.code,'TRANSACTION_REJECTED')});
test('invalid command and stale revision reject',()=>{const {api}=system();assert.equal(api.proposeMutation({commandId:'x',type:'BOGUS',expectedWorldRevision:0}).failure.code,'INVALID_COMMAND');api.proposeMutation(spawn());assert.equal(api.proposeMutation({...spawn(0,'c2','e2')}).failure.code,'INVALID_WORLD_REVISION')});
test('invalid entity rejects atomically',()=>{const {api}=system(),b=api.getWorldState();const r=api.proposeMutation({commandId:'x',type:'SetTransform',expectedWorldRevision:0,entityId:'missing',transform:{}});assert.equal(r.status,'REJECTED');assert.equal(api.getWorldState().stateDigest,b.stateDigest)});
test('multi-command one failure rejects all',()=>{const {api}=system(),before=api.getWorldState();const r=api.proposeTransaction({transactionId:'t',expectedWorldRevision:0,commands:[spawn(0,'a','a'),{commandId:'b',type:'SetTransform',expectedWorldRevision:0,entityId:'missing',transform:{}}]});assert.equal(r.status,'REJECTED');assert.equal(api.getWorldState().stateDigest,before.stateDigest);assert.equal(Object.keys(api.getWorldState().entities).length,0)});
test('duplicate command identity rejects',()=>{const {api}=system();api.proposeMutation(spawn());const r=api.proposeMutation({...spawn(1),entity:body('e2')});assert.equal(r.status,'REJECTED');assert.equal(r.failure.code,'INVALID_COMMAND')});
test('legality validates the proposed candidate rather than pre-command state',()=>{let observed=false;const eventLog=new (require('./helpers').EventLog)(),runtime=require('./helpers').createAuthorityRuntime({initialWorld:require('./helpers').initial(),eventLog,legalityPort:require('./helpers').testDouble(x=>{observed=!!x.proposedState.entities.e1;return {outcome:'PASS'}})});runtime.worldMutationAPI.proposeMutation(spawn());assert.equal(observed,true)});
test('transaction rejects command with mismatched expected revision atomically',()=>{const {api}=system(),before=api.getWorldState();const r=api.proposeTransaction({transactionId:'rev-mismatch',expectedWorldRevision:0,commands:[spawn(1,'a','a')]});assert.equal(r.status,'REJECTED');assert.equal(r.failure.evidence.cause,'INVALID_WORLD_REVISION');assert.equal(api.getWorldState().stateDigest,before.stateDigest)});
