'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {route}=require('../../src/clean-runtime/mutation/physical-capability-router');
const {createAuthorityEnvelope}=require('../../src/clean-runtime/mutation/v3-authority-envelope');
const {plan}=require('../../src/clean-runtime/mutation/physical-proof-planner');
const {mapResult,createV3AuthorityAdapter}=require('../../src/clean-runtime/mutation/v3-authority-adapter');
const envelope=()=>createAuthorityEnvelope({definitions:{x:{}},frames:{f:{}},bodies:{b:{}},supportRelations:{r:{}},boundaryFeatures:{w:{}},authoritativeGeometryFrameRefs:{x:{}}});
function req(q,id='r'){return {apiVersion:'3.0.0',requestId:id,queryType:q}}
test('router promotes only closed support containment opening slice',()=>{for(const q of ['CONTACT_REGION_VS_SUPPORT_SURFACE','BODY_CONTAINMENT_IN_ALLOWED_REGION','BODY_VS_OPENING_BOUNDARY'])assert.equal(route(q).status,'ROUTED');for(const q of ['BODY_VS_BODY','BODY_VS_WORLD_SOLID','BODY_VS_OBSTACLE','NO_SUCH_QUERY'])assert.equal(route(q).status,'UNKNOWN')});
test('INVALID can never become PASS and preserves V3 evidence identity',()=>{const r=mapResult({status:'INVALID',reason:'STALE_EVIDENCE',evidenceDigest:'d',evidence:{hostile:true}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.evidence.v3Status,'INVALID');assert.equal(r.evidence.v3Reason,'STALE_EVIDENCE');assert.equal(r.evidence.v3EvidenceDigest,'d')});
test('UNKNOWN ambiguity and definite FAIL stay non-committing outcomes',()=>{assert.equal(mapResult({status:'UNKNOWN',reason:'QUANTIZATION_AMBIGUITY'}).outcome,'UNKNOWN');assert.equal(mapResult({status:'FAIL',reason:'CONTACT_FLOATING'}).outcome,'FAIL')});
test('authority envelope is deeply immutable and forbids self-derived pins',()=>{const e=envelope();assert.equal(e.selfDerivedPinsAllowed,false);assert(Object.isFrozen(e));assert(Object.isFrozen(e.definitions));assert.throws(()=>{e.definitions.x=1})});
test('proof planner is deterministic under command order',()=>{const a={transaction:{commands:[{commandId:'2',entityId:'b'},{commandId:'1',entityId:'a'}]},requirementsByEntity:{a:[{queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',request:req('BODY_CONTAINMENT_IN_ALLOWED_REGION','a')}],b:[{queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',request:req('CONTACT_REGION_VS_SUPPORT_SURFACE','b')}]}};const b={...a,transaction:{commands:[...a.transaction.commands].reverse()}};assert.deepEqual(plan(a),plan(b));assert.deepEqual(plan(a).impactedEntityIds,['a','b'])});
test('empty proof plan rejects closed',()=>{const p=createV3AuthorityAdapter({evaluateV3:()=>({status:'PASS',reason:'VALID'}),authorityEnvelope:envelope(),proofPlanner:()=>({proofs:[]})});assert.equal(p.evaluate({}).outcome,'UNKNOWN')});
test('non-promoted BODY_VS_BODY cannot reach evaluator',()=>{let calls=0;const p=createV3AuthorityAdapter({evaluateV3:()=>{calls++;return {status:'PASS',reason:'VALID'}},authorityEnvelope:envelope(),proofPlanner:()=>({proofs:[{queryType:'BODY_VS_BODY',request:req('BODY_VS_BODY')}]})});const r=p.evaluate({});assert.equal(r.outcome,'UNKNOWN');assert.equal(calls,0)});
test('one non-PASS proof rejects aggregate after prior PASS',()=>{let n=0;const p=createV3AuthorityAdapter({evaluateV3:()=>++n===1?{status:'PASS',reason:'VALID',evidenceDigest:'1'}:{status:'INVALID',reason:'STALE_EVIDENCE',evidenceDigest:'2'},authorityEnvelope:envelope(),proofPlanner:()=>({proofs:[{queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',request:req('CONTACT_REGION_VS_SUPPORT_SURFACE','1')},{queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',request:req('BODY_CONTAINMENT_IN_ALLOWED_REGION','2')}]})});const r=p.evaluate({});assert.equal(r.outcome,'UNKNOWN');assert.equal(n,2);assert.equal(r.evidence.results.length,2)});
test('all required promoted proofs PASS only then adapter PASSes',()=>{let n=0;const p=createV3AuthorityAdapter({evaluateV3:()=>{n++;return {status:'PASS',reason:'VALID',evidenceDigest:String(n)}},authorityEnvelope:envelope(),proofPlanner:()=>({proofs:[{queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',request:req('CONTACT_REGION_VS_SUPPORT_SURFACE')},{queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',request:req('BODY_CONTAINMENT_IN_ALLOWED_REGION')},{queryType:'BODY_VS_OPENING_BOUNDARY',request:req('BODY_VS_OPENING_BOUNDARY')}]})});assert.equal(p.evaluate({}).outcome,'PASS');assert.equal(n,3)});
