'use strict';
// Candidate 5 resubmission: normative behavioral regressions exercised through
// the COMPLETE Foundation path (registry -> envelope -> plan -> route ->
// context -> adapter -> evaluator -> decision aggregation). Every row asserts
// behavior plus fail-closed/result/evaluator/commit evidence on the sealed
// Foundation decision record.
const test=require('node:test'),assert=require('node:assert/strict'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const {digest}=require('../../src/clean-runtime/contracts/canonical'),G=require('../../src/numeric-frame-rotation/graph'),D=require('../../src/verified-architecture-phase2-v3/definitions'),C=require('../../src/verified-architecture-phase2-v3/closure-records'),Foundation=require('../../src/clean-runtime/mutation/v3-promotion-foundation');
const rf=f=>({frameId:f.frameId,revision:f.revision,digest:f.digest}),rb=b=>({bodyId:b.bodyId,revision:b.revision,digest:b.digest}),rc=c=>({contactRegionId:c.contactRegionId,revision:c.revision,digest:c.digest}),rg=(g,f)=>({geometryId:g.geometryId,revision:g.revision,digest:g.digest,localFrameRef:rf(f)}),qi=['1','0','0','0'];
function F(id,p=null,t=['0','0','0']){return G.sealFrame({frameId:id,frameKind:p?'ENTITY_LOCAL':'WORLD',parentFrameRef:p?rf(p):null,translationMicrounits:t,rotationQuaternionRatio:qi,revision:1,provenance:'FOUNDATION_MATRIX'})}
function region(id,f,y,extent,support){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:[[String(-extent),String(y),String(-extent)],[String(extent),String(y),String(-extent)],[String(extent),String(y),String(extent)],[-extent,y,extent].map(String)],normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:support?['SUPPORT']:[],limitations:[]})}
function box(id,f,h=['5','5','5']){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'ORIENTED_BOX',shape:{halfExtentsMicrounits:h},capabilities:[],limitations:[]})}
function opening(id,f,bfId){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'OPENING_REGION',shape:{vertices:[['-50','-50','0'],['50','-50','0'],['50','50','0'],['-50','50','0']],normal:['0','0','1'],sidedness:'FRONT_ONLY',localFrameRef:rf(f),boundaryFeatureRef:{boundaryFeatureId:bfId,revision:1}},capabilities:[],limitations:[]})}
function body(id){const x={bodyId:id,revision:1,provenance:'FOUNDATION_MATRIX',limitations:[]};x.digest=D.digest(x,'digest');return Object.freeze(x)}
function sealRegistry(r){const x={...r,registrySnapshotDigest:undefined};return {...r,registrySnapshotDigest:digest(x)}}
// Combined registry/world fixture: support (offset-plane parametrized) +
// containment + opening assignments on one entity, so aggregation behavior is
// exercised on a single Foundation decision.
function fixture(o={}){const {contactY=10,containment=null,openingMode=null,compound=false,locked=false,mutateRegistry=null,mutateAssignment=null,extraValidUnrelated=false,corruptUnrelated=false,malformedContact=false}=o;
 const w=F('w-mx'),cf=F('c-mx',w),sf=F('s-mx',w),bf=F('b-mx',w,containment==='FAIL'?['100','0','0']:['0','0','0']),tf=F('t-mx',w),of=F('o-mx',w),obf=F('ob-mx',w,openingMode==='AMBIGUITY'?['45','0','0']:['0','0','0']);
 const defs={},frames={[w.frameId]:w,[cf.frameId]:cf,[sf.frameId]:sf},bodies={},contacts={},relations={},bounds={};
 const cg=region('cg-mx',cf,malformedContact?10:contactY,2,false),sg=region('sg-mx',sf,10,20,true);
 if(malformedContact){const bad={geometryId:'cg-mx',schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:cf.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:null,normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:[],limitations:[]};bad.digest=D.digest(bad,'digest');defs['cg-mx']=Object.freeze(bad)}else defs[cg.geometryId]=cg;
 defs[sg.geometryId]=sg;
 const b=body('b-mx');bodies[b.bodyId]=b;
 const cr=C.contactRegion({contactRegionId:'cr-mx',revision:1,supportedBodyRef:rb(b),geometryRef:rg(defs['cg-mx'],cf),expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:rf(w),components:['0','-1','0']},provenance:'FOUNDATION_MATRIX',limitations:[]});contacts[cr.contactRegionId]=cr;
 let sr={relationId:'sr-mx',requirement:'REQUIRED',bodyRef:rb(b),contactRegionRef:rc(cr),supportSurfaceRef:rg(sg,sf),contactPolicy:'EXACT_OPPOSED_PHYSICAL_NORMAL',frameRefs:[rf(w),rf(cf),rf(sf)],supportedEntityId:'e'};sr={...sr,digest:D.digest(sr,'digest')};relations[sr.relationId]=sr;
 const e={entityId:'e',physicalParticipation:'ACTIVE'};
 if(containment){let bodyRef,targetG;
  if(compound){const g1=box('good-mx',F('g1-mx',w),['2','2','2']),g2=box('bad-mx',F('g2-mx',w,['100','0','0']),['2','2','2']);defs[g1.geometryId]=g1;defs[g2.geometryId]=g2;frames[g1.localFrameId]=Object.values(frames).find(f=>f.frameId===g1.localFrameId)||null;for(const g of [g1,g2]){const fr=Object.values(frames).find(f=>f.frameId===g.localFrameId);if(!fr)frames[g.localFrameId]=null}
   // frames for children
   }
  }
 // rebuild compound properly below (kept simple and explicit)
 if(compound){const f1=F('good-f-mx',w),f2=F('bad-f-mx',w,['100','0','0']);frames[f1.frameId]=f1;frames[f2.frameId]=f2;const g1=box('good-mx',f1,['2','2','2']),g2=box('bad-mx',f2,['2','2','2']);defs[g1.geometryId]=g1;defs[g2.geometryId]=g2;const cmpD=D.define({geometryId:'cmp-mx',schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:w.frameId,representationKind:'COMPOUND',shape:{children:[{childId:'a-bad',geometryId:'bad-mx'},{childId:'z-good',geometryId:'good-mx'}]},capabilities:[],limitations:[]});defs[cmpD.geometryId]=cmpD;
  frames[bf.frameId]=bf;frames[tf.frameId]=tf;const target=box('target-mx',tf,['50','50','50']);defs[target.geometryId]=target;
  const cmpPin={geometryId:cmpD.geometryId,revision:cmpD.revision,digest:cmpD.digest,localFrameRef:rf(w),childGeometryRefs:cmpD.shape.children.map(ch=>{const d=defs[ch.geometryId],fr=frames[d.localFrameId];return {childId:ch.childId,geometryId:d.geometryId,revision:d.revision,digest:d.digest,localFrameRef:rf(fr)}})};
  e.containmentAssignments=[{bodyGeometryRef:cmpPin,targetGeometryRef:rg(target,tf)}];e._compoundPin=cmpPin;
 }else if(containment){frames[bf.frameId]=bf;frames[tf.frameId]=tf;const bodyG=box('body-mx',bf),target=box('target-mx',tf,['50','50','50']);defs[bodyG.geometryId]=bodyG;defs[target.geometryId]=target;e.containmentAssignments=[{bodyGeometryRef:rg(bodyG,bf),targetGeometryRef:rg(target,tf)}]}
 if(openingMode){frames[obf.frameId]=obf;frames[of.frameId]=of;const ob=box('open-body-mx',obf,openingMode==='MISSING_BOUNDARY'?['5','5','1000']:['5','5','5']);const op=opening('opening-mx',of,'wall');defs[ob.geometryId]=ob;defs[op.geometryId]=op;
  const owner=C.boundaryFeature({boundaryFeatureId:'wall',revision:1,localFrameRef:rf(of),solidGeometryRefs:[],openingRegionRefs:[{geometryId:op.geometryId,revision:op.revision,digest:op.digest}],provenance:'FOUNDATION_MATRIX',limitations:[]});
  let bfRef={boundaryFeatureId:owner.boundaryFeatureId,revision:owner.revision,digest:owner.digest};
  if(openingMode!=='MISSING_BOUNDARY')bounds[owner.boundaryFeatureId]=owner;
  if(openingMode==='MISSING_BOUNDARY')bfRef={boundaryFeatureId:'MISSING-BOUNDARY',revision:1,digest:owner.digest};
  let bodyRef=rg(ob,obf);
  if(openingMode==='FORGED_BODY')bodyRef={...bodyRef,digest:'f'.repeat(64)};
  if(openingMode==='MISSING_BODY')bodyRef={...bodyRef,geometryId:'ghost-body'};
  e.openingAssignments=[{bodyGeometryRef:bodyRef,openingGeometryRef:rg(op,of),targetGeometryRef:rg(op,of),boundaryFeatureRef:bfRef}]}
 if(locked)e.requiredPhysicalCapabilities=[{capability:'V3_BODY_VS_BODY',request:{}}];
 if(extraValidUnrelated||corruptUnrelated){const uf=F('u-mx',w),ug=box('unrelated-mx',uf);frames[uf.frameId]=uf;defs[ug.geometryId]=ug;if(corruptUnrelated)defs[ug.geometryId]=Object.freeze({...ug,revision:2})}
 const authority={geometryRefs:{},geometryFrameRefs:{},bodyRefs:{},contactRegionRefs:{},supportRelationRefs:{},boundaryFeatureRefs:{}};
 for(const g of Object.values(defs)){const f=frames[g.localFrameId];if(g.geometryId==='cmp-mx'){authority.geometryRefs[g.geometryId]=e._compoundPin}else authority.geometryRefs[g.geometryId]=rg(g,f);authority.geometryFrameRefs[g.geometryId]=rf(f)}
 for(const bb of Object.values(bodies))authority.bodyRefs[bb.bodyId]=rb(bb);
 for(const c of Object.values(contacts))authority.contactRegionRefs[c.contactRegionId]=rc(c);
 for(const r of Object.values(relations))authority.supportRelationRefs[r.relationId]={relationId:r.relationId,revision:r.revision,digest:r.digest};
 for(const bb of Object.values(bounds))authority.boundaryFeatureRefs[bb.boundaryFeatureId]={boundaryFeatureId:bb.boundaryFeatureId,revision:bb.revision,digest:bb.digest};
 delete e._compoundPin;
 let registry=sealRegistry({authoritySnapshotId:'snap-mx',revision:1,definitions:defs,frames,bodies,contactRegions:contacts,supportRelations:relations,boundaryFeatures:bounds,authority});
 if(mutateRegistry)registry=mutateRegistry({registry,defs,frames,bounds});
 const b0={schemaVersion:'2.0.0',worldId:'world-mx',revision:0,entities:{e},physicalRelations:[],supportRelations:[sr]},before={...b0,stateDigest:digest(b0)},a0={...b0,revision:1},after={...a0,stateDigest:digest(a0)};
 const c0={commandId:'cmd-mx',type:'SetTransform',expectedWorldRevision:0,entityId:'e',transform:{position:[0,0,0]}},cmd={...c0,commandDigest:digest(c0)},t0={transactionId:'tx-mx',expectedWorldRevision:0,commands:[cmd]},transaction={...t0,transactionDigest:digest(t0)};
 return {registry,before,after,transaction}}
function decide(f){return Foundation.evaluateTransaction({beforeState:f.before,proposedState:f.after,transaction:f.transaction,registrySnapshot:f.registry})}
function reseal(r){return sealRegistry({...r,registrySnapshotDigest:undefined})}

test('FOUNDATION-OFFSET-PLANE-Y10 coplanar support at offset plane y=10 commits with VALID evaluator evidence',()=>{const d=decide(fixture({contactY:10}));assert.equal(d.decision,'COMMIT_ALLOWED',JSON.stringify(d.obligationResults));assert.equal(d.outcome,'PASS');assert.equal(d.obligationResults[0].v3.reason,'VALID');assert.equal(d.summary.evaluatorCalls,1)});
test('FOUNDATION-OFFSET-PLANE-Y11 floating above offset plane y=10 fails closed through the full path',()=>{const d=decide(fixture({contactY:11}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.obligationResults[0].v3.reason,'CONTACT_FLOATING');assert.equal(d.summary.failed,1)});
test('FOUNDATION-OFFSET-PLANE-Y9 penetrating the offset plane fails closed through the full path',()=>{const d=decide(fixture({contactY:9}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.obligationResults[0].v3.reason,'CONTACT_PENETRATION');assert.equal(d.summary.failed,1)});
test('FOUNDATION-MISSING-BOUNDARY-1000 unresolved affirmative owner with protrusion 1000 stops before the evaluator',()=>{const d=decide(fixture({openingMode:'MISSING_BOUNDARY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults[0];assert.equal(r.capability,'V3_OPENING');assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'INCOMPLETE_AUTHORITY');assert.equal(d.summary.evaluatorCalls,1)});
test('FOUNDATION-FORGED-CONTAINMENT-BODY tampered body authority pin rejects at envelope build',()=>{const d=decide(fixture({containment:'PASS',mutateRegistry:({registry})=>{registry.authority.geometryRefs['body-mx']={...registry.authority.geometryRefs['body-mx'],digest:'0'.repeat(64)};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'geometry-pin');assert.equal(d.envelopeFailure.evidence.recordId,'body-mx')});
test('FOUNDATION-FORGED-CONTAINMENT-TARGET tampered target authority pin rejects at envelope build',()=>{const d=decide(fixture({containment:'PASS',mutateRegistry:({registry})=>{registry.authority.geometryRefs['target-mx']={...registry.authority.geometryRefs['target-mx'],digest:'0'.repeat(64)};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.recordId,'target-mx')});
test('FOUNDATION-MISSING-OPENING-BODY opening body absent from the registry fails closed before the evaluator',()=>{const d=decide(fixture({openingMode:'MISSING_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults[0];assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'INCOMPLETE_AUTHORITY');assert.equal(d.summary.evaluatorCalls,1)});
test('FOUNDATION-FORGED-OPENING-BODY forged opening body reference is stale evidence at the evaluator',()=>{const d=decide(fixture({openingMode:'FORGED_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');const r=d.obligationResults[0];assert.equal(r.v3.status,'INVALID');assert.equal(r.v3.reason,'STALE_EVIDENCE');assert.equal(d.summary.invalidV3,1);assert.equal(d.outcome,'UNKNOWN')});
test('FOUNDATION-MISSING-OPENING-SOLID owner solid reference absent from the registry rejects at envelope build',()=>{const d=decide(fixture({openingMode:'PASS',mutateRegistry:({registry})=>{let nb={...registry.boundaryFeatures.wall,solidGeometryRefs:[{geometryId:'ghost-solid',revision:1,digest:'0'.repeat(64)}],digest:undefined};nb.digest=D.digest(nb,'digest');registry.boundaryFeatures.wall=Object.freeze(nb);registry.authority.boundaryFeatureRefs.wall={boundaryFeatureId:nb.boundaryFeatureId,revision:nb.revision,digest:nb.digest};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'INCOMPLETE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'solid-membership')});
test('FOUNDATION-FORGED-OPENING-SOLID tampered owner solid reference is stale at envelope build',()=>{const d=decide(fixture({openingMode:'PASS',mutateRegistry:({registry,frames})=>{const sf=F('solid-f-mx',frames['w-mx']);const sg=box('solid-mx',sf);registry.frames[sf.frameId]=sf;registry.definitions[sg.geometryId]=sg;registry.authority.geometryRefs[sg.geometryId]=rg(sg,sf);registry.authority.geometryFrameRefs[sg.geometryId]=rf(sf);let nb={...registry.boundaryFeatures.wall,solidGeometryRefs:[{geometryId:sg.geometryId,revision:sg.revision,digest:'0'.repeat(64)}],digest:undefined};nb.digest=D.digest(nb,'digest');registry.boundaryFeatures.wall=Object.freeze(nb);registry.authority.boundaryFeatureRefs.wall={boundaryFeatureId:nb.boundaryFeatureId,revision:nb.revision,digest:nb.digest};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'solid-membership')});
test('FOUNDATION-COMPOUND-ILLEGAL-SIBLING compound containment with an illegal sibling fails closed',()=>{const d=decide(fixture({compound:true}));assert.equal(d.decision,'REJECT_REQUIRED',JSON.stringify(d.obligationResults).slice(0,400));assert.equal(d.outcome,'FAIL');const r=d.obligationResults.find(x=>x.capability==='V3_CONTAINMENT');assert.equal(r.v3.status,'FAIL')});
test('FOUNDATION-QUANTIZATION-AMBIGUITY exact opening edge cannot PASS and stays UNKNOWN',()=>{const d=decide(fixture({openingMode:'AMBIGUITY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults.find(x=>x.capability==='V3_OPENING');assert.equal(r.v3.status,'UNKNOWN');assert.equal(r.v3.reason,'QUANTIZATION_AMBIGUITY')});
test('FOUNDATION-AGGREGATE-PASS-FAIL one passing and one failing obligation aggregates to FAIL and no commit',()=>{const d=decide(fixture({contactY:10,containment:'FAIL'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.summary.passed,1);assert.equal(d.summary.failed,1);assert.equal(d.summary.evaluatorCalls,2)});
test('FOUNDATION-AGGREGATE-PASS-UNKNOWN one passing and one ambiguous obligation aggregates to UNKNOWN and no commit',()=>{const d=decide(fixture({contactY:10,openingMode:'AMBIGUITY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.passed,1);assert.equal(d.summary.unknown,1)});
test('FOUNDATION-AGGREGATE-PASS-INVALID one passing and one invalid obligation aggregates to UNKNOWN and no commit',()=>{const d=decide(fixture({contactY:10,openingMode:'FORGED_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.passed,1);assert.equal(d.summary.invalidV3,1)});
test('FOUNDATION-AGGREGATE-PASS-NON_PROMOTED locked collision capability stays NON_PROMOTED inside a mixed decision',()=>{const d=decide(fixture({contactY:10,locked:true}));assert.equal(d.decision,'REJECT_REQUIRED');const locked=d.obligationResults.find(x=>x.capability==='V3_BODY_VS_BODY');assert(locked);assert.equal(locked.outcome,'UNKNOWN');assert.equal(locked.classification,'NON_PROMOTED_CAPABILITY');assert.equal(d.summary.passed,1);assert.equal(d.summary.evaluatorCalls,1)});
test('FOUNDATION-MALFORMED-EVALUATOR malformed module data reaching the evaluator fails closed with no commit',()=>{const d=decide(fixture({malformedContact:true}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults[0];assert.notEqual(r.outcome,'PASS');assert.equal(r.adapterEvidence.evaluatorCalls<=1,true);assert.equal(d.summary.passed,0)});
test('FOUNDATION-GLOBAL-CORRUPTION-OUTSIDE-IMPACT tampering an unrelated registry record rejects the whole decision',()=>{const d=decide(fixture({contactY:10,corruptUnrelated:true}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.recordId,'unrelated-mx')});
test('FOUNDATION-VALID-UNRELATED-CONTROL a valid unrelated registry record does not block a clean commit',()=>{const d=decide(fixture({contactY:10,extraValidUnrelated:true}));assert.equal(d.decision,'COMMIT_ALLOWED',JSON.stringify(d).slice(0,300));assert.equal(d.outcome,'PASS')});
// Manifest mutation detection: creating or modifying an unapproved production
// module must make the real isolation audit fail.
test('FOUNDATION-MANIFEST-MODIFIED-MODULE-DETECTED modifying a foundation module trips MANIFEST_SHA_MISMATCH',()=>{const p=path.resolve(__dirname,'../../src/clean-runtime/mutation/physical-capability-router.js'),orig=fs.readFileSync(p);try{fs.writeFileSync(p,orig+'\n// mutation-detection-probe\n');let failed=null;try{cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8',stdio:['ignore','pipe','pipe']})}catch(e){failed=e}assert(failed,'audit must fail on a modified module');assert(String(failed.stdout).includes('MANIFEST_SHA_MISMATCH'))}finally{fs.writeFileSync(p,orig)}
 const clean=cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8'});assert(JSON.parse(clean).findings.length===0)});
test('FOUNDATION-MANIFEST-UNAPPROVED-MODULE-DETECTED creating an unapproved module trips the audit set mismatch',()=>{const p=path.resolve(__dirname,'../../src/clean-runtime/v3-authority/unapproved-probe.js');try{fs.writeFileSync(p,'module.exports=1;\n');let failed=null;try{cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8',stdio:['ignore','pipe','pipe']})}catch(e){failed=e}assert(failed,'audit must fail on an unapproved module');assert(String(failed.stdout).includes('FOUNDATION_MANIFEST_SET_MISMATCH'))}finally{fs.rmSync(p,{force:true})}
 const clean=cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8'});assert(JSON.parse(clean).findings.length===0)});
