'use strict';
// Candidate 5 resubmission: normative behavioral regressions exercised through
// the complete Foundation path (registry -> envelope -> plan -> route ->
// context -> adapter -> evaluator -> decision aggregation). Every row asserts
// exact outcome, reason/classification, evaluator count, final decision (or
// adapter-level reject), unchanged synthetic state bytes on rejection, and
// emits a structured evidence record consumed by the matrix coverage checker.
const test=require('node:test'),assert=require('node:assert/strict'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const {digest}=require('../../src/clean-runtime/contracts/canonical'),G=require('../../src/numeric-frame-rotation/graph'),D=require('../../src/verified-architecture-phase2-v3/definitions'),C=require('../../src/verified-architecture-phase2-v3/closure-records'),Foundation=require('../../src/clean-runtime/mutation/v3-promotion-foundation'),{computeImpact,plan}=require('../../src/clean-runtime/mutation/physical-proof-planner'),{buildAuthorityEnvelope}=require('../../src/clean-runtime/v3-authority/authority-envelope-builder'),Router=require('../../src/clean-runtime/mutation/physical-capability-router'),{contextForObligation}=require('../../src/clean-runtime/v3-authority/authority-envelope'),Adapter=require('../../src/clean-runtime/mutation/v3-authority-adapter');
const rf=f=>({frameId:f.frameId,revision:f.revision,digest:f.digest}),rb=b=>({bodyId:b.bodyId,revision:b.revision,digest:b.digest}),rc=c=>({contactRegionId:c.contactRegionId,revision:c.revision,digest:c.digest}),rg=(g,f)=>({geometryId:g.geometryId,revision:g.revision,digest:g.digest,localFrameRef:rf(f)}),qi=['1','0','0','0'],HEX=/^[0-9a-f]{64}$/;
const RECORDS=[];
function rec(row,x){assert(HEX.test(x.resultDigest||''),'row '+row+' must carry a result/decision digest');RECORDS.push({row,...x});}
process.on('exit',()=>{const p=process.env.CANDIDATE5_MATRIX_EVIDENCE||path.resolve(__dirname,'../../evidence/clean-runtime/v3-authority-promotion-foundation/candidate5/foundation-matrix-evidence.json');fs.writeFileSync(p,JSON.stringify({schemaVersion:'v3-candidate5-foundation-matrix-evidence/1.0.0',records:RECORDS},null,2))});
function F(id,p=null,t=['0','0','0']){return G.sealFrame({frameId:id,frameKind:p?'ENTITY_LOCAL':'WORLD',parentFrameRef:p?rf(p):null,translationMicrounits:t,rotationQuaternionRatio:qi,revision:1,provenance:'FOUNDATION_MATRIX'})}
function region(id,f,y,extent,support){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'FINITE_PLANAR_REGION',shape:{vertices:[[String(-extent),String(y),String(-extent)],[String(extent),String(y),String(-extent)],[String(extent),String(y),String(extent)],[-extent,y,extent].map(String)],normal:['0','1','0'],sidedness:'FRONT_ONLY'},capabilities:support?['SUPPORT']:[],limitations:[]})}
function box(id,f,h=['5','5','5']){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'ORIENTED_BOX',shape:{halfExtentsMicrounits:h},capabilities:[],limitations:[]})}
function opening(id,f,bfId){return D.define({geometryId:id,schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:f.frameId,representationKind:'OPENING_REGION',shape:{vertices:[['-50','-50','0'],['50','-50','0'],['50','50','0'],['-50','50','0']],normal:['0','0','1'],sidedness:'FRONT_ONLY',localFrameRef:rf(f),boundaryFeatureRef:{boundaryFeatureId:bfId,revision:1}},capabilities:[],limitations:[]})}
function body(id){const x={bodyId:id,revision:1,provenance:'FOUNDATION_MATRIX',limitations:[]};x.digest=D.digest(x,'digest');return Object.freeze(x)}
function sealRegistry(r){const x={...r,registrySnapshotDigest:undefined};return {...r,registrySnapshotDigest:digest(x)}}
function reseal(r){return sealRegistry({...r,registrySnapshotDigest:undefined})}
function fixture(o={}){const {contactY=10,containment=null,openingMode=null,compound=false,locked=false,mutateRegistry=null,extraValidUnrelated=false,corruptUnrelated=false}=o;
 const w=F('w-mx'),cf=F('c-mx',w),sf=F('s-mx',w),bf=F('b-mx',w,containment==='FAIL'?['100','0','0']:['0','0','0']),tf=F('t-mx',w),of=F('o-mx',w),obf=F('ob-mx',w,openingMode==='AMBIGUITY'?['45','0','0']:['0','0','0']);
 const defs={},frames={[w.frameId]:w,[cf.frameId]:cf,[sf.frameId]:sf},bodies={},contacts={},relations={},bounds={};
 const cg=region('cg-mx',cf,contactY,2,false),sg=region('sg-mx',sf,10,20,true);defs[cg.geometryId]=cg;defs[sg.geometryId]=sg;
 const b=body('b-mx');bodies[b.bodyId]=b;
 const cr=C.contactRegion({contactRegionId:'cr-mx',revision:1,supportedBodyRef:rb(b),geometryRef:rg(cg,cf),expectedContactNormal:{valueClass:'EXACT_RATIONAL',frameRef:rf(w),components:['0','-1','0']},provenance:'FOUNDATION_MATRIX',limitations:[]});contacts[cr.contactRegionId]=cr;
 let sr={relationId:'sr-mx',requirement:'REQUIRED',bodyRef:rb(b),contactRegionRef:rc(cr),supportSurfaceRef:rg(sg,sf),contactPolicy:'EXACT_OPPOSED_PHYSICAL_NORMAL',frameRefs:[rf(w),rf(cf),rf(sf)],supportedEntityId:'e'};sr={...sr,digest:D.digest(sr,'digest')};relations[sr.relationId]=sr;
 const e={entityId:'e',physicalParticipation:'ACTIVE'};
 if(compound){const f1=F('good-f-mx',w),f2=F('bad-f-mx',w,['100','0','0']);frames[f1.frameId]=f1;frames[f2.frameId]=f2;frames[bf.frameId]=bf;frames[tf.frameId]=tf;const g1=box('good-mx',f1,['2','2','2']),g2=box('bad-mx',f2,['2','2','2']);defs[g1.geometryId]=g1;defs[g2.geometryId]=g2;const cmpD=D.define({geometryId:'cmp-mx',schemaVersion:'3.0.0',revision:1,provenance:{source:'FOUNDATION_MATRIX'},localFrameId:w.frameId,representationKind:'COMPOUND',shape:{children:[{childId:'a-bad',geometryId:'bad-mx'},{childId:'z-good',geometryId:'good-mx'}]},capabilities:[],limitations:[]});defs[cmpD.geometryId]=cmpD;
  const target=box('target-mx',tf,['50','50','50']);defs[target.geometryId]=target;
  const cmpPin={geometryId:cmpD.geometryId,revision:cmpD.revision,digest:cmpD.digest,localFrameRef:rf(w),childGeometryRefs:cmpD.shape.children.map(ch=>{const d=defs[ch.geometryId],fr=frames[d.localFrameId];return {childId:ch.childId,geometryId:d.geometryId,revision:d.revision,digest:d.digest,localFrameRef:rf(fr)}})};
  e.containmentAssignments=[{bodyGeometryRef:cmpPin,targetGeometryRef:rg(target,tf)}];e._compoundPin=cmpPin;
 }else if(containment){frames[bf.frameId]=bf;frames[tf.frameId]=tf;const bodyG=box('body-mx',bf),target=box('target-mx',tf,['50','50','50']);defs[bodyG.geometryId]=bodyG;defs[target.geometryId]=target;e.containmentAssignments=[{bodyGeometryRef:rg(bodyG,bf),targetGeometryRef:rg(target,tf)}]}
 if(openingMode){const forgedOwner=openingMode==='PROTRUSION_FORGED_OWNER',bfId=forgedOwner?'MISSING-BOUNDARY':'wall';frames[obf.frameId]=obf;frames[of.frameId]=of;const ob=box('open-body-mx',obf,(openingMode==='PROTRUSION'||forgedOwner)?['5','5','1000']:['5','5','5']);const op=opening('opening-mx',of,bfId);defs[ob.geometryId]=ob;defs[op.geometryId]=op;
  const owner=C.boundaryFeature({boundaryFeatureId:bfId,revision:1,localFrameRef:rf(of),solidGeometryRefs:[],openingRegionRefs:[{geometryId:op.geometryId,revision:op.revision,digest:op.digest}],provenance:'FOUNDATION_MATRIX',limitations:[]});
  let bfRef={boundaryFeatureId:owner.boundaryFeatureId,revision:owner.revision,digest:owner.digest};
  // PROTRUSION_FORGED_OWNER: the registry, opening definition and authority
  // pins stay fully self-consistent (owner id MISSING-BOUNDARY, real opening
  // membership), so envelope/plan/context all build READY. Only the world
  // state's opening assignment - attacker-influenced input - claims an owner
  // pin whose digest matches no authoritative record.
  if(forgedOwner){const claimed=C.boundaryFeature({boundaryFeatureId:bfId,revision:1,localFrameRef:rf(of),solidGeometryRefs:[],openingRegionRefs:[],provenance:'HOSTILE',limitations:[]});bfRef={boundaryFeatureId:bfId,revision:1,digest:claimed.digest}}
  bounds[owner.boundaryFeatureId]=owner;
  let bodyRef=rg(ob,obf);
  if(openingMode==='FORGED_BODY')bodyRef={...bodyRef,digest:'f'.repeat(64)};
  if(openingMode==='MISSING_BODY')bodyRef={...bodyRef,geometryId:'ghost-body'};
  e.openingAssignments=[{bodyGeometryRef:bodyRef,openingGeometryRef:rg(op,of),targetGeometryRef:rg(op,of),boundaryFeatureRef:bfRef}]}
 if(locked)e.requiredPhysicalCapabilities=[{capability:'V3_BODY_VS_BODY',request:{}}];
 if(extraValidUnrelated||corruptUnrelated){const uf=F('u-mx',w),ug=box('unrelated-mx',uf);frames[uf.frameId]=uf;defs[ug.geometryId]=ug;if(corruptUnrelated)defs[ug.geometryId]=Object.freeze({...ug,revision:2})}
 const authority={geometryRefs:{},geometryFrameRefs:{},bodyRefs:{},contactRegionRefs:{},supportRelationRefs:{},boundaryFeatureRefs:{}};
 for(const g of Object.values(defs)){const f=frames[g.localFrameId];if(g.geometryId==='cmp-mx'){authority.geometryRefs[g.geometryId]=e._compoundPin}else authority.geometryRefs[g.geometryId]=rg(g,f);authority.geometryFrameRefs[g.geometryId]=rf(f)}
 for(const bb of Object.values(bodies))authority.bodyRefs[bb.bodyId]=rb(bb);
 for(const c of Object.values(contacts))authority.contactRegionRefs[c.contactRegionId]=rc(c);
 for(const r of Object.values(relations))authority.supportRelationRefs[r.relationId]={relationId:r.relationId,revision:r.revision,digest:r.digest};
 for(const bb of Object.values(bounds))authority.boundaryFeatureRefs[bb.boundaryFeatureId]={boundaryFeatureId:bb.boundaryFeatureId,revision:bb.revision,digest:bb.digest};
 delete e._compoundPin;
 let registry=sealRegistry({authoritySnapshotId:'snap-mx',revision:1,definitions:defs,frames,bodies,contactRegions:contacts,supportRelations:relations,boundaryFeatures:bounds,authority});
 if(mutateRegistry)registry=mutateRegistry({registry,defs,frames,bounds});
 const b0={schemaVersion:'2.0.0',worldId:'world-mx',revision:0,entities:{e},physicalRelations:[],supportRelations:[sr]},before={...b0,stateDigest:digest(b0)},a0={...b0,revision:1},after={...a0,stateDigest:digest(a0)};
 const c0={commandId:'cmd-mx',type:'SetTransform',expectedWorldRevision:0,entityId:'e',transform:{position:[0,0,0]}},cmd={...c0,commandDigest:digest(c0)},t0={transactionId:'tx-mx',expectedWorldRevision:0,commands:[cmd]},transaction={...t0,transactionDigest:digest(t0)};
 return {registry,before,after,transaction}}
function decide(f){const s0=digest(f.before),s1=digest(f.after);const d=Foundation.evaluateTransaction({beforeState:f.before,proposedState:f.after,transaction:f.transaction,registrySnapshot:f.registry});assert.equal(digest(f.before),s0,'before state bytes mutated');assert.equal(digest(f.after),s1,'proposed state bytes mutated');return {d,stateBytesUnchanged:true}}
function chain(f,capability){const impact=computeImpact({beforeState:f.before,proposedState:f.after,transaction:f.transaction}),eb=buildAuthorityEnvelope({registrySnapshot:f.registry,beforeState:f.before,proposedState:f.after,transaction:f.transaction,impactSet:impact});assert.equal(eb.status,'READY');const pp=plan({beforeState:f.before,proposedState:f.after,transaction:f.transaction,envelope:eb.envelope});assert.equal(pp.status,'READY');const o=pp.plan.obligations.find(x=>x.capability===capability);assert(o,'missing obligation '+capability);const rr=Router.route({capability:o.capability,apiVersion:o.apiVersion,queryType:o.queryType});assert.equal(rr.status,'ROUTED');const cx=contextForObligation(eb.envelope,o);assert.equal(cx.status,'READY');return {f,eb,pp,o,rr,cx}}
function resealObligation(o,requestPatch,reqPatch){const b={...o,request:{...o.request,...requestPatch},authorityRequirements:{...o.authorityRequirements,...reqPatch},obligationDigest:undefined};return Object.freeze({...b,obligationDigest:digest(b)})}
function resealContext(cx,contextPatch){const body={schemaVersion:cx.schemaVersion,obligationId:cx.obligationId,sourceEnvelopeDigest:cx.sourceEnvelopeDigest,authoritySnapshotRef:cx.authoritySnapshotRef,authoritySnapshotRefDigest:cx.authoritySnapshotRefDigest,worldBinding:cx.worldBinding,worldBindingDigest:cx.worldBindingDigest,context:{...cx.context,...contextPatch}};return {status:'READY',...body,contextDigest:digest(body)}}

test('OFFSET_PLANE_Y10 coplanar support at offset plane y=10 commits with VALID evaluator evidence',()=>{const {d}=decide(fixture({contactY:10}));assert.equal(d.decision,'COMMIT_ALLOWED');assert.equal(d.outcome,'PASS');assert.equal(d.obligationResults[0].v3.reason,'VALID');assert.equal(d.summary.evaluatorCalls,1);rec('OFFSET_PLANE_Y10',{outcome:'PASS',reason:'VALID',classification:'V3_VALID',evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','v3.reason','summary.evaluatorCalls','decisionDigest']})});
test('OFFSET_PLANE_Y11 floating above offset plane y=10 fails closed through the full path',()=>{const {d}=decide(fixture({contactY:11}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.obligationResults[0].v3.reason,'CONTACT_FLOATING');assert.equal(d.summary.failed,1);rec('OFFSET_PLANE_Y11',{outcome:'FAIL',reason:'CONTACT_FLOATING',classification:'V3_DEFINITE_ILLEGALITY',evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','v3.reason','summary.failed']})});
test('OFFSET_PLANE_Y9 penetrating the offset plane fails closed through the full path',()=>{const {d}=decide(fixture({contactY:9}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.obligationResults[0].v3.reason,'CONTACT_PENETRATION');assert.equal(d.summary.failed,1);rec('OFFSET_PLANE_Y9',{outcome:'FAIL',reason:'CONTACT_PENETRATION',classification:'V3_DEFINITE_ILLEGALITY',evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','v3.reason','summary.failed']})});
test('MISSING_BOUNDARY_PROTRUSION_1000 forged affirmative owner pin with protrusion 1000 is INVALID/STALE_EVIDENCE before geometry through the real chain',()=>{const f=fixture({openingMode:'PROTRUSION_FORGED_OWNER'});const {o}=chain(f,'V3_OPENING');assert.deepEqual(o.authorityRequirements.boundaryFeatureIds,['MISSING-BOUNDARY'],'planner must keep the boundary requirement');assert.equal(o.request.boundaryFeatureRef.boundaryFeatureId,'MISSING-BOUNDARY');assert.notEqual(o.request.boundaryFeatureRef.digest,f.registry.boundaryFeatures['MISSING-BOUNDARY'].digest,'claimed owner pin must match no authoritative record');const {d,stateBytesUnchanged}=decide(f);assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults.find(x=>x.capability==='V3_OPENING');assert(r,'missing V3_OPENING obligation result');assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'V3_INVALID_AUTHORITY');assert.equal(r.v3.status,'INVALID');assert.equal(r.v3.reason,'STALE_EVIDENCE');assert.equal(r.adapterEvidence.validationStage,'complete');assert.equal(r.adapterEvidence.evaluatorCalls,1);assert.equal(d.summary.required,2);assert.equal(d.summary.invalidV3,1);assert.equal(d.summary.evaluatorCalls,2);rec('MISSING_BOUNDARY_PROTRUSION_1000',{outcome:r.outcome,reason:r.v3.reason,classification:r.classification,evaluatorCalls:r.adapterEvidence.evaluatorCalls,decision:d.decision,stateBytesUnchanged,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','obligationResults[V3_OPENING].outcome','obligationResults[V3_OPENING].classification','obligationResults[V3_OPENING].v3.status','obligationResults[V3_OPENING].v3.reason','obligationResults[V3_OPENING].adapterEvidence.validationStage','obligationResults[V3_OPENING].adapterEvidence.evaluatorCalls','summary.invalidV3','summary.evaluatorCalls','decisionDigest']})});
test('FORGED_CONTAINMENT_BODY tampered body authority pin rejects at envelope build',()=>{const {d}=decide(fixture({containment:'PASS',mutateRegistry:({registry})=>{registry.authority.geometryRefs['body-mx']={...registry.authority.geometryRefs['body-mx'],digest:'0'.repeat(64)};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'geometry-pin');assert.equal(d.envelopeFailure.evidence.recordId,'body-mx');assert.equal(d.summary.evaluatorCalls,0);rec('FORGED_CONTAINMENT_BODY',{outcome:d.outcome,reason:'STALE_AUTHORITY',classification:'ENVELOPE_REJECTED',evaluatorCalls:0,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','envelopeFailure.reason','envelopeFailure.evidence.stage','envelopeFailure.evidence.recordId']})});
test('FORGED_CONTAINMENT_TARGET tampered target authority pin rejects at envelope build',()=>{const {d}=decide(fixture({containment:'PASS',mutateRegistry:({registry})=>{registry.authority.geometryRefs['target-mx']={...registry.authority.geometryRefs['target-mx'],digest:'0'.repeat(64)};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.recordId,'target-mx');assert.equal(d.summary.evaluatorCalls,0);rec('FORGED_CONTAINMENT_TARGET',{outcome:d.outcome,reason:'STALE_AUTHORITY',classification:'ENVELOPE_REJECTED',evaluatorCalls:0,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','envelopeFailure.reason','envelopeFailure.evidence.recordId']})});
test('MISSING_OPENING_BODY opening body absent from the registry fails closed before the evaluator',()=>{const {d}=decide(fixture({openingMode:'MISSING_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults.find(x=>x.capability==='V3_OPENING');assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'INCOMPLETE_AUTHORITY');assert.equal(d.summary.evaluatorCalls,1);rec('MISSING_OPENING_BODY',{outcome:r.outcome,reason:'INCOMPLETE_AUTHORITY',classification:r.classification,evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','classification','summary.evaluatorCalls']})});
test('FORGED_OPENING_BODY forged opening body reference is stale evidence at the evaluator',()=>{const {d}=decide(fixture({openingMode:'FORGED_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');const r=d.obligationResults.find(x=>x.capability==='V3_OPENING');assert.equal(r.v3.status,'INVALID');assert.equal(r.v3.reason,'STALE_EVIDENCE');assert.equal(d.summary.invalidV3,1);assert.equal(d.outcome,'UNKNOWN');rec('FORGED_OPENING_BODY',{outcome:d.outcome,reason:'STALE_EVIDENCE',classification:r.classification,evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','v3.status','v3.reason','summary.invalidV3','outcome']})});
test('MISSING_OPENING_SOLID owner solid reference absent from the registry rejects at envelope build',()=>{const {d}=decide(fixture({openingMode:'PASS',mutateRegistry:({registry})=>{let nb={...registry.boundaryFeatures.wall,solidGeometryRefs:[{geometryId:'ghost-solid',revision:1,digest:'0'.repeat(64)}],digest:undefined};nb.digest=D.digest(nb,'digest');registry.boundaryFeatures.wall=Object.freeze(nb);registry.authority.boundaryFeatureRefs.wall={boundaryFeatureId:nb.boundaryFeatureId,revision:nb.revision,digest:nb.digest};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'INCOMPLETE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'solid-membership');assert.equal(d.summary.evaluatorCalls,0);rec('MISSING_OPENING_SOLID',{outcome:d.outcome,reason:'INCOMPLETE_AUTHORITY',classification:'ENVELOPE_REJECTED',evaluatorCalls:0,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','envelopeFailure.reason','envelopeFailure.evidence.stage']})});
test('FORGED_OPENING_SOLID tampered owner solid reference is stale at envelope build',()=>{const {d}=decide(fixture({openingMode:'PASS',mutateRegistry:({registry,frames})=>{const sf=F('solid-f-mx',frames['w-mx']);const sg=box('solid-mx',sf);registry.frames[sf.frameId]=sf;registry.definitions[sg.geometryId]=sg;registry.authority.geometryRefs[sg.geometryId]=rg(sg,sf);registry.authority.geometryFrameRefs[sg.geometryId]=rf(sf);let nb={...registry.boundaryFeatures.wall,solidGeometryRefs:[{geometryId:sg.geometryId,revision:sg.revision,digest:'0'.repeat(64)}],digest:undefined};nb.digest=D.digest(nb,'digest');registry.boundaryFeatures.wall=Object.freeze(nb);registry.authority.boundaryFeatureRefs.wall={boundaryFeatureId:nb.boundaryFeatureId,revision:nb.revision,digest:nb.digest};return reseal(registry)}}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.stage,'solid-membership');assert.equal(d.summary.evaluatorCalls,0);rec('FORGED_OPENING_SOLID',{outcome:d.outcome,reason:'STALE_AUTHORITY',classification:'ENVELOPE_REJECTED',evaluatorCalls:0,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','envelopeFailure.reason','envelopeFailure.evidence.stage']})});
test('COMPOUND_ILLEGAL_SIBLING compound containment with an illegal sibling fails closed',()=>{const {d}=decide(fixture({compound:true}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');const r=d.obligationResults.find(x=>x.capability==='V3_CONTAINMENT');assert.equal(r.v3.status,'FAIL');rec('COMPOUND_ILLEGAL_SIBLING',{outcome:d.outcome,reason:r.v3.reason,classification:r.classification,evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','v3.status','v3.reason']})});
test('QUANTIZATION_AMBIGUITY exact opening edge cannot PASS and stays UNKNOWN',()=>{const {d}=decide(fixture({openingMode:'AMBIGUITY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');const r=d.obligationResults.find(x=>x.capability==='V3_OPENING');assert.equal(r.v3.status,'UNKNOWN');assert.equal(r.v3.reason,'QUANTIZATION_AMBIGUITY');rec('QUANTIZATION_AMBIGUITY',{outcome:d.outcome,reason:'QUANTIZATION_AMBIGUITY',classification:r.classification,evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','v3.status','v3.reason']})});
test('AGGREGATE_PASS_PASS two passing obligations aggregate to COMMIT_ALLOWED',()=>{const {d}=decide(fixture({contactY:10,containment:'PASS'}));assert.equal(d.decision,'COMMIT_ALLOWED');assert.equal(d.outcome,'PASS');assert.equal(d.summary.passed,2);assert.equal(d.summary.evaluatorCalls,2);rec('AGGREGATE_PASS_PASS',{outcome:d.outcome,reason:'VALID',classification:'V3_VALID',evaluatorCalls:2,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.passed','summary.evaluatorCalls']})});
test('AGGREGATE_PASS_FAIL one passing and one failing obligation aggregates to FAIL and no commit',()=>{const {d}=decide(fixture({contactY:10,containment:'FAIL'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.summary.passed,1);assert.equal(d.summary.failed,1);assert.equal(d.summary.evaluatorCalls,2);rec('AGGREGATE_PASS_FAIL',{outcome:d.outcome,reason:'FAIL',classification:'V3_DEFINITE_ILLEGALITY',evaluatorCalls:2,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.passed','summary.failed','summary.evaluatorCalls']})});
test('AGGREGATE_PASS_UNKNOWN one passing and one ambiguous obligation aggregates to UNKNOWN and no commit',()=>{const {d}=decide(fixture({contactY:10,openingMode:'AMBIGUITY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.passed,1);assert.equal(d.summary.unknown,1);rec('AGGREGATE_PASS_UNKNOWN',{outcome:d.outcome,reason:'QUANTIZATION_AMBIGUITY',classification:'V3_UNCERTAIN_OR_UNSUPPORTED',evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.passed','summary.unknown']})});
test('AGGREGATE_PASS_INVALID one passing and one invalid obligation aggregates to UNKNOWN and no commit',()=>{const {d}=decide(fixture({contactY:10,openingMode:'FORGED_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.passed,1);assert.equal(d.summary.invalidV3,1);rec('AGGREGATE_PASS_INVALID',{outcome:d.outcome,reason:'STALE_EVIDENCE',classification:'V3_INVALID_AUTHORITY',evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.passed','summary.invalidV3']})});
test('AGGREGATE_PASS_NON_PROMOTED locked collision capability stays NON_PROMOTED inside a mixed decision',()=>{const {d}=decide(fixture({contactY:10,locked:true}));assert.equal(d.decision,'REJECT_REQUIRED');const locked=d.obligationResults.find(x=>x.capability==='V3_BODY_VS_BODY');assert(locked);assert.equal(locked.outcome,'UNKNOWN');assert.equal(locked.classification,'NON_PROMOTED_CAPABILITY');assert.equal(d.summary.passed,1);assert.equal(d.summary.evaluatorCalls,1);rec('AGGREGATE_PASS_NON_PROMOTED',{outcome:d.outcome,reason:'NON_PROMOTED_CAPABILITY',classification:'NON_PROMOTED_CAPABILITY',evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','locked.outcome','locked.classification','summary.passed','summary.evaluatorCalls']})});
test('FAIL_CLOSED_PRECEDENCE_UNKNOWN_OVER_FAIL ambiguity outranks definite failure and blocks commit',()=>{const {d}=decide(fixture({contactY:11,openingMode:'AMBIGUITY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.failed,1);assert.equal(d.summary.unknown,1);rec('FAIL_CLOSED_PRECEDENCE_UNKNOWN_OVER_FAIL',{outcome:d.outcome,reason:'QUANTIZATION_AMBIGUITY',classification:'V3_UNCERTAIN_OR_UNSUPPORTED',evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.failed','summary.unknown']})});
test('FAIL_CLOSED_PRECEDENCE_INVALID_OVER_FAIL invalid authority outranks definite failure and blocks commit',()=>{const {d}=decide(fixture({contactY:11,openingMode:'FORGED_BODY'}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'UNKNOWN');assert.equal(d.summary.failed,1);assert.equal(d.summary.invalidV3,1);rec('FAIL_CLOSED_PRECEDENCE_INVALID_OVER_FAIL',{outcome:d.outcome,reason:'STALE_EVIDENCE',classification:'V3_INVALID_AUTHORITY',evaluatorCalls:d.summary.evaluatorCalls,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','summary.failed','summary.invalidV3']})});
test('EVALUATOR_THROW throwing evaluator converts to bounded UNKNOWN/MALFORMED_V3_RESULT through a real aggregate decision',()=>{const f=fixture({contactY:10});const tx=Foundation.__testOnlyCreateEvaluateTransaction(Adapter.__testOnlyCreateAdapter(()=>{throw new Error('boom')}));const s0=digest(f.before),s1=digest(f.after);const run=()=>tx({beforeState:f.before,proposedState:f.after,transaction:f.transaction,registrySnapshot:f.registry});const d1=run(),d2=run();const stateBytesUnchanged=digest(f.before)===s0&&digest(f.after)===s1;assert(stateBytesUnchanged,'synthetic state bytes mutated');assert.equal(d1.decision,'REJECT_REQUIRED');assert.equal(d1.outcome,'UNKNOWN');const r=d1.obligationResults[0];assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'MALFORMED_V3_RESULT');assert.equal(r.v3.status,'MALFORMED');assert.equal(r.v3.reason,'MALFORMED_V3_RESULT');assert.equal(r.adapterEvidence.validationStage,'evaluator-throw');assert.equal(r.adapterEvidence.evaluatorCalls,1);assert.equal(r.exception,'boom');assert.equal(d1.summary.evaluatorCalls,1);assert.notEqual(r.outcome,'PASS');assert.equal(r.resultDigest,d2.obligationResults[0].resultDigest,'throw conversion is not deterministic');assert.equal(d1.decisionDigest,d2.decisionDigest);rec('EVALUATOR_THROW',{outcome:r.outcome,reason:r.v3.reason,classification:r.classification,evaluatorCalls:r.adapterEvidence.evaluatorCalls,decision:d1.decision,stateBytesUnchanged,resultDigest:d1.decisionDigest,evidenceFields:['decision','outcome','classification','v3.status','v3.reason','adapterEvidence.validationStage','adapterEvidence.evaluatorCalls','exception','summary.evaluatorCalls','resultDigest-determinism','decisionDigest']})});
test('EVALUATOR_MALFORMED_RETURN malformed evaluator result converts to bounded UNKNOWN/MALFORMED_V3_RESULT through a real aggregate decision',()=>{const f=fixture({contactY:10});const {o}=chain(f,'V3_SUPPORT');const bogus=()=>Object.freeze({status:'BOGUS',apiVersion:'3.0.0',requestId:o.request.requestId,queryType:o.queryType,reason:'VALID'});const tx=Foundation.__testOnlyCreateEvaluateTransaction(Adapter.__testOnlyCreateAdapter(bogus));const s0=digest(f.before),s1=digest(f.after);const run=()=>tx({beforeState:f.before,proposedState:f.after,transaction:f.transaction,registrySnapshot:f.registry});const d1=run(),d2=run();const stateBytesUnchanged=digest(f.before)===s0&&digest(f.after)===s1;assert(stateBytesUnchanged,'synthetic state bytes mutated');assert.equal(d1.decision,'REJECT_REQUIRED');assert.equal(d1.outcome,'UNKNOWN');const r=d1.obligationResults[0];assert.equal(r.outcome,'UNKNOWN');assert.equal(r.classification,'MALFORMED_V3_RESULT');assert.equal(r.v3.status,'MALFORMED');assert.equal(r.v3.reason,'MALFORMED_V3_RESULT');assert.equal(r.adapterEvidence.validationStage,'evaluator-result');assert.equal(r.adapterEvidence.evaluatorCalls,1);assert.equal(d1.summary.evaluatorCalls,1);assert.notEqual(r.outcome,'PASS');assert.equal(r.resultDigest,d2.obligationResults[0].resultDigest,'malformed-result conversion is not deterministic');assert.equal(d1.decisionDigest,d2.decisionDigest);rec('EVALUATOR_MALFORMED_RETURN',{outcome:r.outcome,reason:r.v3.reason,classification:r.classification,evaluatorCalls:r.adapterEvidence.evaluatorCalls,decision:d1.decision,stateBytesUnchanged,resultDigest:d1.decisionDigest,evidenceFields:['decision','outcome','classification','v3.status','v3.reason','adapterEvidence.validationStage','adapterEvidence.evaluatorCalls','summary.evaluatorCalls','resultDigest-determinism','decisionDigest']})});
test('CALLER_EVALUATOR_BYPASS caller-supplied evaluator input cannot override the closed evaluator on a y=11 floating contact',()=>{const f=fixture({contactY:11});const {d,stateBytesUnchanged}=decide(f);assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.outcome,'FAIL');assert.equal(d.obligationResults[0].v3.status,'FAIL');assert.equal(d.obligationResults[0].v3.reason,'CONTACT_FLOATING');const {eb,o,rr,cx}=chain(f,'V3_SUPPORT');const signed={apiVersion:'3.0.0',requestId:o.request.requestId,queryType:o.queryType,status:'PASS',reason:'VALID',evidence:{attackerControlled:true,claim:'forged VALID evidence'}};signed.evidenceDigest=D.digest(signed,'evidenceDigest');Object.freeze(signed);const r=Adapter.evaluate({obligation:o,route:rr.route,context:cx,envelopeRef:{envelopeDigest:eb.envelope.envelopeDigest,authoritySnapshotRef:eb.envelope.authoritySnapshotRef,worldBinding:eb.envelope.worldBinding},evaluator:()=>signed});assert.equal(r.outcome,'FAIL');assert.equal(r.classification,'V3_DEFINITE_ILLEGALITY');assert.equal(r.v3.status,'FAIL');assert.equal(r.v3.reason,'CONTACT_FLOATING');assert.equal(r.adapterEvidence.evaluatorId,'CLOSED_V3');assert.equal(r.adapterEvidence.evaluatorCalls,1);assert.equal(r.adapterEvidence.validationStage,'complete');assert.notEqual(r.v3.evidenceDigest,signed.evidenceDigest,'attacker evidence was preserved');assert.equal(r.resultDigest,d.obligationResults[0].resultDigest,'caller-injected evaluator changed the adapter result bytes');rec('CALLER_EVALUATOR_BYPASS',{outcome:r.outcome,reason:r.v3.reason,classification:r.classification,evaluatorCalls:r.adapterEvidence.evaluatorCalls,decision:d.decision,stateBytesUnchanged,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome','classification','v3.status','v3.reason','adapterEvidence.evaluatorId','adapterEvidence.evaluatorCalls','adapterEvidence.validationStage','resultDigest-equals-real-chain-result','decisionDigest']})});
test('GLOBAL_CORRUPTION_OUTSIDE_IMPACT tampering an unrelated registry record rejects the whole decision',()=>{const {d}=decide(fixture({contactY:10,corruptUnrelated:true}));assert.equal(d.decision,'REJECT_REQUIRED');assert.equal(d.envelopeFailure.reason,'STALE_AUTHORITY');assert.equal(d.envelopeFailure.evidence.recordId,'unrelated-mx');assert.equal(d.summary.evaluatorCalls,0);rec('GLOBAL_CORRUPTION_OUTSIDE_IMPACT',{outcome:d.outcome,reason:'STALE_AUTHORITY',classification:'ENVELOPE_REJECTED',evaluatorCalls:0,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','envelopeFailure.reason','envelopeFailure.evidence.recordId']})});
test('VALID_UNRELATED_CONTROL a valid unrelated registry record does not block a clean commit',()=>{const {d}=decide(fixture({contactY:10,extraValidUnrelated:true}));assert.equal(d.decision,'COMMIT_ALLOWED');assert.equal(d.outcome,'PASS');rec('VALID_UNRELATED_CONTROL',{outcome:d.outcome,reason:'VALID',classification:'V3_VALID',evaluatorCalls:1,decision:d.decision,stateBytesUnchanged:true,resultDigest:d.decisionDigest,evidenceFields:['decision','outcome']})});
test('MANIFEST_MODIFIED_MODULE modifying a foundation module trips MANIFEST_SHA_MISMATCH',()=>{const p=path.resolve(__dirname,'../../src/clean-runtime/mutation/physical-capability-router.js'),orig=fs.readFileSync(p);try{fs.writeFileSync(p,orig+'\n// mutation-detection-probe\n');let failed=null;try{cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8',stdio:['ignore','pipe','pipe']})}catch(e){failed=e}assert(failed,'audit must fail on a modified module');assert(String(failed.stdout).includes('MANIFEST_SHA_MISMATCH'))}finally{fs.writeFileSync(p,orig)}
 const clean=JSON.parse(cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8'}));assert(clean.findings.length===0);rec('MANIFEST_MODIFIED_MODULE',{outcome:'UNKNOWN',reason:'MANIFEST_SHA_MISMATCH',classification:'AUDIT_FINDING',evaluatorCalls:0,decision:'AUDIT_REJECTED',stateBytesUnchanged:true,resultDigest:clean.auditDigest,evidenceFields:['audit.exit-nonzero-on-mutation','audit.findings.MANIFEST_SHA_MISMATCH','audit.clean-after-restore']})});
test('MANIFEST_UNAPPROVED_MODULE creating an unapproved module trips the audit set mismatch',()=>{const p=path.resolve(__dirname,'../../src/clean-runtime/v3-authority/unapproved-probe.js');try{fs.writeFileSync(p,'module.exports=1;\n');let failed=null;try{cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8',stdio:['ignore','pipe','pipe']})}catch(e){failed=e}assert(failed,'audit must fail on an unapproved module');assert(String(failed.stdout).includes('FOUNDATION_MANIFEST_SET_MISMATCH'))}finally{fs.rmSync(p,{force:true})}
 const clean=JSON.parse(cp.execFileSync('node',['tests/clean-runtime/v3-promotion-authority-audit.js'],{cwd:path.resolve(__dirname,'../..'),encoding:'utf8'}));assert(clean.findings.length===0);rec('MANIFEST_UNAPPROVED_MODULE',{outcome:'UNKNOWN',reason:'FOUNDATION_MANIFEST_SET_MISMATCH',classification:'AUDIT_FINDING',evaluatorCalls:0,decision:'AUDIT_REJECTED',stateBytesUnchanged:true,resultDigest:clean.auditDigest,evidenceFields:['audit.exit-nonzero-on-unapproved','audit.findings.FOUNDATION_MANIFEST_SET_MISMATCH','audit.clean-after-restore']})});
