'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {digest}=require('../../src/clean-runtime/contracts/canonical');
const {contextForObligation}=require('../../src/clean-runtime/v3-authority/authority-envelope');
const Adapter=require('../../src/clean-runtime/mutation/v3-authority-adapter');
const Foundation=require('../../src/clean-runtime/mutation/v3-promotion-foundation');
const {execute,replay,proofRoot,makeEvent}=require('./v3-foundation-commit-replay-simulator');

// --- A3 binding fixtures: canonical sealed envelope with full authoritySnapshotRef and worldBinding ---
const H=h=>h.repeat(64);
function sealedEnvelope(id){const body={schemaVersion:'v3-authority-envelope/1.0.0',envelopeId:id,authoritySnapshotRef:{authoritySnapshotId:'snap-'+id,revision:1,digest:H('d')},worldBinding:{worldId:'w',beforeRevision:0,beforeStateDigest:H('a'),proposedRevision:1,proposedStateDigest:H('b'),transactionId:'tx',transactionDigest:H('c')},definitions:{},frames:{},bodies:{},contactRegions:{},supportRelations:{},boundaryFeatures:{},authority:{geometryRefs:{},geometryFrameRefs:{},boundaryFeatureRefs:{}}};return Object.freeze({...body,envelopeDigest:digest(body)})}
function obligation(env){const core={schemaVersion:'physical-proof-obligation/1.0.0',obligationId:'V3_SUPPORT:x',capability:'V3_SUPPORT',apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',subjectEntityIds:['e'],relationIds:[],boundaryFeatureIds:[],request:{apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',requestId:'V3_SUPPORT:x'},authorityRequirements:{geometryIds:[],geometryFrameIds:[],bodyIds:[],contactRegionIds:[],supportRelationIds:[],boundaryFeatureIds:[]},beforeDependencyDigest:H('a'),proposedDependencyDigest:H('b'),authorityEnvelopeDigest:env.envelopeDigest};return Object.freeze({...core,obligationDigest:digest(core)})}
test('mixed-envelope context projection rejects before evaluator',()=>{const a=sealedEnvelope('A'),b=sealedEnvelope('B'),o=obligation(a),cx=contextForObligation(b,o);assert.equal(cx.status,'INCOMPLETE_AUTHORITY');assert.equal(cx.reason,'MIXED_ENVELOPE')});
test('context projection rejects envelope missing authoritySnapshotRef',()=>{const b0={...sealedEnvelope('A')};delete b0.authoritySnapshotRef;delete b0.envelopeDigest;const b=Object.freeze({...b0,envelopeDigest:digest(b0)});assert.equal(contextForObligation(b,obligation(b)).reason,'INVALID_ENVELOPE')});
test('context projection rejects envelope missing canonical worldBinding',()=>{const b0={...sealedEnvelope('A')};delete b0.worldBinding;delete b0.envelopeDigest;const b=Object.freeze({...b0,envelopeDigest:digest(b0)});assert.equal(contextForObligation(b,obligation(b)).reason,'INVALID_ENVELOPE')});
test('A3 context binds sourceEnvelopeDigest, full authoritySnapshotRef and canonical worldBinding',()=>{const a=sealedEnvelope('A'),cx=contextForObligation(a,obligation(a));assert.equal(cx.status,'READY');assert.equal(cx.sourceEnvelopeDigest,a.envelopeDigest);assert.deepEqual(cx.authoritySnapshotRef,a.authoritySnapshotRef);assert.equal(cx.authoritySnapshotRefDigest,digest(a.authoritySnapshotRef));assert.deepEqual(cx.worldBinding,a.worldBinding);assert.equal(cx.worldBindingDigest,digest(a.worldBinding));assert.equal(cx.contextDigest,digest({schemaVersion:cx.schemaVersion,obligationId:cx.obligationId,sourceEnvelopeDigest:cx.sourceEnvelopeDigest,authoritySnapshotRef:cx.authoritySnapshotRef,authoritySnapshotRefDigest:cx.authoritySnapshotRefDigest,worldBinding:cx.worldBinding,worldBindingDigest:cx.worldBindingDigest,context:cx.context}))});
function routeFor(o){const body={capability:'V3_SUPPORT',routeState:'PROMOTED',apiVersion:'3.0.0',queryType:o.queryType,evaluatorId:'CLOSED_V3',routeTableDigest:H('e')};return Object.freeze({...body,routeDigest:digest(body)})}
function reseal(cx){const body={schemaVersion:cx.schemaVersion,obligationId:cx.obligationId,sourceEnvelopeDigest:cx.sourceEnvelopeDigest,authoritySnapshotRef:cx.authoritySnapshotRef,authoritySnapshotRefDigest:cx.authoritySnapshotRefDigest,worldBinding:cx.worldBinding,worldBindingDigest:cx.worldBindingDigest,context:cx.context};return {...cx,contextDigest:digest(body)}}
test('adapter rejects context rebound to another envelope with zero evaluator calls',()=>{const a=sealedEnvelope('A'),b=sealedEnvelope('B'),o=obligation(a),cx=reseal({...contextForObligation(a,o),sourceEnvelopeDigest:b.envelopeDigest});const r=Adapter.evaluate({obligation:o,route:routeFor(o),context:cx,envelopeRef:{envelopeDigest:a.envelopeDigest}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.adapterEvidence.evaluatorCalls,0)});
test('adapter rejects honestly re-signed context with tampered authoritySnapshotRef',()=>{const a=sealedEnvelope('A'),o=obligation(a),base=contextForObligation(a,o),snap={authoritySnapshotId:'forged',revision:1,digest:H('f')},cx=reseal({...base,authoritySnapshotRef:snap,authoritySnapshotRefDigest:digest(snap)});const r=Adapter.evaluate({obligation:o,route:routeFor(o),context:cx,envelopeRef:{envelopeDigest:a.envelopeDigest,authoritySnapshotRef:a.authoritySnapshotRef,worldBinding:a.worldBinding}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.adapterEvidence.evaluatorCalls,0)});
test('adapter rejects honestly re-signed context with tampered worldBinding',()=>{const a=sealedEnvelope('A'),o=obligation(a),base=contextForObligation(a,o),wb={...a.worldBinding,worldId:'other'},cx=reseal({...base,worldBinding:wb,worldBindingDigest:digest(wb)});const r=Adapter.evaluate({obligation:o,route:routeFor(o),context:cx,envelopeRef:{envelopeDigest:a.envelopeDigest,authoritySnapshotRef:a.authoritySnapshotRef,worldBinding:a.worldBinding}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.adapterEvidence.evaluatorCalls,0)});

// --- Real Foundation output fixtures: shared with the determinism harness ---
const {realFixture,realProof}=require('./v3-candidate5-fixture');
function checkedProof(f){const r=realProof(f);assert(!r.error,JSON.stringify(r.detail));assert.equal(r.decision.decision,'COMMIT_ALLOWED');assert.equal(r.decision.outcome,'PASS');return r}
test('real Foundation output append+commit is atomic and replay exact under external proof root',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root});assert.equal(r.status,'COMMITTED');assert.deepEqual(r.state,f.after);const rp=replay({initialState:f.before,eventLog:r.eventLog,proofRootsByTransaction:{[f.transaction.transactionId]:r0.root}});assert.equal(rp.status,'REPLAY_OK');assert.equal(rp.finalStateDigest,f.after.stateDigest)});
test('replay requires the EXTERNAL proof root and never trusts the event-carried root',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root});assert.equal(r.eventLog[0].physicalProofRoot,r0.root);assert.equal(replay({initialState:f.before,eventLog:r.eventLog}).status,'REPLAY_REJECTED');assert.equal(replay({initialState:f.before,eventLog:r.eventLog,proofRootsByTransaction:{}}).status,'REPLAY_REJECTED')});
test('real event append failure leaves state and log byte-identical',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root,failAppend:true});assert.equal(r.status,'APPEND_FAILED');assert.deepEqual(r.state,f.before);assert.deepEqual(r.eventLog,[])});
test('real commit failure rolls back staged event and state',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root,failCommit:true});assert.equal(r.status,'COMMIT_FAILED');assert.deepEqual(r.state,f.before);assert.deepEqual(r.eventLog,[])});
for(const field of ['sequence','transactionId','beforeStateDigest','afterStateDigest','physicalProof'])test('replay rejects tampered '+field,()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root}),e=structuredClone(r.eventLog[0]);if(field==='sequence')e.sequence=2;else if(field==='physicalProof')e.physicalProof={...e.physicalProof,planDigest:H('9')};else e[field]='tampered';assert.equal(replay({initialState:f.before,eventLog:[e],proofRootsByTransaction:{[f.transaction.transactionId]:r0.root}}).status,'REPLAY_REJECTED')});
test('replay rejects a re-signed forged proof (honest payload and event re-digest)',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root}),e=structuredClone(r.eventLog[0]);const forged={...e.physicalProof,planDigest:H('9'),obligations:e.physicalProof.obligations.map(o=>({...o,v3Reason:'VALID'}))};forged.payloadDigest=digest({...forged,payloadDigest:undefined});e.physicalProof=forged;e.eventDigest=digest({...e,eventDigest:undefined});assert.equal(replay({initialState:f.before,eventLog:[e],proofRootsByTransaction:{[f.transaction.transactionId]:r0.root}}).reason,'UNTRUSTED_PHYSICAL_PROOF')});
test('replay rejects arbitrary honestly sealed state at revision 99',()=>{const f=realFixture(),r0=checkedProof(f),b99={...f.after,revision:99,stateDigest:undefined},s99={...b99,stateDigest:digest(b99)},ev=makeEvent({previousEventDigest:null,sequence:1,transactionId:f.transaction.transactionId,beforeStateDigest:f.before.stateDigest,afterState:s99,physicalProof:r0.proof,expectedProofRoot:r0.root});assert.equal(replay({initialState:f.before,eventLog:[ev],proofRootsByTransaction:{[f.transaction.transactionId]:r0.root}}).status,'REPLAY_REJECTED')});
test('replay rejects arbitrary honestly sealed state at revision+1 under a re-signed event',()=>{const f=realFixture(),r0=checkedProof(f),r=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root}),e=structuredClone(r.eventLog[0]);const bx={...f.after,entities:{e:{entityId:'e',physicalParticipation:'NONE'}},stateDigest:undefined},sx={...bx,stateDigest:digest(bx)};e.afterState=sx;e.afterStateDigest=sx.stateDigest;e.eventDigest=digest({...e,eventDigest:undefined});assert.equal(replay({initialState:f.before,eventLog:[e],proofRootsByTransaction:{[f.transaction.transactionId]:r0.root}}).reason,'PROOF_STATE_BINDING_MISMATCH')});
test('execute rejects an honestly re-signed decision proposing revision 99',()=>{const f=realFixture(),r0=checkedProof(f),b99={...f.after,revision:99,stateDigest:undefined},s99={...b99,stateDigest:digest(b99)},d0={...r0.decision,proposedState:s99,proposedStateDigest:s99.stateDigest},d1={...d0,decisionDigest:digest(d0)};assert.equal(execute({state:f.before,decision:d1,transaction:f.transaction,physicalProof:{...r0.proof,decisionDigest:d1.decisionDigest},expectedProofRoot:r0.root}).status,'REJECTED')});
test('replay rejects missing duplicate and reordered events',()=>{const f=realFixture(),r0=checkedProof(f),one=execute({state:f.before,decision:r0.decision,transaction:f.transaction,physicalProof:r0.proof,expectedProofRoot:r0.root}),map={[f.transaction.transactionId]:r0.root};assert.equal(replay({initialState:f.before,eventLog:[one.event,one.event],proofRootsByTransaction:map}).status,'REPLAY_REJECTED');assert.equal(replay({initialState:f.after,eventLog:[one.event],proofRootsByTransaction:map}).status,'REPLAY_REJECTED');const bx={...f.after,revision:2,stateDigest:undefined},s2={...bx,stateDigest:digest(bx)},d0={...r0.decision,proposedState:s2,proposedStateDigest:s2.stateDigest,beforeStateDigest:f.after.stateDigest},d2={...d0,decisionDigest:digest(d0)},p2={...r0.proof,transactionId:'tx2',decisionDigest:d2.decisionDigest,beforeStateDigest:f.after.stateDigest,proposedStateDigest:s2.stateDigest};p2.payloadDigest=digest({...p2,payloadDigest:undefined});const two=execute({state:f.after,decision:d2,transaction:{transactionId:'tx2'},physicalProof:p2,eventLog:one.eventLog,expectedProofRoot:proofRoot(p2)});assert.equal(replay({initialState:f.before,eventLog:[two.event,one.event],proofRootsByTransaction:{...map,tx2:proofRoot(p2)}}).status,'REPLAY_REJECTED')});
test('real Foundation evidence is deterministic byte-for-byte',()=>{const a=checkedProof(realFixture()),b=checkedProof(realFixture());assert.deepEqual(a.proof,b.proof);assert.equal(a.root,b.root);const f=realFixture(),r1=execute({state:f.before,decision:a.decision,transaction:f.transaction,physicalProof:a.proof,expectedProofRoot:a.root}),r2=execute({state:f.before,decision:b.decision,transaction:f.transaction,physicalProof:b.proof,expectedProofRoot:b.root});assert.deepEqual(r1,r2);assert.equal(digest(r1),digest(r2))});
