'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {digest}=require('../../src/clean-runtime/contracts/canonical');const {contextForObligation}=require('../../src/clean-runtime/v3-authority/authority-envelope');const Adapter=require('../../src/clean-runtime/mutation/v3-authority-adapter');const {execute,replay}=require('./v3-foundation-commit-replay-simulator');
function sealedEnvelope(id){const body={schemaVersion:'v3-authority-envelope/1.0.0',envelopeId:id,worldBinding:{worldId:'w',beforeRevision:0,beforeStateDigest:'a'.repeat(64),proposedRevision:1,proposedStateDigest:'b'.repeat(64),transactionId:'tx',transactionDigest:'c'.repeat(64)},definitions:{},frames:{},bodies:{},contactRegions:{},supportRelations:{},boundaryFeatures:{},authority:{geometryRefs:{},geometryFrameRefs:{},boundaryFeatureRefs:{}},sourceManifest:{sourceKind:'AUTHORITY_REGISTRY_SNAPSHOT',registrySnapshotDigest:'d'.repeat(64),recordDigests:[]}};return Object.freeze({...body,envelopeDigest:digest(body)})}
function obligation(env){const core={schemaVersion:'physical-proof-obligation/1.0.0',obligationId:'V3_SUPPORT:x',capability:'V3_SUPPORT',apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',subjectEntityIds:['e'],relationIds:[],boundaryFeatureIds:[],request:{apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',requestId:'V3_SUPPORT:x'},authorityRequirements:{geometryIds:[],geometryFrameIds:[],bodyIds:[],contactRegionIds:[],supportRelationIds:[],boundaryFeatureIds:[]},beforeDependencyDigest:'a'.repeat(64),proposedDependencyDigest:'b'.repeat(64),authorityEnvelopeDigest:env.envelopeDigest};return Object.freeze({...core,obligationDigest:digest(core)})}
test('mixed-envelope context projection rejects before evaluator',()=>{const a=sealedEnvelope('A'),b=sealedEnvelope('B'),o=obligation(a),cx=contextForObligation(b,o);assert.equal(cx.status,'INCOMPLETE_AUTHORITY');assert.equal(cx.reason,'MIXED_ENVELOPE')});
test('adapter rejects context rebound to another envelope with zero evaluator calls',()=>{const a=sealedEnvelope('A'),b=sealedEnvelope('B'),o=obligation(a),cx=contextForObligation(a,o),routeBody={capability:'V3_SUPPORT',routeState:'PROMOTED',apiVersion:'3.0.0',queryType:o.queryType,evaluatorId:'CLOSED_V3',routeTableDigest:'e'.repeat(64)},route=Object.freeze({...routeBody,routeDigest:digest(routeBody)}),mixed={...cx,envelopeDigest:b.envelopeDigest};mixed.contextDigest=digest({schemaVersion:mixed.schemaVersion,obligationId:mixed.obligationId,envelopeDigest:mixed.envelopeDigest,worldBindingDigest:mixed.worldBindingDigest,context:mixed.context});const r=Adapter.evaluate({obligation:o,route,context:mixed,envelopeRef:{envelopeDigest:a.envelopeDigest}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.adapterEvidence.evaluatorCalls,0)});
function state(rev,n){const body={worldId:'w',revision:rev,value:n};return {...body,stateDigest:digest(body)}}function fixture(){const before=state(0,0),after=state(1,1),decision={decision:'COMMIT_ALLOWED',outcome:'PASS',proposedState:after},transaction={transactionId:'tx'},physicalProof={transactionId:'tx',decision:'COMMIT_ALLOWED',decisionDigest:'f'.repeat(64),planDigest:'1'.repeat(64),routeTableDigest:'2'.repeat(64)};return {before,after,decision,transaction,physicalProof}}
test('synthetic append then commit is atomic and replay exact',()=>{const f=fixture(),r=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof});assert.equal(r.status,'COMMITTED');assert.deepEqual(r.state,f.after);const rp=replay({initialState:f.before,eventLog:r.eventLog});assert.equal(rp.status,'REPLAY_OK');assert.equal(rp.finalStateDigest,f.after.stateDigest)});
test('synthetic event append failure leaves state and log byte-identical',()=>{const f=fixture(),r=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof,failAppend:true});assert.equal(r.status,'APPEND_FAILED');assert.deepEqual(r.state,f.before);assert.deepEqual(r.eventLog,[])});
test('synthetic commit failure rolls back staged event and state',()=>{const f=fixture(),r=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof,failCommit:true});assert.equal(r.status,'COMMIT_FAILED');assert.deepEqual(r.state,f.before);assert.deepEqual(r.eventLog,[])});
for(const field of ['sequence','transactionId','beforeStateDigest','afterStateDigest','physicalProof'])test('replay rejects tampered '+field,()=>{const f=fixture(),r=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof}),e=structuredClone(r.eventLog[0]);if(field==='sequence')e.sequence=2;else if(field==='physicalProof')e.physicalProof={...e.physicalProof,planDigest:'9'.repeat(64)};else e[field]='tampered';const rr=replay({initialState:f.before,eventLog:[e]});assert.equal(rr.status,'REPLAY_REJECTED')});
test('replay rejects missing duplicate and reordered events',()=>{const f=fixture(),one=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof});assert.equal(replay({initialState:f.before,eventLog:[one.event,one.event]}).status,'REPLAY_REJECTED');assert.equal(replay({initialState:f.after,eventLog:[one.event]}).status,'REPLAY_REJECTED');const secondAfter=state(2,2),d2={...f.decision,proposedState:secondAfter},two=execute({state:f.after,decision:d2,transaction:{transactionId:'tx2'},physicalProof:{...f.physicalProof,transactionId:'tx2'},eventLog:one.eventLog});assert.equal(replay({initialState:f.before,eventLog:[two.event,one.event]}).status,'REPLAY_REJECTED')});
test('synthetic evidence is deterministic byte-for-byte',()=>{const f=fixture(),a=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof}),b=execute({state:f.before,decision:f.decision,transaction:f.transaction,physicalProof:f.physicalProof});assert.deepEqual(a,b);assert.equal(digest(a),digest(b))});
