'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {digest}=require('../../src/clean-runtime/contracts/canonical');const {buildAuthorityEnvelope}=require('../../src/clean-runtime/v3-authority/authority-envelope-builder');const Router=require('../../src/clean-runtime/mutation/physical-capability-router');const {computeImpact,plan}=require('../../src/clean-runtime/mutation/physical-proof-planner');const {contextForObligation}=require('../../src/clean-runtime/v3-authority/authority-envelope');const Adapter=require('../../src/clean-runtime/mutation/v3-authority-adapter');
const seal=(x,f='digest')=>({...x,[f]:digest(x)}),pin=(id,k,r)=>({[k]:id,revision:r.revision,digest:r.digest});
function fixture({missingOpening=false}={}){const frame=seal({frameId:'w',frameKind:'WORLD',parentFrameRef:null,translationMicrounits:['0','0','0'],rotationQuaternionRatio:['1','0','0','0'],revision:1,provenance:'HOSTILE'}),g=seal({geometryId:'g',revision:1,localFrameId:'w',representationKind:'FINITE_PLANAR_REGION'}),body=seal({bodyId:'b',revision:1}),cr=seal({contactRegionId:'c',revision:1}),sr=seal({relationId:'r',revision:1}),bf=seal({boundaryFeatureId:'bf',revision:1,localFrameRef:pin('w','frameId',frame),solidGeometryRefs:[],openingRegionRefs:missingOpening?[{geometryId:'MISSING_OPENING',revision:1,digest:'a'.repeat(64)}]:[]});const authority={geometryRefs:{g:pin('g','geometryId',g)},geometryFrameRefs:{g:pin('w','frameId',frame)},bodyRefs:{b:pin('b','bodyId',body)},contactRegionRefs:{c:pin('c','contactRegionId',cr)},supportRelationRefs:{r:pin('r','relationId',sr)},boundaryFeatureRefs:{bf:pin('bf','boundaryFeatureId',bf)}};let registry={authoritySnapshotId:'a',revision:1,definitions:{g},frames:{w:frame},bodies:{b:body},contactRegions:{c:cr},supportRelations:{r:sr},boundaryFeatures:{bf},authority};registry={...registry,registrySnapshotDigest:digest(registry)};const b0={schemaVersion:'2.0.0',worldId:'world',revision:0,entities:{e:{entityId:'e'}},physicalRelations:[],supportRelations:[]},before={...b0,stateDigest:digest(b0)},a0={...b0,revision:1},after={...a0,stateDigest:digest(a0)},c0={commandId:'cmd',type:'SetTransform',expectedWorldRevision:0,entityId:'e',transform:{position:[0,0,0]}},cmd={...c0,commandDigest:digest(c0)},t0={transactionId:'tx',expectedWorldRevision:0,commands:[cmd]},tx={...t0,transactionDigest:digest(t0)},impact=computeImpact({beforeState:before,proposedState:after,transaction:tx});return {registry,before,after,tx,impact}}
const build=f=>buildAuthorityEnvelope({registrySnapshot:f.registry,beforeState:f.before,proposedState:f.after,transaction:f.tx,impactSet:f.impact});
test('ADV-01 missing opening membership target is rejected before READY',()=>{const r=build(fixture({missingOpening:true}));assert.equal(r.status,'REJECTED');assert.equal(r.reason,'INCOMPLETE_AUTHORITY')});
test('ADV-02 exact promoted identities cannot be swapped',()=>{const base=structuredClone(Router.ROUTE_TABLE);delete base.routeTableDigest;base.routes.V3_SUPPORT.state='NON_PROMOTED';base.routes.V3_SUPPORT.evaluatorId=null;base.routes.V3_BODY_VS_BODY.state='PROMOTED';base.routes.V3_BODY_VS_BODY.evaluatorId='CLOSED_V3';const mutant={...base,routeTableDigest:digest(base)};assert.throws(()=>Router.validateRouteTable(mutant),/INVALID_ROUTE_TUPLE/)});
test('ADV-03 caller requirements cannot create an obligation',()=>{const f=fixture(),e=build(f).envelope,p=plan({beforeState:f.before,proposedState:f.after,transaction:f.tx,envelope:e,requirementsByEntity:{e:[{capability:'V3_CONTAINMENT',request:{apiVersion:'3.0.0',queryType:'BODY_CONTAINMENT_IN_ALLOWED_REGION',requestId:'caller-id'},authorityRequirements:{}}]}});assert.equal(p.status,'PLAN_REJECTED');assert.equal(p.reason,'INCOMPLETE_PROOF_REQUIREMENTS')});
test('ADV-04 physical zero obligations fail closed',()=>{const f=fixture(),e=build(f).envelope,p=plan({beforeState:f.before,proposedState:f.after,transaction:f.tx,envelope:e});assert.equal(p.reason,'INCOMPLETE_PROOF_REQUIREMENTS')});
test('ADV-05 forged registry digest rejects',()=>{const f=fixture();f.registry.registrySnapshotDigest='0'.repeat(64);assert.equal(build(f).reason,'INVALID_REGISTRY_SNAPSHOT')});
test('ADV-06 missing geometry pin rejects',()=>{const f=fixture();delete f.registry.authority.geometryRefs.g;f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});assert.equal(build(f).reason,'INCOMPLETE_AUTHORITY')});
test('ADV-07 missing frame pin rejects',()=>{const f=fixture();delete f.registry.authority.geometryFrameRefs.g;f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});assert.equal(build(f).reason,'INCOMPLETE_AUTHORITY')});
test('ADV-08 wrong query does not route',()=>assert.equal(Router.route({capability:'V3_SUPPORT',apiVersion:'3.0.0',queryType:'BODY_VS_BODY'}).reason,'QUERY_CAPABILITY_MISMATCH'));
for(const c of ['V3_BODY_VS_BODY','V3_WORLD_SOLID','V3_OBSTACLE'])test('ADV locked '+c,()=>{const r=Router.ROUTE_TABLE.routes[c];assert.equal(Router.route({capability:c,apiVersion:r.apiVersion,queryType:r.queryType}).reason,'NON_PROMOTED_CAPABILITY')});
for(const v of ['3.0.0 ','03.0.0','4.0.0',null,undefined])test('ADV version '+String(v),()=>{const r=Router.ROUTE_TABLE.routes.V3_SUPPORT;assert.notEqual(Router.route({capability:'V3_SUPPORT',apiVersion:v,queryType:r.queryType}).status,'ROUTED')});

test('ADV-09 envelope bound to a foreign transaction digest rejects at planning',()=>{const f=fixture(),e0={worldBinding:{transactionDigest:'f'.repeat(64),beforeStateDigest:f.before.stateDigest,proposedStateDigest:f.after.stateDigest}},e={...e0,envelopeDigest:digest(e0)},p=plan({beforeState:f.before,proposedState:f.after,transaction:f.tx,envelope:e});assert.equal(p.status,'PLAN_REJECTED');assert.equal(p.reason,'STALE_OR_INVALID_INPUT');assert.equal(p.evidence.stage,'envelope')});
test('ADV-10 opening backref mismatch rejects before READY',()=>{const f=fixture();const bf2=seal({...f.registry.boundaryFeatures.bf,digest:undefined,openingRegionRefs:[{geometryId:'g',revision:1,digest:f.registry.definitions.g.digest}]});f.registry.boundaryFeatures.bf=bf2;f.registry.authority.boundaryFeatureRefs.bf=pin('bf','boundaryFeatureId',bf2);f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});const r=build(f);assert.equal(r.status,'REJECTED');assert.equal(r.reason,'STALE_AUTHORITY');assert.equal(r.evidence.stage,'opening-backref')});
test('ADV-11 stale compound child digest rejects before READY',()=>{const f=fixture();const comp=seal({geometryId:'comp',revision:1,localFrameId:'w',representationKind:'COMPOUND',shape:{children:[{geometryId:'g',revision:1,digest:'a'.repeat(64)}]}});f.registry.definitions.comp=comp;f.registry.authority.geometryRefs.comp=pin('comp','geometryId',comp);f.registry.authority.geometryFrameRefs.comp=pin('w','frameId',f.registry.frames.w);f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});const r=build(f);assert.equal(r.status,'REJECTED');assert.equal(r.reason,'STALE_AUTHORITY');assert.equal(r.evidence.stage,'compound-child')});
test('ADV-12 context projection and adapter enforce the full authority requirement set',()=>{const f=fixture(),e=build(f).envelope,core={schemaVersion:'physical-proof-obligation/1.0.0',obligationId:'V3_SUPPORT:adv12',capability:'V3_SUPPORT',apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',subjectEntityIds:['e'],relationIds:[],boundaryFeatureIds:[],request:{apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',requestId:'V3_SUPPORT:adv12'},authorityRequirements:{geometryIds:['MISSING'],geometryFrameIds:[],bodyIds:[],contactRegionIds:[],supportRelationIds:[],boundaryFeatureIds:[]},beforeDependencyDigest:'a'.repeat(64),proposedDependencyDigest:'b'.repeat(64),authorityEnvelopeDigest:e.envelopeDigest},o={...core,obligationDigest:digest(core)};const cx=contextForObligation(e,o);assert.equal(cx.status,'INCOMPLETE_AUTHORITY');assert.equal(cx.reason,'MISSING_PROJECTION_DATA');const req={geometryIds:['g'],geometryFrameIds:[],bodyIds:[],contactRegionIds:[],supportRelationIds:[],boundaryFeatureIds:[]},core2={...core,obligationId:'V3_SUPPORT:adv12b',request:{...core.request,requestId:'V3_SUPPORT:adv12b'},authorityRequirements:req},o2={...core2,obligationDigest:digest(core2)};const ctxBody={schemaVersion:'v3-obligation-context/1.1.0',obligationId:o2.obligationId,sourceEnvelopeDigest:e.envelopeDigest,authoritySnapshotRef:e.authoritySnapshotRef,authoritySnapshotRefDigest:digest(e.authoritySnapshotRef),worldBinding:e.worldBinding,worldBindingDigest:digest(e.worldBinding),context:{frames:[],definitions:{},bodies:{},contactRegions:{},supportRelations:{},boundaryFeatures:{},authoritativeGeometryRefs:{},authoritativeGeometryFrameRefs:{},authoritativeBoundaryFeatureRefs:{}}},stripped={status:'READY',...ctxBody,contextDigest:digest(ctxBody)},routeBody={capability:'V3_SUPPORT',routeState:'PROMOTED',apiVersion:'3.0.0',queryType:'CONTACT_REGION_VS_SUPPORT_SURFACE',evaluatorId:'CLOSED_V3',routeTableDigest:'e'.repeat(64)},route={...routeBody,routeDigest:digest(routeBody)};const r=Adapter.evaluate({obligation:o2,route,context:stripped,envelopeRef:{envelopeDigest:e.envelopeDigest}});assert.equal(r.outcome,'UNKNOWN');assert.equal(r.adapterEvidence.evaluatorCalls,0);assert.equal(r.adapterEvidence.validationStage,'context')});
test('ADV-13 obligation identity is content-bound and requestId equals obligationId',()=>{const entities={a:{entityId:'a',physicalParticipation:'ACTIVE',containmentAssignments:[{bodyGeometryRef:{geometryId:'ga',revision:1,digest:'c'.repeat(64),localFrameRef:{frameId:'w',revision:1,digest:'b'.repeat(64)}},targetGeometryRef:{geometryId:'shared',revision:1,digest:'a'.repeat(64),localFrameRef:{frameId:'w',revision:1,digest:'b'.repeat(64)}}}]}},st=(rev,xs)=>{const x={schemaVersion:'2.0.0',worldId:'w',revision:rev,entities:xs,physicalRelations:[],supportRelations:[]};return {...x,stateDigest:digest(x)}},before=st(0,entities),after=st(1,entities),c0={commandId:'ca',type:'SetTransform',expectedWorldRevision:0,entityId:'a',transform:{position:[0,0,0]}},ca={...c0,commandDigest:digest(c0)},t0={transactionId:'tx',expectedWorldRevision:0,commands:[ca]},t={...t0,transactionDigest:digest(t0)},e0={worldBinding:{transactionDigest:t.transactionDigest,beforeStateDigest:before.stateDigest,proposedStateDigest:after.stateDigest}},e={...e0,envelopeDigest:digest(e0)},p=plan({beforeState:before,proposedState:after,transaction:t,envelope:e});assert.equal(p.status,'READY');assert.equal(p.plan.obligations.length,1);const o=p.plan.obligations[0];assert.equal(o.request.requestId,o.obligationId);assert.equal(o.obligationDigest,digest({...o,obligationDigest:undefined}));const body={...o,obligationDigest:undefined};delete body.request;assert.notEqual(digest(body),o.obligationDigest)});
