'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {digest}=require('../../src/clean-runtime/contracts/canonical');const {buildAuthorityEnvelope}=require('../../src/clean-runtime/v3-authority/authority-envelope-builder');const {route,ROUTE_TABLE}=require('../../src/clean-runtime/mutation/physical-capability-router');const {computeImpact,plan}=require('../../src/clean-runtime/mutation/physical-proof-planner');
const seal=(x,f='digest')=>({...x,[f]:digest(x)});function fixture(){const frame=seal({frameId:'w',frameKind:'WORLD',parentFrameRef:null,translationMicrounits:['0','0','0'],rotationQuaternionRatio:['1','0','0','0'],revision:1,provenance:'TEST'}),g=seal({geometryId:'g',revision:1,localFrameId:'w',representationKind:'FINITE_PLANAR_REGION'}),body=seal({bodyId:'b',revision:1}),cr=seal({contactRegionId:'c',revision:1}),sr=seal({relationId:'r',revision:1}),bf=seal({boundaryFeatureId:'bf',revision:1});const pin=(id,k,r)=>({[k]:id,revision:r.revision,digest:r.digest});const authority={geometryRefs:{g:pin('g','geometryId',g)},geometryFrameRefs:{g:pin('w','frameId',frame)},bodyRefs:{b:pin('b','bodyId',body)},contactRegionRefs:{c:pin('c','contactRegionId',cr)},supportRelationRefs:{r:pin('r','relationId',sr)},boundaryFeatureRefs:{bf:pin('bf','boundaryFeatureId',bf)}};let registry={authoritySnapshotId:'a',revision:1,definitions:{g},frames:{w:frame},bodies:{b:body},contactRegions:{c:cr},supportRelations:{r:sr},boundaryFeatures:{bf},authority};registry={...registry,registrySnapshotDigest:digest(registry)};const before0={schemaVersion:'2.0.0',worldId:'world',revision:0,entities:{e:{entityId:'e'}},physicalRelations:[],supportRelations:[],provenance:'TEST'},before={...before0,stateDigest:digest(before0)},after0={...before0,revision:1},after={...after0,stateDigest:digest(after0)};const c0={commandId:'cmd',type:'SetTransform',expectedWorldRevision:0,entityId:'e',transform:{position:[0,0,0]}},cmd={...c0,commandDigest:digest(c0)},t0={transactionId:'tx',expectedWorldRevision:0,commands:[cmd]},tx={...t0,transactionDigest:digest(t0)},impact=computeImpact({beforeState:before,proposedState:after,transaction:tx});return {registry,before,after,tx,impact}}
function build(f=fixture()){return buildAuthorityEnvelope({registrySnapshot:f.registry,beforeState:f.before,proposedState:f.after,transaction:f.tx,impactSet:f.impact})}
test('H01 missing registry rejects',()=>assert.equal(buildAuthorityEnvelope({}).status,'REJECTED'));
test('H02 forged registry digest rejects',()=>{const f=fixture();f.registry.registrySnapshotDigest='0'.repeat(64);assert.equal(build(f).reason,'INVALID_REGISTRY_SNAPSHOT')});
test('H03 world mismatch rejects',()=>{const f=fixture();const a={...f.after,worldId:'other'};a.stateDigest=digest({...a,stateDigest:undefined});f.after=a;assert.equal(build(f).reason,'INVALID_WORLD_BINDING')});
test('H04 forged proposed state rejects',()=>{const f=fixture();f.after.stateDigest='1'.repeat(64);assert.equal(build(f).reason,'INVALID_WORLD_BINDING')});
test('H05 forged transaction rejects',()=>{const f=fixture();f.tx.transactionDigest='2'.repeat(64);assert.equal(build(f).reason,'INVALID_TRANSACTION_BINDING')});
test('H06 missing independent geometry pin rejects',()=>{const f=fixture();delete f.registry.authority.geometryRefs.g;f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});assert.equal(build(f).reason,'INCOMPLETE_AUTHORITY')});
test('H07 missing independent frame pin rejects',()=>{const f=fixture();delete f.registry.authority.geometryFrameRefs.g;f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});assert.equal(build(f).reason,'INCOMPLETE_AUTHORITY')});
test('H08 forged geometry frame pin rejects stale',()=>{const f=fixture();f.registry.authority.geometryFrameRefs.g.digest='3'.repeat(64);f.registry.registrySnapshotDigest=digest({...f.registry,registrySnapshotDigest:undefined});assert.equal(build(f).reason,'STALE_AUTHORITY')});
test('H09 ready envelope is deeply frozen',()=>{const r=build();assert.equal(r.status,'READY');assert(Object.isFrozen(r.envelope));assert(Object.isFrozen(r.envelope.authority))});
test('H10 unknown capability never routes',()=>assert.equal(route({capability:'NOPE',apiVersion:'3.0.0',queryType:'X'}).reason,'UNKNOWN_CAPABILITY'));
for(const [i,v] of ['3.0.0 ','03.0.0','4.0.0',null,undefined].entries())test('H'+(11+i)+' unknown version '+String(v),()=>{const r=ROUTE_TABLE.routes.V3_SUPPORT;assert.notEqual(route({capability:'V3_SUPPORT',apiVersion:v,queryType:r.queryType}).status,'ROUTED')});
test('H16 wrong query mismatch',()=>assert.equal(route({capability:'V3_SUPPORT',apiVersion:'3.0.0',queryType:'BODY_VS_BODY'}).reason,'QUERY_CAPABILITY_MISMATCH'));
for(const [i,c] of ['V3_BODY_VS_BODY','V3_WORLD_SOLID','V3_OBSTACLE'].entries())test('H'+(17+i)+' '+c+' locked',()=>{const r=ROUTE_TABLE.routes[c];assert.equal(route({capability:c,apiVersion:r.apiVersion,queryType:r.queryType}).reason,'NON_PROMOTED_CAPABILITY')});
test('H20 impact direct subject deterministic',()=>{const f=fixture();assert.deepEqual(f.impact.directEntityIds,['e'])});
test('H21 physical zero obligations rejects',()=>{const f=fixture(),e=build(f).envelope;assert.equal(plan({beforeState:f.before,proposedState:f.after,transaction:f.tx,envelope:e,requirementsByEntity:{}}).reason,'INCOMPLETE_PROOF_REQUIREMENTS')});
test('H22 NON_PROMOTED obligation is not omitted',()=>{const f=fixture(),e=build(f).envelope,p=plan({beforeState:f.before,proposedState:f.after,transaction:f.tx,envelope:e,requirementsByEntity:{e:[{capability:'V3_BODY_VS_BODY',request:{apiVersion:'3.0.0',queryType:'BODY_VS_BODY',requestId:'x'}}]}});assert.equal(p.status,'READY');assert.equal(p.plan.obligations[0].capability,'V3_BODY_VS_BODY')});
