(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.KoRishonAdaptiveRuntime=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='nextgen-60-64.1';
const DEFAULT_BUDGETS=Object.freeze({firstInteractiveMs:2500,scenarioLoadMs:4000,inputResponseMs:100,renderFps:45,memoryMb:384,assetLoadMs:2500,aiLatencyMs:2000});
const TIERS=Object.freeze({low:{pixelRatio:1,antialias:false,shadows:false,shadowMapSize:512,geometryDetail:.55,maxConcurrentAssets:2},medium:{pixelRatio:1.25,antialias:true,shadows:true,shadowMapSize:1024,geometryDetail:.75,maxConcurrentAssets:3},high:{pixelRatio:1.7,antialias:true,shadows:true,shadowMapSize:2048,geometryDetail:1,maxConcurrentAssets:4}});
const clone=v=>JSON.parse(JSON.stringify(v));
function safe(test,fallback=false){try{return test()}catch(_){return fallback}}
function storageAvailable(env){return safe(()=>{if(!env.localStorage)return false;const k='__ko_capability__';env.localStorage.setItem(k,'1');env.localStorage.removeItem(k);return true})}
function detectCapabilities(env=globalThis){const nav=env.navigator||{},doc=env.document;let webgl=false,webgl2=false;if(doc?.createElement){const c=doc.createElement('canvas');webgl2=!!safe(()=>c.getContext('webgl2'));webgl=webgl2||!!safe(()=>c.getContext('webgl')||c.getContext('experimental-webgl'))}const memoryGb=Number(nav.deviceMemory)||null,cores=Number(nav.hardwareConcurrency)||null,connection=nav.connection||nav.mozConnection||nav.webkitConnection||null;const mobile=!!safe(()=>env.matchMedia?.('(pointer: coarse)').matches)||/Android|iPhone|iPad|Mobile/i.test(nav.userAgent||'');const deviceClass=(mobile||memoryGb&&memoryGb<=4||cores&&cores<=4)?'low':(memoryGb&&memoryGb>=8&&cores&&cores>=8?'high':'medium');return {version:VERSION,webgpu:!!nav.gpu,webgl,webgl2,speechRecognition:!!(env.SpeechRecognition||env.webkitSpeechRecognition),speechSynthesis:!!env.speechSynthesis,audio:!!(env.AudioContext||env.webkitAudioContext),storage:storageAvailable(env),network:{online:nav.onLine!==false,effectiveType:connection?.effectiveType||'unknown',saveData:!!connection?.saveData,downlink:Number(connection?.downlink)||null},memoryGb,cores,mobile,deviceClass,battery:{supported:typeof nav.getBattery==='function',level:null,charging:null}}}
function chooseQuality(profile,telemetry={}){if(!profile.webgl)return 'low';let score=profile.deviceClass==='high'?2:profile.deviceClass==='medium'?1:0;if(profile.network.saveData||profile.network.effectiveType==='2g'||profile.network.effectiveType==='slow-2g')score=0;if(profile.battery.level!==null&&profile.battery.level<.2&&!profile.battery.charging)score=0;if(Number.isFinite(telemetry.fps)){if(telemetry.fps<30)score=0;else if(telemetry.fps<45)score=Math.min(score,1)}if(Number.isFinite(telemetry.memoryMb)&&telemetry.memoryMb>DEFAULT_BUDGETS.memoryMb)score=0;return ['low','medium','high'][score]}
class PerformanceBudget{constructor(budgets={}){this.budgets=Object.freeze({...DEFAULT_BUDGETS,...budgets});this.metrics={};this.violations=[]}record(name,value,at=Date.now()){if(!Number.isFinite(value))return false;this.metrics[name]={value,at};const budget=this.budgets[name];const ok=budget===undefined?true:(name==='renderFps'?value>=budget:value<=budget);if(!ok)this.violations.push({name,value,budget,at});return ok}snapshot(){return {version:VERSION,budgets:{...this.budgets},metrics:clone(this.metrics),violations:clone(this.violations)}}}
class AssetStreamQueue{constructor({concurrency=3,onEvent=()=>{}}={}){this.concurrency=Math.max(1,concurrency|0);this.onEvent=onEvent;this.queue=[];this.active=0;this.sequence=0}enqueue({id,priority='optional',load}){if(typeof load!=='function')throw new Error('ASSET_LOAD_REQUIRED');const weights={current:0,nearby:1,optional:2};const item={id:String(id),priority:weights[priority]===undefined?'optional':priority,order:this.sequence++,load};this.queue.push(item);this.queue.sort((a,b)=>weights[a.priority]-weights[b.priority]||a.order-b.order);this.onEvent({type:'queued',id:item.id,priority:item.priority});this._drain();return item.id}_drain(){while(this.active<this.concurrency&&this.queue.length){const item=this.queue.shift();this.active++;this.onEvent({type:'started',id:item.id,priority:item.priority});Promise.resolve().then(item.load).then(value=>this.onEvent({type:'loaded',id:item.id,priority:item.priority,value}),error=>this.onEvent({type:'failed',id:item.id,priority:item.priority,error:String(error?.message||error)})).finally(()=>{this.active--;this._drain()})}}}
class AdaptiveQuality{constructor(profile,budget,onChange=()=>{}){this.profile=profile;this.budget=budget;this.onChange=onChange;this.tier=chooseQuality(profile);this.samples=[];this.lastChange=0}sample(frameMs,now=Date.now()){if(!Number.isFinite(frameMs)||frameMs<=0)return this.tier;this.samples.push(frameMs);if(this.samples.length>60)this.samples.shift();if(this.samples.length<30)return this.tier;const avg=this.samples.reduce((a,b)=>a+b,0)/this.samples.length,fps=1000/avg;this.budget.record('renderFps',fps,now);const next=chooseQuality(this.profile,{fps,memoryMb:memoryUsageMb()});if(next!==this.tier&&now-this.lastChange>=3000){const previous=this.tier;this.tier=next;this.lastChange=now;this.onChange(next,TIERS[next],previous)}return this.tier}}
function memoryUsageMb(env=globalThis){const bytes=env.performance?.memory?.usedJSHeapSize;return Number.isFinite(bytes)?bytes/1048576:null}
function degradationPlan(profile){return {renderer:profile.webgl?'webgl':'visual-fallback',intent:profile.webgpu?'webgpu':'local-deterministic',input:profile.speechRecognition?'speech-and-text':'text',audio:profile.audio?'audio':'visual-cues',storage:profile.storage?'persistent':'session',network:profile.network.online?'online':'offline-safe'}}
function createRuntime(env=globalThis,options={}){const profile=detectCapabilities(env),budget=new PerformanceBudget(options.budgets),started=env.performance?.now?.()||0;const events=[];const quality=new AdaptiveQuality(profile,budget,(tier,settings,previous)=>{events.push({type:'quality',tier,previous});options.onQualityChange?.(tier,settings,previous)});const stream=new AssetStreamQueue({concurrency:TIERS[quality.tier].maxConcurrentAssets,onEvent:e=>events.push({...e,value:undefined})});const runtime={version:VERSION,profile,budget,quality,stream,degradation:degradationPlan(profile),events,markInteractive(at=env.performance?.now?.()||0){return budget.record('firstInteractiveMs',Math.max(0,at-started))},recordInput(ms){return budget.record('inputResponseMs',ms)},recordAsset(ms){return budget.record('assetLoadMs',ms)},recordAi(ms){return budget.record('aiLatencyMs',ms)},snapshot(){return {version:VERSION,profile:clone(profile),quality:quality.tier,settings:{...TIERS[quality.tier]},degradation:{...runtime.degradation},performance:budget.snapshot(),stream:{active:stream.active,queued:stream.queue.map(x=>({id:x.id,priority:x.priority}))},events:clone(events)}}};if(profile.battery.supported)safe(()=>env.navigator.getBattery().then(b=>{profile.battery.level=b.level;profile.battery.charging=b.charging}));return runtime}
return {VERSION,DEFAULT_BUDGETS,TIERS,detectCapabilities,chooseQuality,PerformanceBudget,AssetStreamQueue,AdaptiveQuality,degradationPlan,createRuntime,memoryUsageMb};
});
