(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.KoRishonExplainability=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.0.0-nextgen-90-93';
const clone=v=>JSON.parse(JSON.stringify(v));
const stable=v=>{if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(stable).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'};
const hash=v=>{let h=2166136261,x=stable(v);for(let i=0;i<x.length;i++){h^=x.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')};
function invariant(ok,code){if(!ok)throw new Error(code)}
const CATEGORY_ORDER=['safety','assessment','criticalActions','communication','timing','criticalErrors','hints'];
const CATEGORY_LABELS={safety:'בטיחות',assessment:'הערכה',criticalActions:'פעולות קריטיות',communication:'תקשורת',timing:'תזמון',criticalErrors:'שגיאות קריטיות',hints:'רמזים'};
const DEFAULT_CATEGORY={safe:'safety',response:'assessment',breath:'assessment',pulse:'assessment',spo2:'assessment',bp:'assessment',glucose:'assessment',strokeScreen:'assessment',chokingAssess:'assessment',substance:'assessment',seizureTime:'timing',call:'communication',cpr:'criticalActions',aed:'criticalActions'};
function allocate(points,count){if(!count)return[];const base=Math.floor(points/count),extra=points-base*count;return Array.from({length:count},(_,i)=>base+(i<extra?1:0))}
function normalizeSession(input){invariant(input&&input.mode==='training','TRAINING_MODE_REQUIRED');invariant(Array.isArray(input.protocol)&&input.protocol.length,'PROTOCOL_REQUIRED');const keys=new Set(),protocol=input.protocol.map((p,i)=>{invariant(p&&p.key&&!keys.has(p.key),'PROTOCOL_KEY_INVALID');keys.add(p.key);return{key:String(p.key),label:String(p.label||p.key),category:CATEGORY_ORDER.includes(p.category)?p.category:(DEFAULT_CATEGORY[p.key]||'criticalActions'),order:i}});const actions=(input.actions||[]).map((a,i)=>{invariant(a&&keys.has(a.key)&&Number.isFinite(a.timeMs)&&a.timeMs>=0,'ACTION_INVALID');return{key:String(a.key),timeMs:a.timeMs,sequence:Number.isInteger(a.sequence)?a.sequence:i,source:a.source||'actual'}}).sort((a,b)=>a.timeMs-b.timeMs||a.sequence-b.sequence||a.key.localeCompare(b.key));return{mode:'training',protocol,actions,penalties:(input.penalties||[]).map((p,i)=>({id:String(p.id||`penalty-${i}`),label:String(p.label||p),points:-Math.abs(Number(p.points==null?5:p.points)||0)})),hints:(input.hints||[]).map((p,i)=>({id:String(p.id||`hint-${i}`),label:String(p.label||p),points:-Math.abs(Number(p.points==null?4:p.points)||0)})),durationMs:Math.max(0,Number(input.durationMs)||0),sourceIntegrity:clone(input.sourceIntegrity||null)}}
function scoreSession(input){const s=normalizeSession(input),weights=allocate(100,s.protocol.length),first=new Map();for(const a of s.actions)if(!first.has(a.key))first.set(a.key,a);const rows=[];s.protocol.forEach((p,i)=>{const a=first.get(p.key);if(a)rows.push({id:`protocol:${p.key}`,category:p.category,label:p.label,points:weights[i],timeMs:a.timeMs,source:a.source,reason:`הושלם ב-${Math.round(a.timeMs/1000)} שנ׳`})});for(const p of s.penalties)rows.push({id:p.id,category:'criticalErrors',label:p.label,points:p.points,reason:'הפחתה מתועדת'});for(const p of s.hints)rows.push({id:p.id,category:'hints',label:p.label,points:p.points,reason:'רמז שנצרך'});const unclamped=rows.reduce((n,r)=>n+r.points,0),total=Math.max(0,Math.min(100,unclamped));if(total!==unclamped)rows.push({id:'score:boundary',category:unclamped<0?'criticalErrors':'criticalActions',label:'גבול ציון 0–100',points:total-unclamped,reason:'התאמת גבול דטרמיניסטית'});const categories=CATEGORY_ORDER.map(key=>({key,label:CATEGORY_LABELS[key],points:rows.filter(r=>r.category===key).reduce((n,r)=>n+r.points,0),details:rows.filter(r=>r.category===key)}));const result={version:VERSION,total,categories,rows,completed:[...first.keys()],missing:s.protocol.filter(p=>!first.has(p.key)).map(clone),durationMs:s.durationMs};result.digest=hash(result);return result}
function simulateAction(input,action){const s=normalizeSession(input);invariant(action&&s.protocol.some(p=>p.key===action.key),'ACTION_NOT_IN_PROTOCOL');const before=scoreSession(s);if(s.actions.some(a=>a.key===action.key))return{action:clone(action),before,after:before,delta:0,alreadyCompleted:true,medicalStateChanged:false};const branch=clone(s);branch.actions.push({key:action.key,timeMs:Number.isFinite(action.timeMs)?action.timeMs:s.durationMs,sequence:branch.actions.length,source:'score-simulation'});const after=scoreSession(branch);return{action:clone(action),before,after,delta:after.total-before.total,alreadyCompleted:false,medicalStateChanged:false,branchDigest:after.digest}}
function branchAt(input,cutoffMs,action){const s=normalizeSession(input);invariant(Number.isFinite(cutoffMs)&&cutoffMs>=0,'CUTOFF_INVALID');invariant(action&&s.protocol.some(p=>p.key===action.key),'ACTION_NOT_IN_PROTOCOL');const actual=scoreSession(s),branch=clone(s);branch.actions=branch.actions.filter(a=>a.timeMs<=cutoffMs);if(!branch.actions.some(a=>a.key===action.key))branch.actions.push({key:action.key,timeMs:cutoffMs,sequence:branch.actions.length,source:'what-if'});branch.durationMs=Math.max(branch.durationMs,cutoffMs);const counterfactual=scoreSession(branch);return{cutoffMs,action:clone(action),historicalActions:branch.actions.filter(a=>a.timeMs<=cutoffMs).map(clone),actual,counterfactual,delta:counterfactual.total-actual.total,medicalStateChanged:false,sourceIntegrity:s.sourceIntegrity,branchDigest:counterfactual.digest}}
function compareReplay(input,request){const branch=branchAt(input,request.cutoffMs,request.action),actualActions=normalizeSession(input).actions;return{...branch,actualTimeline:actualActions,counterfactualTimeline:branch.historicalActions,differences:{added:branch.historicalActions.filter(x=>!actualActions.some(a=>a.key===x.key&&a.timeMs===x.timeMs)),removed:actualActions.filter(x=>!branch.historicalActions.some(a=>a.key===x.key&&a.timeMs===x.timeMs))},labels:{actual:'מה שקרה',counterfactual:'מה היה קורה אילו'},readOnly:true}}
return{VERSION,CATEGORY_ORDER,CATEGORY_LABELS,normalizeSession,scoreSession,simulateAction,branchAt,compareReplay};
});
