(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./core.js'):root.KoRishonNextGen,typeof module==='object'&&module.exports?require('./event-bus.js'):root.KoRishonEventBus,typeof module==='object'&&module.exports?require('./recovery.js'):root.KoRishonRecovery);if(typeof module==='object'&&module.exports)module.exports=api;root.KoRishonInternalApi=api;})(typeof globalThis!=='undefined'?globalThis:this,function(core,busApi,recoveryApi){
'use strict';
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
class SimulationApi{
 constructor({skillsProvider=()=>[],progressProvider=()=>({}),clock=()=>0,eventBus,recovery}={}){this.skillsProvider=skillsProvider;this.progressProvider=progressProvider;this.clock=clock;this.bus=eventBus||new busApi.EventBus({clock});this.recovery=recovery||new recoveryApi.RecoveryManager({eventBus:this.bus});this.sessions=new Map();this.counter=0}
 response(status,body){return{status,body:clone(body)}}
 start(body={}){try{const sim=core.createSimulation(body),id=body.simulationId||`simulation:${String(this.counter++).padStart(6,'0')}`;if(this.sessions.has(id))return this.response(409,{error:'SIMULATION_EXISTS'});this.sessions.set(id,{sim,scenario:clone(body.scenario),seed:body.seed,finished:false});return this.response(201,{simulationId:id,state:sim.snapshot()})}catch(error){return this.response(400,{error:String(error.message||error)})}}
 get(id){const session=this.sessions.get(id);if(!session)throw Object.assign(new Error('SIMULATION_NOT_FOUND'),{status:404});return session}
 action(body={}){let session;try{session=this.get(body.simulationId)}catch(e){return this.response(e.status||400,{error:e.message})}if(session.finished)return this.response(409,{error:'SIMULATION_FINISHED'});const before=session.sim.medical.snapshot();this.bus.publish('ACTION_SUBMITTED',{simulationId:body.simulationId,intent:body.request&&body.request.intent});const result=this.recovery.execute('ACTION',()=>session.sim.dispatch(body.request,body.context||{}),{context:{simulationId:body.simulationId}});if(!result.ok)return this.response(409,{error:result.error,state:before});const after=session.sim.medical.snapshot();if(JSON.stringify(before)!==JSON.stringify(after)){this.bus.publish('STATE_CHANGED',{simulationId:body.simulationId,before,after});if(after.condition<before.condition)this.bus.publish('PATIENT_DETERIORATED',{simulationId:body.simulationId,before:before.condition,after:after.condition})}if(body.request&&body.request.intent==='hint')this.bus.publish('HINT_USED',{simulationId:body.simulationId});return this.response(200,{result:result.value,state:after,recovered:result.recovered})}
 state(id){try{return this.response(200,{simulationId:id,state:this.get(id).sim.snapshot()})}catch(e){return this.response(e.status||400,{error:e.message})}}
 finish(body={}){try{const session=this.get(body.simulationId);if(!session.finished){session.finished=true;this.bus.publish('SCENARIO_COMPLETED',{simulationId:body.simulationId,state:session.sim.medical.snapshot()})}return this.response(200,{simulationId:body.simulationId,state:session.sim.snapshot(),finished:true})}catch(e){return this.response(e.status||400,{error:e.message})}}
 replay(id){try{const s=this.get(id),snapshot=s.sim.snapshot();return this.response(200,{simulationId:id,state:core.replay({scenario:s.scenario,seed:s.seed,eventLog:snapshot.eventLog})})}catch(e){return this.response(e.status||409,{error:e.message})}}
 handle({method,path,body={}}){if(method==='POST'&&path==='/simulation/start')return this.start(body);if(method==='POST'&&path==='/simulation/action')return this.action(body);if(method==='GET'&&path==='/simulation/state')return this.state(body.simulationId);if(method==='POST'&&path==='/simulation/finish')return this.finish(body);if(method==='GET'&&path==='/simulation/replay')return this.replay(body.simulationId);if(method==='GET'&&path==='/user/skills')return this.response(200,{skills:this.skillsProvider(body.userId)});if(method==='GET'&&path==='/user/progress')return this.response(200,{progress:this.progressProvider(body.userId)});return this.response(404,{error:'ROUTE_NOT_FOUND'})}
}
return{SimulationApi};
});
