(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.KoRishonInteractiveDebrief=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function normalize({events=[],protocol=[],doneAt={},penalties=[]}={}){
 const timeline=events.map((event,index)=>({id:`event-${index}`,kind:'performed',status:'done',time:Number(event.time)||0,label:String(event.action||'פעולה'),detail:String(event.result||''),key:event.key||null}));
 protocol.forEach(([key,label])=>{if(doneAt[key]==null)timeline.push({id:`missing-${key}`,kind:'missing',status:'missing',time:null,label:String(label),detail:'פעולת מפתח לא בוצעה',key})});
 penalties.forEach((label,index)=>timeline.push({id:`penalty-${index}`,kind:'penalty',status:'penalty',time:null,label:String(label),detail:'הפחתה שנרשמה במהלך התרחיש',key:null}));
 return timeline.sort((a,b)=>a.time==null?1:b.time==null?-1:a.time-b.time||a.id.localeCompare(b.id));
}
function filter(items,kind='all'){return kind==='all'?items:items.filter(item=>item.kind===kind)}
function timestamp(seconds){if(seconds==null)return 'לא בוצע';const value=Math.max(0,Math.floor(seconds));return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function mount(container,input){if(!container)throw new Error('DEBRIEF_CONTAINER_REQUIRED');const items=normalize(input);container.innerHTML=`<section class="interactive-debrief" aria-labelledby="interactiveDebriefTitle"><h3 id="interactiveDebriefTitle">בדיקה אינטראקטיבית של ההחלטות</h3><p class="interactive-help">בחר פעולה כדי לראות מתי בוצעה ומה הייתה התוצאה. פעולות חסרות והפחתות נשארות מסומנות.</p><div class="debrief-filters" role="group" aria-label="סינון התחקיר"><button type="button" data-filter="all" aria-pressed="true">הכול <b>${items.length}</b></button><button type="button" data-filter="performed" aria-pressed="false">בוצע <b>${items.filter(x=>x.kind==='performed').length}</b></button><button type="button" data-filter="missing" aria-pressed="false">חסר <b>${items.filter(x=>x.kind==='missing').length}</b></button><button type="button" data-filter="penalty" aria-pressed="false">הפחתות <b>${items.filter(x=>x.kind==='penalty').length}</b></button></div><div class="debrief-inspector"><ol class="debrief-timeline" aria-label="ציר החלטות"></ol><article class="debrief-detail" tabindex="0" aria-live="polite"><b>בחר פעולה מציר הזמן</b><p>הפרטים יופיעו כאן בלי לשנות את תוצאת התרחיש.</p></article></div></section>`;
 const list=container.querySelector('.debrief-timeline'),detail=container.querySelector('.debrief-detail');let activeFilter='all',activeId=null;
 function select(id,focusDetail=false){const item=items.find(x=>x.id===id);if(!item)return;activeId=id;list.querySelectorAll('button').forEach(button=>button.setAttribute('aria-current',button.dataset.id===id?'true':'false'));detail.innerHTML=`<small>${esc(timestamp(item.time))}</small><h4>${esc(item.label)}</h4><p>${esc(item.detail||'לא נרשמו פרטים נוספים.')}</p><p class="debrief-status ${esc(item.status)}">${item.kind==='performed'?'בוצע בתרחיש':item.kind==='missing'?'פעולת מפתח חסרה':'הפחתה בציון'}</p>`;if(focusDetail)detail.focus()}
 function render(){const visible=filter(items,activeFilter);list.innerHTML=visible.map(item=>`<li class="${esc(item.status)}"><button type="button" data-id="${esc(item.id)}" aria-current="${item.id===activeId?'true':'false'}"><time>${esc(timestamp(item.time))}</time><span>${esc(item.label)}</span><small>${item.kind==='performed'?'בוצע':item.kind==='missing'?'חסר':'הפחתה'}</small></button></li>`).join('')||'<li class="empty">אין פריטים בסינון הזה.</li>';list.querySelectorAll('button').forEach(button=>button.onclick=()=>select(button.dataset.id));if(visible.length&&!visible.some(x=>x.id===activeId))select(visible[0].id)}
 container.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{activeFilter=button.dataset.filter;container.querySelectorAll('[data-filter]').forEach(candidate=>candidate.setAttribute('aria-pressed',candidate===button?'true':'false'));render()});
 container.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Enter'].includes(event.key))return;const buttons=[...list.querySelectorAll('button')];if(!buttons.length)return;const current=Math.max(0,buttons.findIndex(button=>button.dataset.id===activeId));if(event.key==='Enter'){select(buttons[current].dataset.id,true);event.preventDefault();return}const next=(current+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();select(buttons[next].dataset.id);event.preventDefault()});
 render();container.dataset.interactiveDebrief='active';return{items:items.slice(),select,filter:kind=>{activeFilter=kind;render()}}}
 return{normalize,filter,timestamp,mount};
});
