(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.KoRishonNpcState=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const STATES=new Set(['standing-caller','kneeling-near-patient','approaching','stepping-back','executing-instruction','distressed-interfering','leaving','returning','observing']);
const ASSETS={'standing-caller':'./assets/realistic/witness/caller.png','kneeling-near-patient':'./assets/realistic/witness/kneeling.png','approaching':'./assets/realistic/final-composites/witness-third.png','stepping-back':'./assets/realistic/final-composites/witness-third.png','executing-instruction':'./assets/realistic/final-composites/witness-third.png','distressed-interfering':'./assets/realistic/witness/distressed.png','leaving':'./assets/realistic/final-composites/witness-third.png','returning':'./assets/realistic/final-composites/witness-third.png',observing:'./assets/realistic/final-composites/witness-third.png'};
const clone=x=>JSON.parse(JSON.stringify(x));
function hazardous(x){return x.hazardActive===true||/אש|חשמל|תנועה|חומר|עשן|מים|רטוב|מלגזה|רכב/.test(x.hazard||'')}
function initial(ctx){if(hazardous(ctx))return'stepping-back';if(ctx.patientConsciousness==='unresponsive')return'kneeling-near-patient';return ctx.distress>=.7?'distressed-interfering':'observing'}
function target(state,ctx){const p=ctx.patient||{x:0,z:0},side=ctx.environment==='urban'?-1:1;switch(state){case'kneeling-near-patient':return{x:p.x-side*1.25,z:p.z+.9};case'approaching':return{x:p.x+side*1.75,z:p.z+.62};case'stepping-back':return{x:p.x-side*2.8,z:p.z+1.5};case'standing-caller':return{x:p.x+side*2.65,z:p.z+.9};case'distressed-interfering':return{x:p.x+side*2.45,z:p.z+.15};default:return{x:p.x+side*2.4,z:p.z+1.1}}}
function distance(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}
class NpcStateMachine{constructor(context={}){this.context=clone(context);this.state=initial(this.context);this.sequence=0;this.events=[];this.position=target(this.state,this.context);this.record('scenario-start',null,this.state)}record(cause,from,to,extra={}){const event=Object.freeze({id:`npc:${String(this.sequence++).padStart(5,'0')}`,atMs:Number(extra.atMs||0),cause,from,to,caseKey:this.context.caseKey,environment:this.context.environment,patientState:this.context.patientConsciousness,hazardActive:hazardous(this.context)});this.events.push(event);return event}transition(input={}){const from=this.state;Object.assign(this.context,clone(input.context||{}));let to=from,cause=input.type||'timeline';if(hazardous(this.context)&&input.type!=='hazard-cleared')to='stepping-back';else if(input.type==='addressed'||input.type==='ask-witness')to='approaching';else if(input.type==='call-emergency')to='standing-caller';else if(input.type==='delegate')to='executing-instruction';else if(input.type==='depart')to='leaving';else if(input.type==='return')to='returning';else if(input.type==='distress'||(input.type==='timeline'&&this.context.distress>=.7))to='distressed-interfering';else if(input.type==='hazard-cleared')to=this.context.patientConsciousness==='unresponsive'?'kneeling-near-patient':'observing';else if(input.type==='arrived')to=this.context.patientConsciousness==='unresponsive'?'kneeling-near-patient':'observing';else if(input.type==='patient-changed')to=initial(this.context);else if(input.type==='timeline'&&this.context.callNeeded&&!this.context.callPlaced)to='standing-caller';this.state=to;this.position=target(to,this.context);const patient=this.context.patient||{x:0,z:0};if(!['leaving','returning'].includes(to)&&distance(this.position,patient)<1.1)throw new Error('NPC_PATIENT_OVERLAP');const event=this.record(cause,from,to,{atMs:input.atMs});return this.snapshot(event)}snapshot(lastEvent){const patient=this.context.patient||{x:0,z:0};return{state:this.state,position:clone(this.position),asset:ASSETS[this.state],grounded:true,clearance:distance(this.position,patient),lastEvent:lastEvent?clone(lastEvent):null,eventLog:clone(this.events)}}}
return{STATES,ASSETS,NpcStateMachine,initial,target};
});
