(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.KoRishonReporting=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const REPORT_TYPES=Object.freeze(['instructor','user','course','group']);
const clone=v=>JSON.parse(JSON.stringify(v));
const csvCell=v=>'"'+String(v===undefined||v===null?'':typeof v==='object'?JSON.stringify(v):v).replace(/"/g,'""')+'"';
function buildReport({type='user',simulationId,snapshot,subject={},generatedAtMs=0}){if(!REPORT_TYPES.includes(type))throw new Error('REPORT_TYPE_UNKNOWN');if(!snapshot||!snapshot.eventLog)throw new Error('REPORT_SNAPSHOT_REQUIRED');const events=snapshot.eventLog.events||[];return{schemaVersion:'report-1.0.0',type,simulationId:simulationId||snapshot.eventLog.meta.scenarioId,generatedAtMs,subject:clone(subject),summary:{eventCount:events.length,finalCondition:snapshot.medical&&snapshot.medical.condition,integrity:snapshot.eventLog.integrity||null},medical:clone(snapshot.medical||{}),events:clone(events),causalLinks:clone(snapshot.causalLinks||[])}}
function toJSON(report){return JSON.stringify(report,null,2)}
function toCSV(report){const rows=[['sequence','timeMs','type','eventId','condition','payload']];for(const e of report.events)rows.push([e.sequence,e.timeMs,e.type,e.id,e.state&&e.state.condition,e.payload]);return rows.map(row=>row.map(csvCell).join(',')).join('\n')}
function pdfEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function toPDF(report){const lines=[`Ko Rishon ${report.type} report`,`Simulation: ${report.simulationId}`,`Events: ${report.summary.eventCount}`,`Final condition: ${report.summary.finalCondition===undefined?'n/a':report.summary.finalCondition}`,`Integrity: ${report.summary.integrity&&report.summary.integrity.valid?'valid':'unverified'}`];const stream=['BT','/F1 14 Tf','50 790 Td',...lines.flatMap((line,i)=>i?[`0 -22 Td`,`(${pdfEscape(line)}) Tj`]:[`(${pdfEscape(line)}) Tj`]),'ET'].join('\n');const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let out='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=out.length;out+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)out+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return out}
function exportReport(report,format){if(format==='json')return{mimeType:'application/json',extension:'json',data:toJSON(report)};if(format==='csv')return{mimeType:'text/csv',extension:'csv',data:toCSV(report)};if(format==='pdf')return{mimeType:'application/pdf',extension:'pdf',data:toPDF(report)};throw new Error('REPORT_FORMAT_UNKNOWN')}
return{REPORT_TYPES,buildReport,toJSON,toCSV,toPDF,exportReport};
});
