'use strict';
// Private test-owned adapter/checkpoint only. Not an owner grant or real ledger connection.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{digest,deepFreeze}=require('../../contracts/canonical'),C=require('../door-world-genesis/candidate');
const root=path.resolve(__dirname,'../../../..'),data=['evidence/verified-architecture-phase2/surface-models/school.json','evidence/track-b/scene-camera-candidate/packet-v1_5.json'];
function closure(){const seen=new Set(),pending=[__filename];while(pending.length){const p=pending.pop();if(seen.has(p))continue;seen.add(p);for(const m of fs.readFileSync(p,'utf8').matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g))if(m[1].startsWith('.')){const q=require.resolve(path.resolve(path.dirname(p),m[1]));if(!q.startsWith(root+path.sep))throw Error('OUTSIDE_ROOT');pending.push(q)}}return Object.fromEntries([...seen,...data.map(p=>path.join(root,p))].sort().map(p=>[path.relative(root,p),crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]))}
const unknown=reason=>deepFreeze({status:'UNKNOWN',reason,classification:'PRIVATE_DECISION_STORE_FIXTURE_NOT_OPERATIONAL',operationalStatus:'UNKNOWN'});
function createPrivateFixture({packet,...extra}={}){try{if(Object.keys(extra).length)return unknown('CALLER_AUTHORITY_OR_EXTRA_INPUT');const g=C.prepareGenesis(packet),binding={packetDigest:digest(packet),modelDigest:g.surfaceModel.surfaceModelDigest,worldDigest:g.genesis.stateDigest,genesisDigest:g.genesis.stateDigest,eventHeadDigest:'0'.repeat(64),sourceClosureDigest:digest(closure())},tokens=new WeakMap();let epoch=0,entries=[],head=null,decision=null,replayed=false;
 function validate(log){if(!Array.isArray(log)||log.length!==entries.length)return unknown('TRUSTED_CHECKPOINT_LENGTH_MISMATCH');let prior=null,terminal=false;for(let i=0;i<log.length;i++){const e=log[i];if(e.sequence!==i+1||e.epoch!==i+1||e.priorDigest!==prior||e.entryDigest!==digest({...e,entryDigest:undefined})||digest(e.binding)!==digest(binding)||!['PREPARATION_READY','REVOKED'].includes(e.decision)||terminal)return unknown('REPLAY_CHAIN_OR_BINDING_INVALID');terminal=e.decision==='REVOKED';prior=e.entryDigest}if(prior!==head)return unknown('TRUSTED_CHECKPOINT_HEAD_MISMATCH');return deepFreeze({status:'PRIVATE_REPLAY_MECHANICS_ONLY',epoch,decision:log.at(-1)?.decision||null,operationalStatus:'UNKNOWN'})}
 const driver=Object.freeze({append({expectedEpoch,nextDecision,...rest}={}){if(Object.keys(rest).length||expectedEpoch!==epoch||decision==='REVOKED'||!['PREPARATION_READY','REVOKED'].includes(nextDecision))return unknown('EPOCH_TERMINAL_OR_DECISION_INVALID');const b={sequence:epoch+1,epoch:epoch+1,priorDigest:head,binding,decision:nextDecision},e=deepFreeze({...b,entryDigest:digest(b)});entries=[...entries,e];head=e.entryDigest;epoch++;decision=nextDecision;replayed=false;return deepFreeze({status:'PRIVATE_APPEND_ONLY',epoch})},exportPrivateLog(){return deepFreeze(structuredClone(entries))},restart(){epoch=entries.length;replayed=false;return unknown('RESTART_REQUIRES_REPLAY')}});
 const adapter=Object.freeze({replay({log,...rest}={}){if(Object.keys(rest).length)return unknown('EXTRA_INPUT');const v=validate(log);replayed=v.status==='PRIVATE_REPLAY_MECHANICS_ONLY';return v},mint(){if(!replayed||decision!=='PREPARATION_READY'||digest(closure())!==binding.sourceClosureDigest)return unknown('UNREPLAYED_REVOKED_OR_SOURCE_CHANGED');const token=Object.freeze({classification:'OPAQUE_PRIVATE_FIXTURE_TOKEN_NOT_AUTHORITY'});tokens.set(token,{epoch,bindingDigest:digest(binding)});return token},inspect({token,currentBinding,...rest}={}){try{const t=tokens.get(token);if(Object.keys(rest).length||!t)return unknown('TOKEN_NOT_ADAPTER_MINTED');if(!replayed||decision!=='PREPARATION_READY'||t.epoch!==epoch||t.bindingDigest!==digest(currentBinding)||digest(closure())!==binding.sourceClosureDigest)return unknown('STALE_REVOKED_UNREPLAYED_OR_SOURCE_CHANGED');return deepFreeze({status:'PRIVATE_TOKEN_MECHANICS_ONLY_NOT_OPERATIONAL',epoch,bindingDigest:t.bindingDigest,operationalStatus:'UNKNOWN'})}catch{return unknown('TOKEN_INPUT_INVALID')}}});
 return Object.freeze({classification:'PRIVATE_DECISION_STORE_FIXTURE_NOT_OPERATIONAL',binding:deepFreeze(binding),driver,adapter,limitations:deepFreeze(['TEST_OWNED_IN_MEMORY_CHECKPOINT_NOT_DURABLE','NO_REAL_LEDGER_ADAPTER_OR_OWNER_AUTHORITY_ROUTE','TOKEN_IS_FIXTURE_ONLY_NO_ADMISSION_OR_COMMIT_PERMISSION','NO_WATCHER_SCHEDULE_OR_OPERATIONAL_CONNECTION'])});
 }catch{return unknown('FIXTURE_INPUT_OR_CLOSURE_INVALID')}}
module.exports={createPrivateFixture};
