'use strict';
// Independent identity-orientation bag/unit query mechanics only. No positive port.
const {digest,deepFreeze}=require('../../contracts/canonical'),C=require('../door-world-genesis/candidate'),S=require('../door-world-structure/candidate'),D=require('../definitions/synthetic-training-unit-v1'),{SCHOOL_BAG_BODY}=require('../school-physical-contract'),{projectKnownBodyBounds}=require('../door-legality-adapter');
const CONTACT_TOLERANCE_MICROUNITS=0,axes=['X','Y','Z'],keys=axes.flatMap(k=>['min'+k,'max'+k]),eq=(a,b)=>digest(a)===digest(b),intersects=(a,b)=>axes.every(k=>a['min'+k]<b['max'+k]&&b['min'+k]<a['max'+k]);
function translate(b,p){const r=Object.fromEntries(keys.map(k=>[k,b[k]+p[axes.indexOf(k.slice(-1))]]));if(!Object.values(r).every(Number.isSafeInteger))throw Error('TRANSLATION_OVERFLOW');return r}
function bounds(e){const b=projectKnownBodyBounds(e),p=e?.transform?.positionMicrounits;if(!b||!Array.isArray(p)||p.length!==3||!p.every(Number.isSafeInteger)||!eq(e.transform.orientation,[0,0,0,1])||!eq(e.transform.scaleMicrounits,[1000000,1000000,1000000])||e.lifecycleState!=='ACTIVE'||e.postureStateId!=='rigid'||e.physicalBodyRef.proofGeometryDigest!==e.physicalBodyRef.digest)throw Error('BODY_TRANSFORM_OR_POSTURE_UNSUPPORTED');return translate(b,p)}
function inspectBagUnitQuery({packet,surfaceModel,proposedState,entityId,...extra}={}){const out=(outcome,reason,detail={})=>deepFreeze({outcome,reason,classification:'BAG_UNIT_DIRECT_PREPARATION_NOT_ADMITTED',operationalStatus:'UNKNOWN',...detail});try{
 if(Object.keys(extra).length)return out('UNKNOWN','EXTRA_INPUT');const g=C.prepareGenesis(packet);if(!eq(surfaceModel,g.surfaceModel)||S.validateStructure(surfaceModel).status!=='DOORWAY_FLOOR_STATIC_TOPOLOGY_VALIDATED_NOT_ADMITTED')return out('UNKNOWN','EXACT_MODEL_STRUCTURE_REQUIRED');if(proposedState.worldId!==g.genesis.worldId||!eq(proposedState.sceneDefinitionRef,g.genesis.sceneDefinitionRef)||!eq(proposedState.surfaces,g.genesis.surfaces)||!eq(proposedState.environmentPhysicalState,g.genesis.environmentPhysicalState))return out('UNKNOWN','EXACT_CLOSED_MODEL_BINDING_REQUIRED');
 const bag=proposedState.entities['school-medical-bag'],unit=proposedState.entities['synthetic-training-unit-v1'];if(!['school-medical-bag','synthetic-training-unit-v1'].includes(entityId)||!bag||!unit||bag.entityId!=='school-medical-bag'||unit.entityId!=='synthetic-training-unit-v1'||bag.physicalBodyRef.recordId!==SCHOOL_BAG_BODY.bodyId||unit.physicalBodyRef.recordId!==D.UNIT_BODY.definition.bodyDefinitionId)return out('UNKNOWN','EXACT_ENTITY_BODY_PAIR_REQUIRED');
 const bb=bounds(bag),ub=bounds(unit),surface=D.INTERIOR_FLOOR.definition,volume=D.CONTAINMENT_VOLUME.definition,binding=D.OWNER_BODY_BINDING.binding;if(!eq(bag.physicalState.supportSurface,{supportSurfaceId:surface.supportSurfaceId,surfaceRevision:surface.surfaceRevision,canonicalDigest:surface.canonicalDigest})||!eq(bag.physicalState.supportVolume,{supportVolumeId:volume.supportVolumeId,volumeRevision:volume.volumeRevision,canonicalDigest:volume.canonicalDigest})||!eq(binding.recoveredBodyRef,{id:bag.physicalBodyRef.recordId,revision:bag.physicalBodyRef.revision,digest:bag.physicalBodyRef.digest}))return out('UNKNOWN','SUPPORT_OWNER_OR_VOLUME_PINS_STALE');
 const pkg=require('../../../../scripts/track-b/gate-a-r1v4-package-builder').buildV21(),actual=proposedState.supportRelations.filter(r=>[bag.entityId,unit.entityId].includes(r.supportedEntityId));const expected=pkg.supportRelations.filter(r=>[bag.entityId,unit.entityId].includes(r.supportedEntityId)).map(r=>({...r,boundWorldRevision:proposedState.revision+1,...(r.supportSourceKind==='STATIC_WORLD'?{surfaceModelRef:{id:surfaceModel.surfaceModelId,revision:surfaceModel.revision,digest:surfaceModel.surfaceModelDigest}}:{}),...(r.supportSourceKind==='ENTITY_OWNED'?{ownerEntityRef:{id:bag.entityId,revision:bag.revision}}:{})}));if(!eq([...actual].sort((a,b)=>a.relationId.localeCompare(b.relationId)),[...expected].sort((a,b)=>a.relationId.localeCompare(b.relationId))))return out('UNKNOWN','EXACT_RELATIONS_REQUIRED_NOT_NAME_EXEMPTION');
 const floor=surfaceModel.surfaces.find(s=>s.surfaceId==='floor'),room=floor.region.allowed[0],plane=Math.round(floor.planeOrDepth.planeY*1e6);if(bb.minY!==plane||bb.minX<room.minX*1e6||bb.maxX>room.maxX*1e6||bb.minZ<room.minZ*1e6||bb.maxZ>room.maxZ*1e6||bag.physicalState.surfaceId!=='floor'||unit.physicalState.surfaceId!==surface.supportSurfaceId)return out('UNKNOWN','EXPLICIT_ROOM_FLOOR_CONTACT_OR_FOOTPRINT');
 if(surface.transformBinding!=='OWNER_TRANSLATION_IDENTITY_ORIENTATION'||volume.transformBinding!=='OWNER_TRANSLATION_IDENTITY_ORIENTATION')return out('UNKNOWN','DEFINITION_TRANSFORM_UNSUPPORTED');const p=bag.transform.positionMicrounits,v=translate(volume.localBoundsMicrounits,p),local=surface.localRegion,contact={minX:local.minX+p[0],maxX:local.maxX+p[0],minZ:local.minZ+p[2],maxZ:local.maxZ+p[2],planeY:surface.localPlane.offsetMicrounits+p[1]};if(!Object.values(contact).every(Number.isSafeInteger))throw Error('SURFACE_OVERFLOW');if(Math.abs(ub.minY-contact.planeY)>CONTACT_TOLERANCE_MICROUNITS||ub.minX<contact.minX||ub.maxX>contact.maxX||ub.minZ<contact.minZ||ub.maxZ>contact.maxZ)return out('UNKNOWN','UNIT_BOTTOM_CONTACT_OR_FULL_FOOTPRINT');if(!(ub.minX>v.minX&&ub.maxX<v.maxX&&ub.minY>=v.minY&&ub.maxY<v.maxY&&ub.minZ>v.minZ&&ub.maxZ<v.maxZ))return out('UNKNOWN','FULL_3D_CONTAINMENT_MISSING');
 const solids=surfaceModel.surfaces.filter(s=>['WALL','OBSTACLE'].includes(s.type)).flatMap(s=>s.region.volumes.map(v=>Object.fromEntries(keys.map(k=>[k,Math.round(v[k]*1e6)])))).concat([surfaceModel.doorDefinition.closedLeaf]);if([bb,ub].some(b=>solids.some(s=>intersects(b,s))))return out('UNKNOWN','STATIC_OR_CLOSED_LEAF_CONTACT');
 for(const e of Object.values(proposedState.entities)){if(e.entityId===bag.entityId||e.entityId===unit.entityId||e.lifecycleState==='REMOVED')continue;const ob=projectKnownBodyBounds(e),p=e.transform?.positionMicrounits;if(!ob||!Array.isArray(p)||p.length!==3||!p.every(Number.isSafeInteger)||!eq(e.transform.orientation,[0,0,0,1])||!eq(e.transform.scaleMicrounits,[1000000,1000000,1000000]))return out('UNKNOWN','OTHER_BODY_UNSUPPORTED');const b=translate(ob,p);if(intersects(bb,b)||intersects(ub,b))return out('UNKNOWN','NON_PROVEN_PAIR_DYNAMIC_COLLISION')}
 return out('BAG_UNIT_DIRECT_CLEAR_PREPARATION_NOT_ADMITTED','EXACT_BAG_FLOOR_AND_UNIT_CONTACT_CONTAINMENT_RECOMPUTED',{contactToleranceMicrounits:CONTACT_TOLERANCE_MICROUNITS,containmentRecomputed:true,proofDigest:digest({bb,ub,contact,v,binding,actual}),limitations:['IDENTITY_ORIENTATION_ONLY_ROTATED_DEFINITIONS_UNSUPPORTED_UNKNOWN','EXPLICIT_EXACT_RELATION_PROTOTYPES_PLUS_RECOMPUTED_CONTACT_NOT_GENERAL_SUPPORT','STRICT_INTERIOR_SIDES_AND_TOP_CONTACT_BOTTOM_ALLOWED','NO_POSITIVE_PORT_COMMIT_ADMISSION_RENDER_OR_NAVIGATION']});
 }catch{return out('UNKNOWN','BAG_UNIT_INPUT_OR_DEFINITION_UNSUPPORTED')}}
module.exports={inspectBagUnitQuery};
